- .eslintrc.json
將comma-dangle 這則lint rule 調整為：
comma-dangle: ["error", "always-multiline"]
> eslint config(comma-dangle)

- .eslintrc.json
- package.json
- src/reducers/counter.js
- webpack.config.base.js
- yarn.lock
由webpack / resolve 設定，讓 "common" 與 "utils" 成為全域下可以直接import 的路徑
並且因應此設定
1. 增加extract-text-webpack-plugin
2. 在.eslintrc.json 中指出webpack.config.base.js 以避免lint 錯誤
（不過editor 的似乎還是會報錯，這邊可能要額外的設定）
> make "common" and "utils" to core modules

- src/components/common/Columns.js
1. 把map的key放對位置
2. 把`Item`設為`PropTypes.func` (原本的`PropTypes.node`是錯的，node指的是instance而不是class)
> 解掉Columns的React warnings

- src/actions/laborRights.js
- src/components/LaborRightsMenu/index.js
- src/components/LaborRightsSingle/index.js
- src/containers/LaborRightsMenu.js
- src/containers/LaborRightsSingle.js
- src/reducers/laborRights.js
#55 
1. 新增三種ActionCreator:
- `fetchLaborRights`: Async action，會呼叫contentfulUtil，並利用以下兩個action設定state
- `setLaborRights`: 將下載好的小教室放進store
- `setLaborRightsStatus`: 設定目前小教室的狀態，如下：
- `UNFETCHED`: 尚未下載的狀態；小教室`componentDidMount`在發現`status==UNFETCHED`才會啟動`LOAD_LABOR_RIGHTS`
- `FETCHING`: 已啟動下載但尚未收到回應的狀態；會渲染LOADING字樣
- `FETCHED`: 已啟動下載並收到回應的狀態；會正常顯室小教室內容
- `ERROR`: 下載發生錯誤的狀態；會渲染Error message
目前status是跟actions/laborRights放一起，不過我覺得可以獨立出來共用
2. SSR
`fetchData`直接`dispatch(fetchLaborRights())`，不需要檢查是否`status==UNFETCHED`
> 小教室狀態(Loading&Error) + SSR

- src/index.js
- src/server.js
- src/store/configureStore.dev.js
- src/store/configureStore.prod.js
1. 根據 react-router-redux ，`routerMiddleware` 會需要 history 來運作
```
import { push } from 'react-router-redux';
store.dispatch(push('/foo'));
```
這樣就可以透過 Action 轉址到 /foo
2. Server Side 端沒有 browserHistory，而只有 memoryHistory，所以
configureStore 就需要 history 這個變數來設定 routerMiddleware
3. 改成這樣之後，ActionCreator 就可以 dispatch 一個 redirect 等 Action
> 讓 configureStore 由外部決定 history

- src/components/LaborRightsSingle/Footer.js
- src/components/Layout/Header/index.js
- src/components/common/FacebookProvider.js
- src/components/common/FacebookWrapper.js
- src/utils/facebook.js
這個 PR 分成兩個部分
1. 將 FB SDK 引入
2. 與我們現有的 Component 搭配
(1.) 的部分：
FB SDK 會在 loading 完成後執行 `window.fbAsyncInit`，所以參考資料來源寫了一個與 React 結合的 Component `FacebookProvider`
(2.) 的部分
經過測試：
這裡遇到最大的問題是：
FB 的按讚按鈕不是 React Render 的，所以當我們小教室切換時，React 只會更新 
```
<div
className="fb-like"
data-href={formatCanonicalPath(`/labor-rights/${id}`)}
data-layout="button_count"
data-action="like"
data-size="large"
data-show-faces="false"
data-share="true"
/>
```
會導致按讚按鈕停留在舊的狀態
用 `componentDidUpdate` 讓 FB XFBML 重新 parse 即可
> Facebook 登入與 Like Button

- src/components/ShareExperience/InterviewForm/index.js
- src/components/ShareExperience/common/SubmitArea.js
- src/components/common/button/ButtonSubmit.js
- src/containers/ShareExperience/SubmitAreaContainer.js
此PR 讓表單送出的行為，經過FB 登入，以順利post。
* 讓SubmitArea 與登入狀態綁定，若未登入則登入並接著執行onSubmit 的行為
> 表單送出與FB 登入整合

- src/components/ShareExperience/common/FacebookFail.js
- src/components/ShareExperience/common/FailFeedback.js
- src/components/ShareExperience/common/SubmitArea.js
- src/components/ShareExperience/common/SuccessFeedback.js
- src/components/common/Modal.js
- src/components/common/button/ButtonSubmit.js
- src/components/common/button/ButtonSubmit.module.css
這個PR 主要在補上填寫頁面的送出回饋
* 送出成功、失敗的回饋UI
* 成功後的按鈕讓他直接跳轉到該篇的頁面
* 失敗則讓他關閉Modal
* Modal 加上`hasClose` 的選項讓使用者可以選擇該Modal 是否要包含 **關閉按鈕 X**
* 我還沒辦法模擬出FB 登入的失敗，所以登入失敗單獨的回饋則沒有接上，我用斷網來測，是會回到上述通用的「失敗」
#147
> 兩個填寫頁的送出回饋，以及元件Style

- src/components/ShareExperience/InterviewForm/formCheck.js
- src/components/ShareExperience/InterviewForm/formCheck.test.js
- src/components/ShareExperience/utils.js
修改form checking function
並且在form to api body 中間修改為，不排除答案為空的qa object
#170
> 修正面試QA 答案不可空白問題

- src/components/About/index.js
- src/components/Contact/index.js
- src/components/ExperienceDetail/index.js
- src/components/ExperienceSearch/index.js
- src/components/Faq/index.js
- src/components/LaborRightsMenu/index.js
- src/components/LaborRightsSingle/index.js
- src/components/LandingPage/index.js
- src/components/Layout/index.js
- src/components/Privacy/index.js
- src/components/Recruit/index.js
- src/components/ShareExperience/Entry.js
- src/components/ShareExperience/InterviewForm/index.js
- src/components/ShareExperience/WorkExperiencesForm/index.js
- src/components/Terms/index.js
- src/constants/helmetData.js
partly solve #4 
1. 新增 `helmetData.js` 這個constant file，管理所有`靜態`的 head information。比較不會資訊四散各地，不好維護。
2. 針對 head information 需要`動態`改變的頁面：`/labor-rights/:id` `/experiences/:id` 。 則是直接在component 內部讀取資料，產生helmet所需的資訊。
3. 目前 helmetData 裡面的資訊只是初版，待行銷組完全確定後，會再另送ＰＲ修正。請主要看結構有沒有問題、實際測試是否有真的產生 head informat。
4. 測試的方法是打開原始碼去看，是否真的產生對應的資訊。不要用inspect element 的方式，因為那可能是前端後來才render出來的。
> Refactor helmet

- src/components/ExperienceSearch/index.js
我本來是試著調整 CSS，但後來仔細看了一下，發現「每一篇經驗 (元件: ExperienceBlock)」的樣式還有分 m 跟 l 兩種，所以猜想 m 是給首頁用的，所以我在經驗搜尋頁這裡，把「每一篇經驗」套用 l 這個樣式，試了一下 chrome 跟 ff 都不會有 overlap 的問題了 ... 但這部份可能還要麻煩 @wutingy 幫忙確認一下是不是這個樣子。
> fixed the style error of experience block (#192)

- src/components/ShareExperience/InterviewForm/InterviewInfo/InterviewTime.js
- src/components/ShareExperience/InterviewForm/InterviewInfo/index.js
- src/components/ShareExperience/InterviewForm/index.js
- src/components/ShareExperience/common/CompanyQuery.js
- src/components/ShareExperience/common/JobTitle.js
- src/components/ShareExperience/common/Region.js
- src/constants/formElements.js
這個 PR 主要是想改善使用者體驗，當使用有未成功填寫的欄位，可以捲到最上方未成功填寫的 component 上。
如果要scroll 到最上方未填寫成功的欄位，就必須要有個地方搜集各個欄位填寫的狀況。
最直覺得做法是讓 interviewForm 這個 component 去 maintain 每個需要驗證的欄位的狀態（分為用state / 不用 state 儲存)。（或者是用redux）
而我是選擇將每個需要驗證的欄位的驗證狀態，存在 interviewForm component 裡面的非state變數裡。並且使用 react-scroll ，在欄位偷塞一個scroll element，讓我可以捲到指定的位置。
* 為什麼不用 redux ? 
因為原本的interviewForm 沒有用到，每個欄位的值是maintain在state裡面，就不改架構了。
* 為什麼不用 state ? 
因為這些變數單純是要拿來找到最上方未填寫成功的欄位，跟 render 無關，不須存在 state 裡面。存在裡面要更新 state 比較繁瑣。
依此類推。 目前僅完成 公司、面試地區、職稱、面試時間。
先確定這樣的 framework  OK，我再把剩下的完成。
建議先看第一個 commit   327c3c9 即可
> 面試經驗表單捲動到最上方未填寫成功的欄位

- src/components/ShareExperience/InterviewForm/InterviewInfo/InterviewResult.js
- src/components/ShareExperience/InterviewForm/formCheck.js
- src/components/ShareExperience/InterviewForm/formCheck.test.js
目前面試結果的檢驗規則是 (0, 10]
這個PR 修改了之前錯誤理解的form checking function ，以及對應的測試
#188
> 面試結果檢驗規則錯誤

- src/components/ExperienceDetail/BackToList.js
- src/components/ExperienceDetail/index.js
- src/components/ExperienceSearch/ExperienceBlock.js
- src/components/ExperienceSearch/index.js
利用query string 帶入 `backable` 來判斷是否要 `goBack()` 還是 `push('/experience/search')`
實作是在 `ExperienceBlock` Link.to 來夾帶backable = 1
不過因為LandingPage 也是用這個元件來放連結，所以從LandingPage 進入單篇經驗，也會觸發 `goBack()` 造成預期應該返回列表，但其實是跳到LandingPage 的情況。
closes: #224
> 修正單篇經驗頁面返回不會正確回到列表的問題

- src/components/ShareExperience/InterviewForm/InterviewExperience/index.js
- src/components/ShareExperience/InterviewForm/InterviewInfo/index.js
- src/components/ShareExperience/InterviewForm/index.js
- src/components/ShareExperience/WorkExperiencesForm/WorkExperience/index.js
- src/components/ShareExperience/WorkExperiencesForm/WorkInfo/index.js
- src/components/ShareExperience/WorkExperiencesForm/index.js
- src/components/ShareExperience/common/Region.js
- src/components/common/subscribeValidation.js
- src/constants/formElements.js
昨天跟彥齊討論完，認為捲動到最上方驗證未過的元件這件事，有太多重複的地方，可以嘗試用 HOC來解。
所以這邊寫了一個 prototype。
簡而言之是寫了一個 HOC `subscribeValidation`，必須要傳入以下四個參數：
* `WrappedComponent`: 要被包住的component
* `validate`: 如何運用該component 的props 去驗證欄位是否符合格式
* `elementName`: hidden 的 scrolling element 名稱
* `onChangeFuncName`: 該 component 的 props裡面，用來更新validation status的函數名稱
不過 server-side-rendering 的時候，會遇到問題。
如果我直接貼網址 `{host}/share/work-experiences` ，前端 server 會出現：
```
(node:51869) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 44): TypeError: Cannot read property 'props' of undefined
```
但從其他頁進去，功能就正常
這是什麼原因？
> HOC 實作 捲動到最放上方驗證未過元件

- src/components/ExperienceDetail/index.js
- src/containers/ExperienceDetailPage.js
- src/selectors/authSelector.js
1. 增加一個authStatus 的selector
2. 將auth.status 連結至ExperienceDetail
3. 在 `componentWillReceiveProps` 中判斷，若獲得新的authStatus 並且是 `connected` ，則重新呼叫 `this.props.fetchExperience(this.props.params.id)`
我看應該是沒有個別獲取按讚資訊的api ，所以就全撈。
closes: #205
> 在登入成功後重新抓取單頁經驗資料

- src/components/common/subscribeValidation.js
這個問題由 #225 來的，當 NODE_ENV 是 production 的時候，babel-plugin-react-pure-components
嘗試將 class 轉成 pure function
但，有可能是它的 bug，轉換過程，anonymous class 會導致 "Cannot read property 'name' of null"
目前是先加上名稱，不確定是否有更好的解法？
* 由於是 hot fix，所以先 merge 讓線上可以運作
* 有更多修正，麻煩再 revert 這個
> Resolve babel-plugin-react-pure-components causing error

- src/components/ExperienceDetail/MessageBoard.js
- src/components/ShareExperience/common/SubmitArea.js
- src/components/common/button/ButtonSubmit.js
- src/components/common/button/ButtonSubmit.module.css
- src/components/common/button/WhyFacebookAuth.js
- src/components/common/form/Checkbox.js
closes: #237 
closes: #240 
* 加上單篇經驗頁面、填寫頁中的送出區域的**使用者條款**、**發文留言規定**連結
* 增加**為什麼需要 Facebook 帳戶驗證？** 的modal
* 在 `Checkbox` 加上style （因為置中跑版）
* 單篇經驗頁那裡，之前按鈕底下就沒有 **為什麼需要 Facebook 帳戶驗證？** ，所以就沒特別加上，連帶modal 也沒有
> 加上送出區塊必須的連結、提示

- src/actions/timeAndSalaryCompany.js
- src/actions/timeAndSalaryJobTitle.js
- src/components/TimeAndSalary/TimeAndSalaryCompany/index.js
- src/components/TimeAndSalary/TimeAndSalaryJobTitle/index.js
- src/containers/TimeAndSalary/TimeAndSalaryCompany.js
- src/containers/TimeAndSalary/TimeAndSalaryJobTitle.js
- src/reducers/timeAndSalaryBoard.js
- src/reducers/timeAndSalaryCompany.js
- src/reducers/timeAndSalaryJobTitle.js
#316 
本PR做了以下事情：
1. `TimeAnsSalary{Company, JobTitle}`的Select onChange觸發`swtichPath`跳轉
2. 把`TimeAndSalary{Company, JobTitle}`中`pathnameMapping`的`{viewParams: { sortBy/groupSortBy, order }}`一律統一改寫為`{ groupSortBy, order }`，減少物件的深度，並保持參數原本的命名意義
> 薪時查詢頁面 - Select 跳轉 與參數改寫

- src/components/TimeAndSalary/TimeAndSalaryBoard/TimeAndSalaryBoard.module.css
- src/components/TimeAndSalary/TimeAndSalaryBoard/index.js
- src/components/TimeAndSalary/common/WorkingHourTable.js
- src/components/TimeAndSalary/common/WorkingHourTable.module.css
- src/components/TimeAndSalary/views/view.module.css
#316 
為了重覆利用`common/WorkTimeTable`已寫好的table style，本PR將`common/WorkTimeTable`的style拆成兩部份：
1. 共用的style，如`.bar`、`.dot`等等
2. 個別頁面的style，如只有`common/WorkTimeTable`才會用到的`.companyTable`不同column的欄寬等等
然後便可以調整`TimeAndSalaryBoard`的style為：
1. 使用共用style
2. 唯`TimeAndSalaryBoard`才會使用的`.latestTable`
目前是把`1.`的共用styles移往`views/view.module.css`，因為`views/view`是目前TimeAndSalary每一頁必引入的共用style。
> 最新薪時頁面的table style

- src/components/TimeAndSalary/TimeAndSalaryBoard/index.js
- src/components/TimeAndSalary/TimeAndSalaryCompany/index.js
- src/components/TimeAndSalary/TimeAndSalaryJobTitle/index.js
- src/components/common/form/Select.js
此PR解決 #316 提到的移除切換route path的Select的placeholder。（討論串：#330 ）
本PR將placeholder修正名稱為nullOption（空選項）並增加兩個相對應的參數：
- `hasNullOption`: 預設`true`
- `nullOptionText`: 預設為`- 請選擇 -`
`TimeAndSalary`所用到的`Select`指定`hasNullOption=false`
> Select元件的placeholder修訂名稱為nullOption並增加參數

- src/components/ExperienceSearch/Banners/Banner1.js
- src/components/ExperienceSearch/Banners/Banner2.js
- src/components/LaborRightsMenu/index.js
- src/components/LandingPage/Banner.js
- src/components/Layout/Header/Top/index.js
- src/components/TimeAndSalary/TimeAndSalaryBoard/CallToActionRow.js
- src/utils/callToActionUtils.js
Close #321 
所有 call to action 用途的連結改為隨機到面試或工作經驗表單頁
1. 實作一個隨機挑選 /share/interview or /share/work-experience 連結的 util function c824e00
2. 將所有 call to action 用途的 component 換成用該 function 取得連結 b22abcc
3. 補上 小教室選單頁 call to action 用途的 component 換成用該 function 取得連結 133835a
> 所有 call to action 用途的連結改為隨機到面試/工作經驗表單頁

- src/components/Layout/Header/index.js
- src/components/Layout/index.js
part of #322 
讓首頁不要顯示上方的募資條。
實作方法是把 App component 從 router 拿到 location 物件往下傳到 Header ，在 Header 判定要不要 render Top component (header 上方的募資條）
> 首頁不要顯示 header 上方的募資條

- src/actions/timeAndSalaryBoard.js
- src/apis/timeAndSalaryApi.js
- src/components/TimeAndSalary/TimeAndSalaryBoard/TimeAndSalaryBoard.module.css
- src/components/TimeAndSalary/TimeAndSalaryBoard/index.js
- src/components/TimeAndSalary/views/view.module.css
- src/containers/TimeAndSalary/TimeAndSalaryBoard.js
- src/reducers/timeAndSalaryBoard.js
Close #   
1. 薪時查詢頁面放上極端值的說明 & 隱藏/顯示鈕
2. 完成極端薪時的action、reducer、api，並顯示於表格中
3. 極端薪時的資料置於`state.timeAndSalaryBoard.{extremeData, extremeStatus, extremeError}`
#337 
on small device: 
- 點選「顯示」會載入極端薪時
- log會顯示state change
> Update: 薪時查詢極端值

- src/constants/helmetData.js
Close #356
#356 的 issue 指出，push 會導致原本的資料被修改（data.meta 會越來越多東西）
透過 getter 讓取得物件時， 會回傳新的物件
在 `src/components/ExperienceSearch/index.js` 的 `renderHelmet()` 可以放上 `console.log(data)`
在 PR 前可以看到
```
{ title: '查詢面試、工作經驗',                     
meta:                  
[ { property: 'og:title', content: '查詢面試、工作經驗 | GoodJob 好工作評論網' },                   
{ property: 'og:url',                         
content: 'https://www.goodjob.life/experiences/search' },                                       
{ property: 'og:image',                       
content: 'https://image.goodjob.life/og/experience-search.jpg' },                               
{ name: 'description',                        
content: '馬上查詢超過 90 篇面試及工作經驗分享，讓我們一起把面試準備的更好，也更瞭解公司內部的真實樣貌，找到更適合自己的好工作！' },               
{ property: …
```
> Hotfix #356, 解決意外修改到原本的資料

- src/components/TimeAndSalary/index.js
- src/constants/helmetData.js
Close #362 
產生薪資工時查詢頁的 helmet 資訊
1.
路徑包含 `work-time-dashboard` => `工時排行榜（由高到低）`
路徑包含 `sort/work-time-asc` => `工時排行榜（由低到高）`
路徑包含 `salary-dashboard` => `估算時薪排行榜（由高到低）`
路徑包含 `sort/salary-asc` => `估算時薪排行榜（由低到高）`
路徑包含 `latest` => `最新薪資、工時資訊`
路徑包含 `sort/time-asc`=>  `最舊薪資、工時資訊`
2.
路徑包含 /company/:company => 前方再加上 company 名稱
路徑包含 /job-title/:company => 前方再加上 job-title 名稱
e.g. `軟體工程師的工時排行榜（由高到低）`
> 薪資工時查詢頁的 helmet 資訊

- src/components/ExperienceSearch/index.js
part of #322  
在 experiences block 每頁的第 10 篇後面塞 banner，而不是一開始就顯示在最上方。
> experiences blocks 中間塞 banner 

- src/components/TimeAndSalary/TimeAndSalaryBoard/index.js
- src/components/TimeAndSalary/TimeAndSalaryCompany/index.js
- src/components/TimeAndSalary/TimeAndSalaryJobTitle/index.js
- src/components/TimeAndSalary/common/WorkingHourBlock.js
1. 幫 Board 的職稱與公司加上連結
2. 以公司或職稱搜尋：當資料只有一筆，自動展開
1. http://localhost:3001/time-and-salary/latest
2. 造訪 http://localhost:3001/time-and-salary/company/%E4%B8%AD%E8%8F%AF%E9%9B%BB%E4%BF%A1%E8%82%A1%E4%BB%BD%E6%9C%89%E9%99%90%E5%85%AC%E5%8F%B8/work-time-dashboard 時，自動展開細節
> TimeAndSalary enhance

- .circleci/docker-compose-dev.yml
- .circleci/docker-compose-production.yml
- .circleci/docker-compose-stage.yml
- src/config/config.dev.js
- src/config/config.prod.js
- src/containers/Root.js
- webpack.config.base.js
將開發用的 GA ID 改成別的，避免測試的時候造成錯誤的資訊
`src/config/config.*.js` --> 會根據 NODE_ENV 是 production or dev 決定要用的 GA_ID
`docker-compose-*.yml` --> 這個會從 process.env.GA_ID 覆蓋 config 的決定（以 https://www-stage.goodjob.life 來說，還是希望 GA_ID 與 https://www.goodjob.life 分開）
> Seperate GA tracking ID from production online and stage/dev environment

- package.json
- src/components/ExperienceDetail/Article.js
- src/components/LaborRightsSingle/Body.js
- src/components/TimeAndSalary/TimeAndSalaryBoard/TimeAndSalaryBoard.module.css
- src/components/TimeAndSalary/TimeAndSalaryBoard/index.js
- src/components/common/GradientMask/GradientMask.module.css
- src/components/common/GradientMask/index.js
- src/components/common/PermissionBlock/BasicPermissionBlock.js
- src/components/common/PermissionBlock/LaborRightsPermissionBlock.js
- src/components/common/PermissionBlock/PermissionBlock.module.css
- src/helpers/Html.js
- yarn.lock
Close #393 
1. 加上灰階遮罩，讓使用者更容易意識到東西被遮住
2. 加上鎖頭＆明確告訴使用者沒權限
3. 文案小幅修改，避免引導使用者只想用很短的時間寫內容
單篇經驗分享：
單筆薪資工時：
搜尋薪資工時：
小教室：
分 commit 看
- 我需要更新 Packages 嗎？ yes
兩個FB帳號
> Refactor: PermissionBlock 圖示與文案& 灰階遮罩

- src/actions/experienceSearch.js
- src/components/ExperienceSearch/Filter/index.js
- src/components/ExperienceSearch/Searchbar.js
- src/components/ExperienceSearch/helper.js
- src/components/ExperienceSearch/index.js
- src/containers/ExperienceSearchPage.js
- src/reducers/experienceSearch.js
- src/selectors/experienceSearchSelector.js
將
兩個選項與 redux state 脫離
1. input/checkbox/radio 的狀態只要放在 Component 內就足夠了
2. 將事件的處理全部移到 `components/ExperienceSearch`，避免底層的 component 自己送 action
> Rewrite ExperienceSearch

- src/components/LaborRightsSingle/index.js
- src/components/common/PermissionBlock/BasicPermissionBlock.js
- src/components/common/PermissionBlock/LaborRightsPermissionBlock.js
- src/constants/hideContent.js
1. 權限機制的連結直接導到薪資工時表單頁
2. 薪資工時沒權限能看的列數提高到 8 列
3. 小教室沒權限能看的張數，應該是要 contentful （之前是用 constant 寫死，是bug）
> Refactor 權限機制

- src/components/ExperienceSearch/Pagination/Pagination.js
如果 Link 是 disabled 的狀態，那麼 `to` 就不要有值，避免 crawler follow 無效的 link
> Fix experienceSearch bug, do not show link href if disabled

- src/components/ShareExperience/CampaignTimeAndSalaryForm/index.js
- src/components/ShareExperience/utils.js
Close #480
原本`TimeAndSalary`是從`state`拿到`campaign` (如下)，在集中campaignInfo到store的時候疏忽這邊了
https://github.com/goodjoblife/GoodJobShare/blob/2ce095936f6ac7c6427252dabf2faf5ff8da66c9/src/components/ShareExperience/utils.js#L186-L190
所以解法是在`setCampaignInfoFromEntries` (如下)時一併`setState({ campaignName })`即可
https://github.com/goodjoblife/GoodJobShare/blob/2ce095936f6ac7c6427252dabf2faf5ff8da66c9/src/components/ShareExperience/CampaignTimeAndSalaryForm/index.js#L187-L193
> 修正Campaign送出表單沒有送出campaign參數

- src/components/TimeAndSalary/common/WorkingHourBlock.js
bug 的來源是 workingHourBlock ([示意圖](https://user-images.githubusercontent.com/3805975/39526800-770f1a48-4e52-11e8-8dc0-5cc215c2c228.png) ) 在未展開的狀態下，還是會 render content，裡面包含了 PermissionBlock 。這一堆 PermissionBlock 會同時間瞬間去檢查三種數字的 fetching status，全部都認為還沒 fetch，就全部都打 API 了。
我嘗試過讓 PermissionBlock 檢查 fetching status 是不是 unfetched，然後在準備要打 API 之"前"，先 dispatch action 把 fetching status 設成 fetching，想說這樣還沒打 API 之前就能先改 fetching status，就不會爆出一堆 query。
但這招沒有奏效，unfetched 還沒變成 isfetching 之前，所有的 PermissionBlock 就已經全部檢查完狀態，全部都打 API 了
所以，目前唯一解法是不要瞬間 render 大量 PermissionBlock。
瞬間 render 大量 PermissionBlock 也很不合理啦，所以就只改一行了
> hotfix: 解決大量 call API 的 bug 

- src/actions/experiences.js
- src/actions/timeAndSalary.js
- src/containers/PermissionBlock/BasicPermissionBlockContainer.js
- src/containers/PermissionBlock/LaborRightsPermissionBlockContainer.js
Close #494
當打 API 時，檢查是不是 `UNFETCHED`，並且 dispatch `FETCHING` 確保一次只有一個 query 發生
當 component 執行 `queryExperienceCountIfUnfetched` 時，
直到 `getExperiences(opt)` 前，都是非 async code (*)，所以 `dispatch(setCountData(0, fetchingStatus.FETCHING));` 可以確保下一個 query 被拒絕
(*) 目前驗證的結果是這樣
> bugfix #494, query api when unfetched

- src/apis/campaignInfoApi.js
- src/components/CampaignTimeAndSalary/index.js
- src/components/ShareExperience/CampaignTimeAndSalaryForm/index.js
Close #472 
增加 Campaign 表單頁面、查詢頁面所需的 meta information
分 commit 看
a291452 新增一個欄位放 description，因為用原本的 formIntroduction 會有 markdown 的符號有點怪，也太長
3849f25 搜尋頁小修改一下 meta 資訊
a836564 表單頁加上 meta 資訊
> [WIP] Update/add meta data for Campaign form and search page 

- src/components/ShareExperience/common/FailFeedback.js
- src/components/ShareExperience/common/SubmitArea.js
Close #500 
填寫表單如果 API 出現錯誤，把錯誤訊息顯示在 modal 上，才不會不知道到底為什麼出錯。
> fix: show error message on Modal when error happen

- src/components/ShareExperience/CampaignTimeAndSalaryForm/index.js
- src/components/ShareExperience/InterviewForm/index.js
- src/components/ShareExperience/TimeSalaryForm/index.js
- src/components/ShareExperience/WorkExperiencesForm/index.js
- src/components/ShareExperience/common/SubmitArea.js
這個 PR 想要解決 **送出表單流程** 由多點處理 程式邏輯 的問題
現象：
這是 `SubmitArea` 的 `onSubmit`，
https://github.com/goodjoblife/GoodJobShare/blob/768364a50714c2bdca0eb18b08a21f947e43074d/src/components/ShareExperience/common/SubmitArea.js#L69-L87
在 `SubmitArea` 裡面會負責處理各種 form 的 `onSubmit` (`this.props.onSubmit`) 狀態 (`p`)，並且根據狀態做 if/else 顯示 modal
會有幾個問題：
1. `p` 到底是什麼？(in this case, `null`, `Promise`)
2. `type` 有哪些？
3. 一堆跟 `SubmitArea` 不相關參數 (`type`, `campaign`, ...) 為了要產生 modal 而傳入
解法：
讓 `SubmitArea` 把 `handleFeedback` 傳入 form 的 `obSubmit` 參數，
由 form 的 `obSubmit` 去處理正確，錯誤的邏輯
```
送表單流程：
檢查欄位 --N→ 提示錯誤的 form part(在 Form 的 onSubmit)
|
Y
↓
已登入 --N→ FB登入(在 SubmitArea 的 login) --N→ 跳出失敗 (在 SubmitArea 的 onFacebookFail)
|           |
Y           |
|<----------
↓
送出表單(*1) --N→ 處理失敗(在 SubmitArea 的 obSubmit)
|
跳出處理成功(在 …
```
> Refactor: In form, do logic handle in only one function

- src/components/CampaignTimeAndSalary/CampaignTimeAndSalaryBoard/index.js
- src/components/CampaignTimeAndSalary/NotFound.js
- src/components/CampaignTimeAndSalary/index.js
- src/containers/CampaignTimeAndSalary/NotFound.js
- src/routes.js
這個 PR 處理當 campaignName 不在 campaign 活動中時，應該要
1. 顯示 404
2. 小心處理 Helmet，因為 campaignInfo 可能是 undefined (`src/components/CampaignTimeAndSalary/index.js`) (PR 前：這個 bug 導致 https://www-stage.goodjob.life/time-and-salary/campaigns/TEST 出現 500)
> Bugfix: Campaign handle 404

- src/components/common/formatter.js
In #399, 這段 code 沒有處理 type === 'day' 的情況
https://github.com/goodjoblife/GoodJobShare/pull/399/files#diff-55e3f0d5fea1a85f7f2f689f26accf1bL139
在 refactor 的過程，繼續保留原本的錯誤行為
故修正這裡
> Add type == day in salaryType formatter

- src/client.js
Close #520
修正 #520，
因為 react-router-redux 的 push action 讓 window.location 更新了，但沒有更新到 react-router 上
以下這兩種寫法為不建議寫法
`window.location.replace(xxx)`
https://github.com/goodjoblife/GoodJobShare/search?q=replace&type=Code 
這會導致產生新的頁面 request, 應該用 history.replace
`dispatch(push(xxx))`
https://github.com/goodjoblife/GoodJobShare/search?l=JavaScript&q=push&type=Code
> Use ConnectedRouter to bind redux history event to router

- src/components/TimeAndSalary/common/WorkingHourTable.js
表訂/實際工時在沒有數值的時候會顯示`undefined`，實際上經過測試上傳工作資訊時必填欄位很多都沒有做檢查，不曉得這個是否是正常的
- Front-end PR：簡易ＵＩ修正
> 修正表訂/實際工時 UI bug

- src/components/Layout/Header/index.js
這個 bug 是在追蹤 middleware 時，意外發現不尋常的錯誤
打 API 的部分應該在 `componentDidMount` 完成
> Bugfix init api in constructor

- src/components/ExperienceDetail/Article/InfoBlock.module.css
- src/components/ShareExperience/InterviewForm/InterviewInfo/InterviewResult.js
- src/components/ShareExperience/InterviewForm/formCheck.js
- src/components/ShareExperience/InterviewForm/formCheck.test.js
Close #389 
1. 錯誤訊息不只顯示「需填寫面試結果」，還加上字數限制
2. 字數限制拉到 100 字 （需搭配後端 PR： https://github.com/goodjoblife/WorkTimeSurvey-backend/pull/505 ）
- Back-end PR：https://github.com/goodjoblife/WorkTimeSurvey-backend/pull/505
輸入的地方
顯示的地方
> Fix/修復面試結果選擇 [其他] 時，輸入文字的錯誤訊息

- src/actions/auth.js
- src/components/App/Header/index.js
- src/components/App/index.js
- src/components/Me/index.js
- src/containers/App/Header/index.js
- src/containers/App/SyncAuth/index.js
- src/containers/Me/index.js
這個 PR 將 FB SDK 的狀態改變更新至 Redux 中
1. 當 SDK 讀取完成 --> 檢查登入狀態 --> 並跟後端取得登入憑證
2. 當 FB 登入 --> 取得使用者帳戶名稱
從 `src/containers/App/SyncAuth/index.js` 的 componentDidMount, componentDidUpdate 來看
備註：
目前登入的狀態會透過 FB SDK 幫忙，之後等 token 被放進 localStorage，就不需要每次都等待 FB SDK
> Sync Auth in one place

- src/components/ExperienceSearch/Searchbar.js
這個 PR 修正 getDerivedStateFromProps 會一直重設 state，導致表單無法輸入值 (Searchbar)
> Fix: getDerivedStateFromProps reset state every props values change

- src/components/ExperienceDetail/LikeZone/LikeZone.js
- src/components/ExperienceDetail/LikeZone/LikeZone.module.css
1. 修了LikeZone hover hitzone 過大的問題
2. ThumbsUp wrapper 改用button ，css 也換成相對應會符合原spec 的寫法
> Decrease the hover hitzone

- src/components/ExperienceDetail/Article/SectionBlock.module.css
像這篇：
https://www.goodjob.life/experiences/5c8378e82d9f5a00111dc220
有網址太長的時候會造成跑版，這個 PR 把 css style 加上 `word-break: break-word`，可以解決這個問題。
> hotfix: use break-word to prevent layout bug

- src/server.js
這個問題解決當 SSR 的時候，中文字的網址沒有 decode
> Fix SSR chinse charactor encoding

- src/components/App/Footer/index.js
- src/components/App/Header/SiteMenu.js
- src/components/CampaignTimeAndSalary/CampaignTimeAndSalaryBoard/index.js
- src/components/ShareExperience/TimeSalaryForm/index.js
- src/components/TimeAndSalary/NotFound.js
- src/components/TimeAndSalary/TimeAndSalaryBoard/index.js
- src/components/TimeAndSalary/index.js
- src/routes.js
#622
> 進到薪資工時頁面的 route 是 /salary-work-times
1. 改為`/salary-work-times/latest`
2. 舊的`/time-and-salary`開頭的都導向至`/salary-work-times/latest`
3. 移除TimeAndSalaryBoard的Select元件
> 將薪資工時route改為salary-work-times

- src/components/TimeAndSalary/SearchScreen/SearchScreen.js
- src/components/TimeAndSalary/SearchScreen/WorkingHourBlock.js
Close #632
#622 
用`Link`取代`history.push`
> SalaryWorkTimes: 使用Link取代history.push

- src/components/Company/SalaryWorkTimeScreen.js
- src/components/Company/helmet.js
- src/components/JobTitle/SalaryWorkTimeScreen.js
- src/components/JobTitle/helmet.js
- src/components/TimeAndSalary/SearchScreen/SearchScreen.js
- src/components/TimeAndSalary/SearchScreen/helmet.js
- src/components/TimeAndSalary/TimeAndSalaryBoard/helmet.js
- src/components/TimeAndSalary/TimeAndSalaryBoard/index.js
- src/constants/helmetData.js
- src/graphql/timeAndSalary.js
Close https://github.com/goodjoblife/GoodJobShare/issues/600
更新薪資工時列表頁、薪資工時查詢結果頁、單一公司薪資工時頁、單一職業薪資工時頁 的 meta description
1. 最重要的 meta description 是 title & description ，title 的原則是盡可能抓到使用者在搜尋引擎搜尋的字詞，而 description 的原則是儘可能把使用者想要的資訊摘錄在一定的字數內。
因此，幾乎所有原本的 OOO 薪資、加班狀況、工時的字眼都直接改成「OOO薪水」，這個詞在 google trend 上還是最高的。而 description 則是摘要一些重要的統計資訊。
2. 分頁要放標題，內容不同確有一樣標題對 SEO 來說很傷
by commit
> Update/helmet for SalaryWorkTimes pages

- src/components/TimeAndSalary/common/formatter.js
Close #622 
解決後端回 null 時，表訂工時、實際工時會出現 null 的問題
更新後的檢查的方式會讓 null / undefined / 0 都顯示為 `-`  
0 的部分沒什麼參考價值，顯示 `-` 覺得 ok
> fix: fix working hour formatter

- src/components/App/Header/index.js
原本在非登入並且需要顯示進度條的情況下，那條會是沒有連結的，應當為原本的規則。
未來還是應該把這段稍微重構一下，但先上這個補救功能，把同一個邏輯寫在不同地方判斷不同事情
* 以非登入狀態下看進度條的連結
> 上方通知連結為何的Rule

- src/actions/auth.js
前端打 FB login SDK 多要 email 權限
- Back-end PR：https://github.com/goodjoblife/WorkTimeSurvey-backend/pull/558
[facebook 文件](https://developers.facebook.com/docs/facebook-login/web/permissions) 最下方有範例
> Refactor: request user email field in FB SDK

- src/components/ShareExperience/CampaignTimeAndSalaryForm/index.js
- src/components/ShareExperience/TimeSalaryForm/TimeSalaryForm.module.css
- src/components/ShareExperience/TimeSalaryForm/index.js
> Refactor: remove email field from SalaryWorkTime form

- src/components/ExperienceDetail/Article/index.js
- src/components/ExperienceDetail/Heading/index.js
- src/components/ExperienceDetail/index.js
- src/components/TimeAndSalary/index.js
目前的經驗單篇有許多warnings，沒解掉的時候開發有點干擾，索性先解掉。
1. `InsepectReportModal`因為放在conditional rendered component裡面，所以因為async actions而造成no-op
- **解法**：移到非conditional rendered的parent component
2. for loop key prop
- **解法**：把key放對地方
3. `<Heading />`的`children` isRequired卻傳進`null`
- **解法**：當null的時候就傳空字串
另外最新薪資工時(`TimeAndSalary`)也有props warning，因為是出於之前把campaign沒拿乾淨而出現的warning，把propTypes拿掉即可。
- Before
- After
另外附上TimeAndSalary的warning：
> 解經驗單篇warnings

- src/actions/auth.js
- src/containers/App/SyncAuth/index.js
- src/reducers/auth.js
解決登入邏輯判定錯誤，造成無限迴圈的重新登入檢查
1. 在網頁開始時，與後端同步本地端儲存的登入狀態（`src/containers/App/SyncAuth/index.js`），移除不必要的檢查
2. `getMeInfo` (`src/actions/auth.js`) 會拋出錯誤，讓 loginWithToken 處理（無限迴圈的一個原因）
1. 移除 `SET_TOKEN`，麻煩 @WendellLiu 確認
2. 把登入流程具體寫出（見註解）
這個 PR 也是跟著 #668 而發現的
> Fix auth change then recursive trigger auth check

- src/components/common/PermissionBlock/CallToLoginShareButton.js
close #680 
這個 PR 修正掉 reload 的部分，由於 reload 的關係，有可能導致 store 沒有及時 sync 至 localStorage
major:
1. 麻煩 @barry800414 確認為什麼當初要用 window.location.reload，避免這個 fix 造成新的 bug
minor:
1. 麻煩 @WendellLiu 如果有空確認一下 store 至 localStorage 的時機，這個不影響 bug 修復，事實上本來就不能依賴 localStroage 的儲存會是 non-async
> Fix #680, avoid force reload

- src/components/ExperienceDetail/index.js
經驗單篇在SSR時因為沒有token，會render出沒有登入的狀態
但若使用者已經登入而且已經對該篇經驗按讚
`liked`的狀態會抓不到，此時也無法取消讚
解法是`componentDidMount`強制重打API使store的資料是登入狀態的
> force experience refetch

- src/components/common/Modal.js
Modal的close button需要stopPropagation
因為現在的Modal已經可以點背景就關閉了
而close button也在背景上，所以若沒stopPropagation就會呼叫close兩次
這在AboutThisJobModal會有問題～
> Modal的close button stop propagation

- src/components/ShareExperience/InterviewForm/formCheck.js
- src/components/ShareExperience/InterviewForm/formCheck.test.js
- src/components/ShareExperience/InterviewStepsForm/formCheck.js
- src/components/ShareExperience/InterviewStepsForm/formCheck.test.js
- src/components/ShareExperience/WorkExperiencesForm/formCheck.js
- src/components/ShareExperience/WorkExperiencesForm/formCheck.test.js
- src/components/ShareExperience/common/Title.js
有使用者反映標題長度太短，公司名稱太長時，就會導致錯誤訊息
因此把經驗分享標題的字數拉到 50 個字
> refactor: increase experience.title length to 50 chars

- src/components/TimeAndSalary/common/formatter.js
薪資工時頁面，表格內容中的「職稱」連結，會因為取值方式錯誤，解析出錯誤的link。
**before**
`https://www.goodjob.life/salary-work-times/latest`
**after**
> [hotfix] Time and Salary Board Link of Job Title

- src/actions/experienceDetail.js
- src/apis/experiencesApi.js
- src/components/ExperienceDetail/index.js
- src/reducers/experienceDetail.js
- src/utils/errors/graphqlError.js
- src/utils/errors/index.js
- src/utils/errors/uiNotFoundError.js
- src/utils/graphqlClient.js
整理了常見的 Error
1. HttpError, GraphqlError 是做 http query, graphql Query 時產生的 Error，可能是有辦法處理的，也可能是不預期的
2. UiXXXError 是已知可以呈現在 UI 的錯誤
錯誤處理流程如下：
```
HttpError, GraphqlError ==> 如果是已知的錯誤 ==> 轉為 Action, 並停止拋出
==> 如果是無法處理的錯誤 ==> 拋出，讓 Sentry 可以接到
```
> Handle erros on ExperienceDetail page

- src/components/ShareExperience/InterviewForm/index.js
- src/components/ShareExperience/InterviewStepsForm/index.js
- src/components/ShareExperience/WorkExperiencesForm/index.js
- src/components/ShareExperience/utils.js
Close #730   
儲存草稿時，連帶idCounter的值也存起來
重新整理時，恢復idCounter的狀態(idCount值比儲存前+1，但是可以正確運作)
因為相關邏輯在`InterviewStepsForm`、`InterviewForm` (目前deprecated)、`WorkExperiencesForm`都有，就一併改
但WorkExperiencesForm測試時發現有其他問題(儲存草稿的bug)，還需要另外研究
不過想說之後會改版，所以我就暫時不深究
目前只確定InterviewStepsForm已經修正
> 解決填寫表單appendBlock的覆寫問題

- src/components/common/PermissionBlock/BasicPermissionBlock.js
- src/components/common/PermissionBlock/LaborRightsPermissionBlock.js
- src/constants/dataProgress.js
> hotfix: 權限區塊導流到面試經驗表單

- src/components/ExperienceDetail/Heading/index.js
- src/components/ExperienceDetail/experienceSelector.js
- src/components/ExperienceDetail/index.js
- src/graphql/experience.js
part of #637 
優化經驗分享頁的 SEO：
1. meta title 改為 `[公司] [職稱] [種類] [時間]`
2. meta description 改為各種固定欄位＋sections 所有內容串起來後，再做 slice 取前面一段。  
3. 文章的標題改為 `[種類] [公司] [職稱]` 
為什麼要這麼做？ 請見背景知識
根據 google 官方 [SEO guide](https://support.google.com/webmasters/answer/7451184?hl=en#understand_your_content)，我們可以知道：
1. 不同頁面的 title 要盡可能不一樣
所以我把職稱和時間都加進去，避免原本公司一樣的話，title 就會一樣。
1. 不同頁面的 meta description 要盡可能不一樣
2. 對使用者決定是否點進去看有幫助
3. 避免將所有內容複製貼上到 description（網路上有不少文章建議長度 130 字元～ 160 字元）
所以我嘗試把一些固定、且使用者可能會想知道的欄位放進去，並且把所有 sections 考慮進去。最後避免內容過長，僅擷取前面 160 字元。
1. by commit 
2. 很多 Ramda 的用法可能還沒那麼成熟，請鞭小力點。先求正確無誤。
> Feat: improve experience detail SEO

- src/components/CompanyAndJobTitle/TimeAndSalary/TimeAndSalary.js
`salaryWorkTimes`和`salaryWorkTimeStatistics`被設為`isRequired`
在`UNFETCHED`時就會undefined而噴warning
需要修正
修正前：
> [公司/職稱頁面] 修正PropTypes

- src/components/CompanyAndJobTitle/TimeAndSalary/TimeAndSalary.js
- src/components/CompanyAndJobTitle/TimeAndSalary/TimeAndSalary.module.css
修改薪時頁面的空資料狀態，與其他頁面一致
- 其他頁面
- 薪時頁面(原)
- 薪時頁面(修正後)
> [公司/職稱頁面] 薪時頁面Empty State

- src/components/TimeAndSalary/SearchScreen/SearchScreen.js
- src/components/TimeAndSalary/common/formatter.js
把幾個需要的連接從/salary-and-times 換成/overview
1. http://localhost:3000/salary-work-times/latest 公司、職稱連結
2. WorkingHourTable 公司、職稱連結
3. 搜尋到一筆資料的結果導流連結
4. 搜尋到多筆資料後，點擊可能結果連結
1. 搜尋到一筆的結果
2. 搜尋到多筆，點擊其中一項結果
3. latest 頁面
4. 任何working hour table
> [公司/職稱頁面] 增強搜尋結果體驗

- src/components/CompanyAndJobTitle/CompanyAndJobTitleWrapper.js
- src/components/CompanyAndJobTitle/CompanyAndJobTitleWrapper.module.css
- src/components/CompanyAndJobTitle/InterviewExperiences/InterviewExperiences.js
- src/components/CompanyAndJobTitle/Overview/Overview.js
- src/components/CompanyAndJobTitle/Overview/Overview.module.css
- src/components/CompanyAndJobTitle/TimeAndSalary/TimeAndSalary.js
- src/components/CompanyAndJobTitle/TimeAndSalary/TimeAndSalary.module.css
- src/components/CompanyAndJobTitle/WorkExperiences/WorkExperiences.js
- src/components/common/facebook/FacebookWrapper.js
把`FanPage`放在`CompanyAndJobTitleWrapper`底下
並且把不同Tab的Component Wrapper統一成`<Section>...</Section>`
Before:
After:
> [公司職稱頁面] 統一Tab風格

- src/components/CompanyAndJobTitle/InterviewExperiences/ExperienceEntry.js
- src/components/CompanyAndJobTitle/WorkExperiences/ExperienceEntry.js
#759 
經驗的「返回列表」都是回到職場經驗，而非真的上一頁
要修正成真正的上一頁
Before
After
> [公司職稱頁面] 修正經驗單篇的返回列表按鈕

- src/components/Company/CompanyPageProvider.js
- src/components/JobTitle/JobTitlePageProvider.js
- src/routes.js
Close #763 
這個 PR 暫時解決公司職稱頁面沒有 SSR 的問題
1) `routes.js` 用 component 而不是 render，
在 SSR 的處理中，如果有 static property fetchData，就會運作
如上圖，可以看到 window.__data 是由 server side 填入，window.__data 會作為一開始的 initial state 給 redux store
如上圖，也可以看到 html 原始碼是有資料的（eg: 323 筆）
代表 SSR Render 成功
> 解決公司職稱頁面沒有 SSR 的問題

- src/actions/viewLog.js
- src/apis/viewLogApi.js
- src/components/ExperienceDetail/ViewLog.js
- src/components/ExperienceDetail/index.js
- src/containers/ExperienceDetail/ViewLog.js
- src/graphql/viewLog.js
> feat: tracking viewing experience detail log

- src/components/Root.js
- src/config/index.js
- src/utils/gtm.js
[google optimize](https://optimize.google.com/optimize/home/) 是一個專門做 A/B testing 的工具，可以讓使用者不用動程式碼就做出 A/B 兩組 UI (註1)，並且自動追蹤目標數據（例如：面試經驗表單轉換率），去判定 A/B 兩組差異是否顯著。
我已經用 google tag manager 在 local & production 上面都安裝了 google optimize SDK，所以不用再程式碼裡面另外裝。
但因為 React 是個 single page application ，如果使用 google optimize 預設的實驗觸發機制（page load），將無法正常運作。（因為 react 只有在第一頁才有真正的 page load）。因此必須在每一次網址改變時，推送事件到 window.dataLayer 去觸發 google optimize 檢查是否觸發實驗。這個 PR 就是做這件事。
詳見官方文件：https://support.google.com/optimize/answer/7008840?hl=en 有個章節是 `Firing activation in a single page application` ，簡而言之是我們要自己送 event 到 dataLayer 觸發 google optimize。
附註：
1. 太複雜的還是要工程師去動程式碼才能達到。但如果只是隱藏區塊、調整顏色、字體等等，可以用 google optimize 編輯器直接做到。
如果成功跑起實驗，幾天後會有類似這樣的報表
建議到 https://optimize.google.com/optimize/home/ 用 goodjob-local 的容器試玩一下！ …
> Feat: trigger google optimize at every page

- src/components/Company/CompanyPageProvider.js
- src/components/CompanyAndJobTitle/InterviewExperiences/ExperienceEntry.js
- src/components/CompanyAndJobTitle/InterviewExperiences/InterviewExperiences.js
- src/components/CompanyAndJobTitle/InterviewExperiences/InterviewExperiences.module.css
- src/components/CompanyAndJobTitle/InterviewExperiences/helper.js
- src/components/CompanyAndJobTitle/InterviewExperiences/index.js
- src/components/CompanyAndJobTitle/Overview/Overview.js
- src/components/CompanyAndJobTitle/Overview/index.js
- src/components/CompanyAndJobTitle/WorkExperiences/ExperienceEntry.js
- src/components/CompanyAndJobTitle/WorkExperiences/WorkExperiences.js
- src/components/CompanyAndJobTitle/WorkExperiences/WorkExperiences.module.css
- src/components/CompanyAndJobTitle/WorkExperiences/helper.js
- src/components/CompanyAndJobTitle/WorkExperiences/index.js
- src/components/ExperienceDetail/index.js
- src/components/JobTitle/JobTitlePageProvider.js
- src/components/common/formatter.js
- src/components/common/icons/index.js
- src/components/common/permission-context/PermissionContext.js
- src/components/common/permission-context/PermissionContextProvider.js
- src/components/common/permission-context/withPermission.js
Close #772    
總覽 / 面試 / 工作 頁面的card修改UI，不同權限會有不同顯示
以下為公司/職稱有card的頁面：
http://localhost:3000/job-titles/軟體工程師/overview
http://localhost:3000/job-titles/軟體工程師/work-experiences
http://localhost:3000/job-titles/軟體工程師/interview-experiences
http://localhost:3000/companies/全家便利商店股份有限公司/overview
http://localhost:3000/companies/全家便利商店股份有限公司/work-experiences
http://localhost:3000/companies/全家便利商店股份有限公司/interview-experiences
**未登入**
**登入&沒權限**
**登入&有權限**
**登入&登出**
> [公司/職稱頁面] 公司、職稱頁面的經驗結果卡片調整 

- src/components/CompanyAndJobTitle/Overview/SummaryBlock.js
- src/components/CompanyAndJobTitle/Overview/SummaryBlock.module.css
- src/components/LandingPage/SummarySection.js
- src/components/LandingPage/SummarySection.module.css
- src/components/LandingPage/index.js
- src/components/common/Carousel.js
- src/components/common/Carousel.module.css
- src/components/common/Charts/CompanyDistributionChart.js
- src/components/common/Charts/JobTitleDistrubitionChart.js
原本以為圖表的寬度無解了，幸好發現 ResponsiveContainer 
所以我讓兩種圖表都包 responsive container ，根據外面寬度去 render 
首頁 > 1024px
首頁 < 1024px
公司職稱頁 > 767px
公司職稱頁 < 767px
> Refactor: chart RWD style

- src/components/common/Carousel.js
這個 PR 解決了底下的 Warning
這個 warning 是因為當 carousel 的 child 不是 active 時，style 為 `display: none`，rechart 取得的寬高都是0
> Carousel will render null when child is not active (selected)

- src/utils/errors/graphqlError.js
- src/utils/errors/httpError.js
- src/utils/errors/uiNotFoundError.js
Close #823 
only use Error.captureStackTrace if it exists
MDN 上的 example 有範例：https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Error#Examples
> hotfix: only use Error.captureStackTrace if it exists

- src/actions/company.js
- src/actions/experienceDetail.js
- src/actions/experienceSearch.js
- src/actions/jobTitle.js
Close #819   
遇到後端拋出的Graphql錯誤，至少讓頁面SSR正常render (不要全白)。
render的頁面：
Prerequisite:
新增一筆經驗，並填入極大數字的薪資 (e.g. `10000000000000000000000`)並送出表單
> [公司薪資API] 容許Graphql錯誤

- src/components/ShareExperience/CampaignTimeAndSalaryForm/index.js
- src/components/ShareExperience/TimeSalaryForm/index.js
Close https://github.com/goodjoblife/WorkTimeSurvey-backend/issues/653
前端這邊有剩幾筆可以留的訊息，把它換掉
- Back-end PR：https://github.com/goodjoblife/WorkTimeSurvey-backend/pull/687
> Refactor：salary work time quota

- src/components/common/FormBuilder/QuestionBuilder/TextArea.js
- src/components/common/FormBuilder/QuestionBuilder/TextArea.module.css
#846  
edit TextArea css
after 
before
下拉選單會把整個題目也一起往下拉
有點奇怪 ～～ 
應該scroll那格框框的內容而已？
> Form textArea css 

- src/components/CompanyAndJobTitle/TabLinkGroup.module.css
- src/components/CompanyAndJobTitle/index.js
- src/components/CompanyAndJobTitle/styles.module.css
- src/routes.js
公司/職業頁面的，因為埋設廣告的需求，調整了排版，右邊固定是廣告版位
- 把原本以 TimeAndSalary component 作為 container 的方法換掉，直接新增新的 component 
by commit
> Feat: side ads for company/job-title pages

- src/components/common/FormBuilder/QuestionBuilder/Radio.js
- src/components/common/FormBuilder/QuestionBuilder/Rating.js
- src/components/common/FormBuilder/useDebouncedConfirm.js
#846 
修復debounce問題
重現Bug步驟：
1. DemoForm 初次填寫 Radio 或 Rating
2. 作答但沒有自動跳下一題
原因：因為 `onConfirm` 為
```js
page => {
setWarningShown(true);
if (!warning) { // <-- 有warning時會阻擋
setPage(page);
}
}
```
而 `onConfirm` 的 debounce 寫在
```js
onClick={() => {
onChange(..)
setTimeout(onConfirm, 300)
}}
```
在未填寫的時候，其實是有 `warning` 的只是沒顯示出來
原本預期填寫時觸發 `onChange` 然後 `warning` 就會消失(因為已填寫)
然後此時觸發 `onConfirm` 就會到下一題
但實際發生的是， `onConfirm` 與 `onChange` 是同一次render的
`onConfirm` 的當下是有 `warning` 的，所以不會跳題
解決方法是，讓 `onConfirm` 在 `onChange` 完的下一次 render 才觸發
該次 render 才會是沒有 `warning` 的狀態，才會觸發跳下一題的動作
> [新版表單] 修復Debounce

- src/components/common/PermissionBlock/BasicPermissionBlock.js
- src/components/common/withExperimentParameters.js
目的同 #881 
感謝 @peteranny 的 comment ，讓我想到這件事可以不用這麼複雜
主要就是在監聽之前，再把現在 target element 的 attributes 拿下來一次
這樣就不會有 useState ~ useEffect 這段時間的改變沒監聽到的問題了
也不用特別改成 class component
> Refactor: withExperimentParameters

- src/components/common/withExperimentParameters.js
- src/utils/gtm.js
- src/utils/sentryUtil.js
Close #  
用 `if(document)` or `if(window)` 這樣的檢查，在 server-side 其實還是會錯（但不知道為什麼有時候才會發生，有時候卻不會），因此改成用 typeof 檢查
> Hotfix: check window and document before using to prevent SSR error

- src/components/ExperienceDetail/Seo.js
Since JSON.stringify doesn't escape the char like `<` and `>`, the raw html in script is not safe.
`JSON.stringify(data)` must be escaped, I use the library in https://github.com/goodjoblife/GoodJobShare/blob/0949ae917d3a55a6371bad7b7b1fee7759e61b78/src/helpers/Html.js#L88
> Escape unsafe js object

- src/client.js
- src/components/App/index.js
- src/components/LandingPage/CallToActionBlock.js
- src/components/ShareExperience/InterviewForm/TypeForm.js
- src/components/common/PermissionBlock/BasicPermissionBlock.js
- src/components/common/ShareExpSection/index.js
- src/constants/dataProgress.js
原本寫pathname不改變就不置頂
但考量到query改變仍有置頂的可能 (?p=2)
因此把某些只是為了內部使用(所以不用置頂)的變數從query搬移到state
> Fix: 當只有state改變時捲軸不置頂

- src/components/ExperienceDetail/Article/ArticleInfo.js
意外發現一個 bug，experience_in_year === 0 的時候，職場經驗單篇會有顯示上的問題，詳見 screenshot，此 PR 修正之。
修正前：
修正後：
> hotfix: experience_in_year bug

- src/components/ShareExperience/InterviewForm/TypeForm/index.js
1. 修正送出成功後的文案（移除 48 小時）
2. 送出成功後，重新整理頁面，讓原本鎖定的頁面可以被解鎖
> Fix: wording and location.reload 

- src/components/ExperienceDetail/index.js
- src/components/common/button/PrivateMessageButton.js
- src/constants/gaConstants.js
- src/hooks/experiments/index.js
- src/hooks/experiments/usePrivateMessageButtonText.js
雖然點擊私訊原作者的人數不多，但動機都很強，3x 個人裡面有 14 個填寫問卷
決定試試看不同文案，是否可以增加誘因
> Feat: 測試私訊原作者按鈕文案

- src/components/ShareExperience/common/TypeFormFooter.module.css
- src/components/ShareExperience/common/TypeFormHeader.module.css
- src/components/common/FormBuilder/FormBuilder.module.css
- src/components/common/FormBuilder/ProgressBlock.module.css
#912
360px 好像還是會蓋掉
所以改成 350px 看看
350px
input 有縮放 
360px
但 360px 好像就不會動
> RWD2 Verson1

- src/components/ShareExperience/InterviewForm/TypeForm/index.js
面試經驗一頁一題式，送到後端的文章 title 都預設 `面試經驗分享`
但這個 title 其實還有用到，主要是職場經驗列表＆我的資料管理頁面都還有在用
此 PR 修復之
應該是不用測
> Hotfix: 面試經驗一頁一題式，送到後端的文章標題

- src/components/ExperienceDetail/ChartsZone/index.js
- src/components/ExperienceDetail/ExperienceDetail.module.css
- src/components/ExperienceDetail/index.js
- src/components/LandingPage/SummarySection.module.css
- src/components/common/Charts/JobTitleDistrubitionChart.js
Close #  
1. 職場經驗單篇中的薪資圖表區塊，可能會有沒資料的狀況，會間接造成畫面上的錯誤（會整一個塊白色）。因此先圖表的部分，會先檢查再決定是否 render，如果沒資料就不 render。
2. 圖表有可能出現只有一張圖的狀況，因此調整排版，讓只有一張圖的時候，圖表會在中間。
3. 微調整個文章區塊的寬度，並讓右邊的廣告 sticky
> hotfix: 修附圖表 render 錯誤、調整職場經驗單篇樣式

- src/actions/permission.js
- src/components/common/PermissionBlock/BasicPermissionBlock.js
- src/components/common/PermissionBlock/PermissionBlock.module.css
- src/components/common/PermissionBlock/components/index.js
- src/hooks/useHandleUnlockData.js
- src/reducers/permission.js
Close #  
- 把解鎖的邏輯完成，先打 API 解鎖。然後打 API 更新點數、解鎖的資料。
- 把上述邏輯拉出來變成 hook ，之後薪資工時那邊好重複用
- 修 Loader props 小 bug 
- 用戶登出的時候，把 permission redux store 重置，這樣才會再拿一次點數、解鎖的資料。
- Back-end PR：feat/permission
> Feat: 解鎖邏輯完成＋共用

- package.json
- src/components/App/Header/index.js
- src/reducers/auth.js
- src/reducers/index.js
- src/selectors/authSelector.js
- yarn.lock
Close #  
為了接下來的redirect 功能做點準備，該功能會有些資訊需要存進local storage 。由於redux-persist 我之前在設定時會涉入immutable transform ，想說既然新的不會再使用immutable 了，在redux persist 這層就開始斷開，所以把既有的會被persist 的"auth" 開始斷開immutable 
- Back-end PR：
脈絡是從 `src/reducers/index.js` 開始拿掉redux-persist config 中的transformer，一路到相對應的auth store 的reducer, selector 都de-immutable
> Get rid of immutable on persist layer

- src/components/ShareExperience/InterviewForm/TypeForm/index.js
- src/components/ShareExperience/common/TypeFormFooter.js
Close #1030 
- fix #1030 ，讓面試經驗表單 footer 拿 backend 回傳的資料數量
> Fix: 面試經驗表單 footer 資料數量錯誤

- src/components/ToastNotification/ToastNotification.module.css
- src/components/common/PopoverToggle/Popover.module.css
Close #1086 
原本的 Toast container 不可見，但有預設 100% 寬度，所以會擋住 dropdown，
現在修正寬度為0。
https://user-images.githubusercontent.com/7566586/233375480-e0ad7cf7-cb14-4885-886a-b55d46416e59.mov
- 開啟 nav dropdown 無異狀
- 手動調用 `createToastLocationState` 觀察 toast 無異狀
> 修正 Toast 擋住元件的問題

- src/apis/payment.js
- src/components/Buy/PaymentSection/useForm.js
- src/components/common/icons/CloseNoCircle.js
- src/graphql/payment.js
Close #1066
後端回傳錯誤訊息時，切換到錯誤訊息頁面
- 後端 PR - https://github.com/goodjoblife/WorkTimeSurvey-backend/pull/839
http://localhost:3000/buy
輸入TapPay提供的[錯誤card number](https://docs.tappaysdk.com/tutorial/zh/reference.html#what-is-it234)，應該要能看到切換至錯誤頁面
> [付款頁面] 後端回傳錯誤時切換到錯誤訊息頁面

- src/components/ToastNotification/Notification.module.css
- src/components/ToastNotification/ToastNotification.module.css
Close #1086  
原本的 toast container 寬100%會擋住底下的元件
此PR修正 toast container 只會照 toast 寬。
```diff
diff --git a/src/components/LandingPage/index.js b/src/components/LandingPage/index.js
index cf4feec3..6a10fac5 100644
--- a/src/components/LandingPage/index.js
+++ b/src/components/LandingPage/index.js
@@ -1,4 +1,4 @@
-import React from 'react';
+import React, { useEffect } from 'react';
import PropTypes from 'prop-types';
import { Link } from 'react-router-dom';
import ImmutablePropTypes from 'react-immutable-proptypes';
@@ -15,6 +15,7 @@ import StaticHelmet from 'common/StaticHelmet';
import CallToActionBlock from './CallToActionBlock';
import SummarySection from './SummarySection';
import { isUnfetched } from '../../constants/status';
+import usePushToast from …
```
> Fix toast css

- src/components/PlanPage/index.js
Close #  
因為新增給早期使用者的 subscriptionPlan，UI 上顯示會多一個，這邊把它過濾掉
old:
new:
> fix: displayed subscriptionPlan

- src/components/Buy/SubscriptionsSection/SubscriptionPlan.js
- src/components/Buy/SubscriptionsSection/SubscriptionPlanCollection.js
- src/components/Buy/SubscriptionsSection/SubscriptionsSection.module.css
- src/components/PlanPage/PlanCard.js
- src/components/PlanPage/PlanCard.module.css
- src/constants/subscription.js
原本付款頁面的卡片使用了 flex 延伸了寬度。
這個 PR 將付款頁面的卡片，以我的方案頁面的 PlanCard 取代，除了不會有奇怪的寬度之外，也可以統一復用元件。
|Before|After|
|-|-|
|![Screenshot 2023-05-17 at 8 44 52 PM](https://github.com/goodjoblife/GoodJobShare/assets/7566586/ee869f8f-bcf4-418c-8e25-2eb3ff690437)|![Screenshot 2023-05-17 at 11 15 06 PM](https://github.com/goodjoblife/GoodJobShare/assets/7566586/52a6d437-2274-47e1-a485-02a4e96cf96e)|
> [付款頁面] 使用現有元件

- src/utils/errors/graphqlError.js
#1119
~~這個PR在後端回傳422時顯示toast~~
~~只做面試經驗的部分~~
~~至於工作經驗，因為尚未 migrate to hooks 所以需要另開PR做~~
更新：修正為只從錯誤訊息移除 Graphql 詞綴
需要重現「留過多資料」的情境 (*需要容易測試的方法*)
在 http://localhost:3000/share 面試經驗送出資料時應失敗，並見到 toast
> [面試經驗表單] 錯誤訊息移除Graphql詞綴

- src/components/BuyResultPage/PaymentResult/InProgress.js
- src/components/BuyResultPage/PaymentResult/PaymentResult.module.css
更加提醒使用者，在訂單確認頁，不要直接離開。減少 paymentRecord 卡在 pending authorization 的情況
原本：
修改後：
> fix: 訂單確認頁面文字 highlight

- src/actions/experience.js
- src/apis/experiencesApi.js
- src/components/ExperienceDetail/MoreExperiencesBlock/index.js
- src/components/ExperienceDetail/index.js
- src/config/index.js
- src/graphql/experience.js
- src/reducers/experience.js
- src/reducers/index.js
- src/selectors/experienceSelector.js
Close #1157  
將單篇 Experence 頁面 更多相關公司與職缺的面試及工作心得 部分改寫
達到：
(1) 增加 page load speed
(2) 減低後端 api 負擔
(3) 減少網路流量
原本會透過 graphql 拿到所有的資料，並排序後選擇前 5 顯示，造成大量資料擷取
所以改成分頁式的拿資料，需要時再拿
SSR 也只需要拿前5筆就足夠
預期行為不變
> refactor: import experience page speed

- src/server.js
ref: https://expressjs.com/en/api.html#express.static
since razzle build static files are immutable, add maxAge header to cache them
also, https://developers.cloudflare.com/cache/concepts/default-cache-behavior/ cloudflare suggest how static file will be cached
> refactor: send maxAge > 0

- src/components/ExperienceDetail/Seo.js
- src/components/common/BreadCrumb/index.js
- src/components/common/Seo/SeoStructure.js
Close #1165 #1178 #1179 
新增麵包屑structure data
~~新增author.url到Article structure data~~
檢查經驗頁面的html是否有structure data
http://localhost:3000/experiences/5b17d823489c0d000fc30534
將經驗頁面的原始碼放進[檢測工具](https://search.google.com/test/rich-results)並確認通過：
其中「文章」的「非重大問題」為缺漏 image，但我們文章確實沒有圖片。
> [經驗頁面] 新增麵包屑 structure data

- src/components/common/CallToAction/CallToActionFolder.js
- src/components/common/ShareExpSection/index.js
- src/constants/dataProgress.js
- src/hooks/experiments/useShareLink.js
Close #
以目前來說，"薪水" 關鍵字吸引到的流量比面試還多，因此表單引導改成 50% 薪水，50% 面試
> feat: change to 50% salary & 50% interview

- src/components/ShareExperience/questionCreators.js
- src/components/ShareExperience/utils.js
- src/components/common/FormBuilder/QuestionBuilder/Checkbox/Checkbox.js
- src/components/common/FormBuilder/QuestionBuilder/Checkbox/CheckboxElse.js
- src/components/common/FormBuilder/QuestionBuilder/Checkbox/Radio.js
- src/components/common/FormBuilder/QuestionBuilder/Checkbox/RadioElse.js
- src/components/common/FormBuilder/QuestionBuilder/Date.js
- src/components/common/FormBuilder/QuestionBuilder/File.js
- src/components/common/FormBuilder/QuestionBuilder/Rating.js
- src/components/common/FormBuilder/QuestionBuilder/SelectText.js
- src/components/common/FormBuilder/QuestionBuilder/Text.js
- src/components/common/FormBuilder/QuestionBuilder/TextArea.js
- src/components/common/FormBuilder/QuestionBuilder/TextList.js
- src/components/common/FormBuilder/QuestionBuilder/index.js
- src/components/common/FormBuilder/index.js
#1195
原始的面試表單在驗證時分兩個步驟：
1. 用 `validator` 驗證輸入是否合法 (true/false)
2. 若否，用 `warning` 產生警告標示
但邏輯上，應該可以直接合併兩者，化簡成一個函式：當輸入有誤時就回傳警告文字，若合法則回傳null。
此重構會使表單更容易定義。
```mermaid
flowchart LR
A[value] --> B{validator} -->|true| C[valid] -.->|null\nwarning| F
B --> |false| E[invalid] --> D{warning} -.->|non-null\nwarning| F[Element]
```
```mermaid
flowchart LR
A[value] --> B{warning} -->|null| C[valid] -.->|null\nwarning| F
B --> |non-null| E[invalid] -.->|non-null\nwarning| F[Element]
```
> [面試經驗] 化簡驗證邏輯

- src/components/Company/CompanyPageProvider.js
- src/components/JobTitle/JobTitlePageProvider.js
Close #1210
修正 `/companies/:company/overview` 的重新導向 code
production:
```
% curl -i "https://www.goodjob.life/companies/Goodjob"
HTTP/2 302
location: /companies/Goodjob/overview
```
before PR:
```
% curl -i "http://localhost:3000/companies/Goodjob"
HTTP/1.1 302 Found
Location: /companies/Goodjob/overview
```
after PR
```
% curl -i "http://localhost:3000/companies/Goodjob"
HTTP/1.1 301 Moved Permanently
Location: /companies/Goodjob/overview
```
> feature: redirect company, job_title overview url with status code 301

- src/components/ShareExperience/questionCreators.js
Close #  
發現要改成拿 API 資料會比較複雜，先更新寫死的數字
> hotfix: 薪資、面試表單最後一題資料數量錯誤（暫時解）

- src/components/common/ShareExpSection/index.js
- src/hooks/experiments/useShareLink.js
Close #  
1. 結束 Salary form A/B testing，一頁一題式＆有 progress bar 的結果最好（觀察三天、五天結果都是一樣顯著），因此都導流到這個 variant
2. 根據 google search console 的數據，設定為 75% 薪水、25% 面試
> feat: end salary A/B testing

- .github/workflows/main.yml
對於較新版本的 nodejs (>=18)，會出現 Hash 錯誤，用 `NODE_OPTIONS=--openssl-legacy-provider` 解
> feature: test future nodejs version

- src/apis/companySearchApi.js
- src/components/ShareExperience/common/CompanyQuery.js
- src/components/ShareExperience/questionCreators.js
Close #1239 #1240  
移除舊版 `/companies/search`
改用 `Query.search_companies`
<table>
<tr>
<th>一頁一題公司名稱</th>
<td>
https://github.com/goodjoblife/GoodJobShare/assets/7566586/0b0a12fc-a96b-4c7f-b8d3-60d91078b101
</td>
</tr>
<tr>
<th>舊版面試表單</th>
<td>
https://github.com/goodjoblife/GoodJobShare/assets/7566586/65f7a08e-1e0e-4d5e-8104-4ed453250465
</td>
</tr>
<tr>
<th>公司表單</th>
<td>
https://github.com/goodjoblife/GoodJobShare/assets/7566586/5a823a2d-86c1-4b8e-b249-b8d885820181
</td>
</tr>
</table>
測試以下autocomplete:
> [API] 移除 /companies/search

- src/actions/auth.js
- src/components/ToastNotification/Notification.js
- src/components/ToastNotification/Notification.module.css
- src/components/ToastNotification/NotificationIcon.js
- src/components/ToastNotification/NotificationIcon.module.css
- src/components/ToastNotification/ToastNotification.module.css
- src/constants/authStatus.js
- src/constants/errorCodeMsg.js
Close #  
1. FB 登入發生錯誤時，送錯誤訊息到 rollbar (ref: https://github.com/goodjoblife/GoodJobShare/pull/1140)
2. FB 登入發生錯誤時，顯示 toast 訊息，並且有錯誤代碼，讓使用者可以回報，我們會更好 debug
> feat: send fb login error message to rollbar and display toast

- src/actions/auth.js
Close #  
現在已經有從 rollbar 追蹤 FB 登入發生錯誤的狀況。可以從下圖看出來大部分錯誤是 ER0006，fb API repsonse 的 status 是我們不知道的 status
但原本錯誤訊息不夠詳細，無法進一步 troubleshooting ，因此根據 [rollbar 官方文件](https://docs.rollbar.com/docs/rollbarjs-configuration-reference#rollbarlog)，帶上 extra 欄位（fb API response）
故意把 status 設成 `unknown` 製造一個 ER0006 ，payload 的內容
（意外的是 rollbar SDK 會幫擋 access token）
> feat: add extra field to rollbar.error

- src/actions/auth.js
- src/components/App/index.js
- src/constants/errorCodeMsg.js
1. 移除全站蓋板公告，現在每天遇到 fb login issue 的人數已經相對少 (<40）
2. 遇到 ER0006 (fb response unknown status)，提醒使用者清除瀏覽器資料
3. refactor dispatch 的使用方法
> feat: remove fb login announcement & enhance toast of FB login issue

- src/components/CompanyAndJobTitle/InterviewExperiences/ExperienceEntry.js
- src/components/CompanyAndJobTitle/WorkExperiences/ExperienceEntry.js
- src/graphql/company.js
Close #1246
將公司頁面的面試和經驗區塊改顯示 original company name
每個卡片都顯示不同的 company name 但指的是同一個公司
> [公司頁面] 面試卡片和工作卡片皆顯示 original company name

- src/components/CompanyAndJobTitle/InterviewExperiences/ExperienceEntry.js
- src/components/CompanyAndJobTitle/WorkExperiences/ExperienceEntry.js
- src/components/TimeAndSalary/common/formatter.js
- src/graphql/jobTitle.js
Close #1276   
在職稱頁面查看薪資工時，看到列出的公司名稱是 originalCompanyName 連結到 canonical URL
> [職稱薪時頁面] 顯示 originalCompanyName

- src/components/TimeAndSalary/NotFound.js
- src/routes.js
followed #1318
由於 /salary-work-times 於 #1318 移除，
所以
* `/time-and-salary/company/:keyword` 會導到 /salary-work-times，最後是 NotFound
* `/time-and-salary/job-title/:keyword` 會導到 /salary-work-times，最後是 NotFound
* `/search/xxxxx` 會導到 /salary-work-times，最後是 NotFound
所以移除這個 PR 幾個相關的路徑
ref:
```
curl -i https://www.goodjob.life/time-and-salary/company/台積
HTTP/2 301 
location: /salary-work-times?q=%E5%8F%B0%E7%A9%8D&s_by=company
curl -i "https://www.goodjob.life/salary-work-times?q=%E5%8F%B0%E7%A9%8D&s_by=company"
HTTP/2 301 
location: /salary-work-times/latest
```
> chore: remove legacy url

- src/components/ShareExperience/InterviewForm/TypeForm/index.js
- src/components/ShareExperience/TimeSalaryForm/TypeForm.js
- src/constants/errorCodeMsg.js
Close #  
1. 上傳薪資、面試時，如果出現錯誤，把錯誤訊息送到 rollbar ，瞭解發生的原因
2. 工作心得的部分等表單改版再做，現在上傳次數較少
面試經驗的部分，我把兩篇七天內的面試經驗設為 is_archived = true ，讓 API 判定太多垃圾資訊回錯誤去模擬
薪資的部分，我把實際日工時填寫 100 ，模擬後端回錯誤（這個其實是我們表單可以改進的地方）
- 面試表單比較麻煩，可先不測
> feat: send submit salary/interview error to rollbar

- src/components/App/index.js
- src/components/common/Questionnaire/CollapsedDrawer/index.js
由於 ExpandedModal 需要 `handleToggleModalOpen`，採用 renderProp 的方式來寫，避免還需要操作較底層的 cloneElement
- Back-end PR：
> bugfix: fix ExpandedModal proptype warning

- src/actions/experience.js
- src/components/LandingPage/ExperienceBlock/index.js
- src/graphql/popularExperience.js
Close #1342  
`popular_experience` 取 `originalCompanyName`
加上 prop types
> [最新面試心得] 顯示 originalCompanyName

- src/components/ShareExperience/AutoCompleteItem.js
Close #1352  
後端會保留統一編號在同名的公司名稱
前端遇到統一編號會另外顯示的時候，就移除名稱內的統一編號
|Before|After|
|-|-|
|![截圖 2024-06-22 凌晨12 59 42](https://github.com/goodjoblife/GoodJobShare/assets/7566586/e3e70248-461a-4109-94da-b8aead90aefb)|![截圖 2024-06-22 凌晨12 55 40](https://github.com/goodjoblife/GoodJobShare/assets/7566586/4f223c5b-ce53-4e2c-9aec-b70a15e659c8)|
> [公司搜尋] 有另外顯示統一編號時，移除公司名稱內的統一編號

- src/components/common/FormBuilder/index.js
Close #1358 
在一頁一題開啟時，阻擋 tab 事件
有點暴力，但剛剛有試過傳統的 tabIndex 發現不太容易擋全部
> [一頁一題表單] 阻擋 tab 事件

- src/apis/experiencesApi.js
- src/components/CompanyAndJobTitle/InterviewExperiences/ExperienceEntry.js
- src/graphql/experience.js
https://api-dev.goodjob.life/graphql
由於 experience API 將 sections 從 Experience 移出，變成 WorkExperience 和 InterviewExperience 有各自的 sections，寫 graphql 時要分開指定
由於 WorkExperience.sections.subtitle 和 InterviewExperience.sections.subtitle 有不同的型別，所以在打 api 時先取不同名稱，抓回來後再統一命名為 subtitle 以作最簡單的向前相容
> [經驗單篇] 修正sections

- src/actions/auth.js
- src/constants/errorCodeMsg.js
Close #1265 
1. google login 如果有發生錯誤，用 rollbar 記錄，並且跳 toast 給使用者
2. 針對 deactivated user ，目前是在 googleLogin & facebookLogin 兩個 mutation 去回 Forbidden error code （如果未來有我們主動停權帳號的話，也會是一樣的 code）。前端拿到這個 Forbidden code ，傳不同的訊息到 rollbar 以分辨不同種的錯誤
- Back-end PR：https://github.com/goodjoblife/WorkTimeSurvey-backend/pull/1036
分別是 deactivated google user & deactivated facebook user 試圖再次登入的錯誤訊息
> feat: handle google & facebook login error

- .github/docker-compose-dev.yml
- .github/docker-compose-production.yml
- .github/docker-compose-stage.yml
- .github/workflows/main.yml
Close #  
fix github action building docker image bug
It looks like ubuntu used by github ci removed `docker-compose` and is instead using `docker compose`.
same as https://github.com/goodjoblife/WorkTimeSurvey-backend/pull/1045
> hotfix: fix github ci docker image build problem

- .eslintrc.js
- src/components/CompanyAndJobTitle/useSearchbar.js
https://github.com/goodjoblife/GoodJobShare/pull/1381/files 有 `react-hooks/exhaustive-deps` 的問題，卻沒被及時發現，因為只是警告而非錯誤。
這個PR改成錯誤並修正。
> 修正 react-hooks/exhaustive-deps

- src/components/common/FormBuilder/QuestionBuilder/Date.js
Close #1401 
- rollbar 顯示這個錯誤滿多次的，對使用者來說會有點困擾，前端沒擋，到最後才跳錯誤訊息
- 不如一開始就不要顯示選項。基本上我認為 10 年前的資訊已經不具參考價值了
以現在的時間來說，只顯示到 2015 年
> fix: do not show option longer than 10 years

- src/components/ShareExperience/questionCreators.js
Close #1403 
- `工作日表訂工時` 標題以及解釋文字，加上一日、一天的提示。前端檢查是否在 0~24。
- `工作日實際平均工時` 標題以及解釋文字，加上一日、一天的提示。前端檢查是否在 0~24。
- `一週總工時`，前端檢查是否在 0~168。
> fix: working time field validation

- src/components/ShareExperience/common/SubmittableFormBuilder.js
- src/components/common/FormBuilder/index.js
- src/constants/errorCodeMsg.js
- FB 上還是很常收到使用者回饋面試表單無法成功上傳的問題，試著多加一個 rollbar 觸發點搜集資料，找出 root cause
> feat: send more rollbar message for debugging form submit issue

- src/apis/timeAndSalaryApi.js
- src/components/ShareExperience/common/CompanyQuery.js
- src/components/ShareExperience/questionCreators.js
- src/components/common/form/TextInput/SearchTextInput.js
- src/graphql/timeAndSalary.js
Close #1319
接上後端的 Query.search_companies 的 limit 參數
!有成功套用 limit!
```js
{
"query":"\n  query($companyName: String!, $hasData: Boolean!, $limit: Int) {\n    search_companies(query: $companyName, hasData: $hasData, limit: $limit) {\n      name\n      businessNumber\n      dataCount\n    }\n  }\n",
"variables":{"companyName":"台","hasData":true,"limit":5}}
```
!沒有改動，要不影響行為!
Query 保持一樣，不會卡 limit
```js
{
"query":"\n  query($companyName: String!, $hasData: Boolean!, $limit: Int) {\n    search_companies(query: $companyName, hasData: $hasData, limit: $limit) {\n      name\n      businessNumber\n      dataCount\n    }\n  }\n",
"variables":{"companyName":"台積","hasData":true}
}
```
!有成功套用 limit!
```js
{
"query":"\n  query($companyName: String!, $hasData: Boolean!, $limit: Int) {\n …
```
> feat: Query.search_companies add limits

- src/actions/company.js
- src/actions/jobTitle.js
- src/apis/company.js
- src/apis/jobTitle.js
- src/graphql/company.js
- src/graphql/jobTitle.js
related to #1385
Overview 頁面更換成 pagination api
api 正確
> [公司職稱頁面] Overview use pagination api

- src/actions/company.js
- src/actions/jobTitle.js
- src/apis/company.js
- src/apis/jobTitle.js
- src/components/Company/CompanyPageProvider.js
- src/components/Company/CompanyWorkExperiencesProvider.js
- src/components/CompanyAndJobTitle/WorkExperiences/WorkExperiences.js
- src/components/CompanyAndJobTitle/WorkExperiences/index.js
- src/components/JobTitle/JobTitlePageProvider.js
- src/components/JobTitle/JobTitleWorkExperiencesProvider.js
- src/graphql/company.js
- src/graphql/jobTitle.js
- src/reducers/companyIndex.js
- src/reducers/jobTitleIndex.js
- src/routes.js
- src/selectors/companyAndJobTitle.js
#1385 
讓公司/職稱頁面的面試經驗標籤頁做分頁，包含搜尋。
原本公司頁面的資料都放在 `state.company.[name].status|data|error`，資料包含薪資、面試、經驗。
由於薪資會獨立獲取，現將薪資移至 `state.companyIndex.workExperiencesByName.[name].status|data|error`。
搜尋時，應該只有底下的 table 會 loading，但目前會連 search bar 一起 reload，影響使用者體驗。
本 PR 先專注在抽換 API，後續 UI 優化會由 #1416 處理。
https://github.com/goodjoblife/WorkTimeSurvey-backend/pull/1043
https://github.com/user-attachments/assets/975138b2-d87f-46f1-ad88-f77bc5641a0a
> [公司職稱頁面] 評價分頁

- src/actions/company.js
- src/actions/jobTitle.js
- src/apis/company.js
- src/apis/jobTitle.js
- src/components/Company/CompanyInterviewExperiencesProvider.js
- src/components/Company/CompanyPageProvider.js
- src/components/CompanyAndJobTitle/InterviewExperiences/InterviewExperiences.js
- src/components/CompanyAndJobTitle/InterviewExperiences/index.js
- src/components/JobTitle/JobTitleInterviewExperiencesProvider.js
- src/components/JobTitle/JobTitlePageProvider.js
- src/graphql/company.js
- src/graphql/jobTitle.js
- src/reducers/companyIndex.js
- src/reducers/jobTitleIndex.js
- src/routes.js
- src/selectors/companyAndJobTitle.js
#1385 
讓公司/職稱頁面的面試經驗標籤頁做分頁，包含搜尋。
原本公司頁面的資料都放在 `state.company.[name].status|data|error`，資料包含薪資、面試、經驗。
由於薪資會獨立獲取，現將薪資移至 `state.companyIndex.interviewExperiencesByName.[name].status|data|error`。
搜尋時，應該只有底下的 table 會 loading，但目前會連 search bar 一起 reload，影響使用者體驗。
本 PR 先專注在抽換 API，後續 UI 優化會由 #1416 處理。
https://github.com/goodjoblife/WorkTimeSurvey-backend/pull/1043
https://github.com/user-attachments/assets/e06368b6-3a2c-40a5-bd2c-65d21dc351c1
> [公司職稱頁面] 面試經驗分頁

- src/components/ShareExperience/WorkExperiencesForm/TypeForm.js
- src/constants/errorCodeMsg.js
Close #1428 
1. 送出評價表單時如果有錯誤，送 error 到 rollbar 
2. 原本以為要加 hotjar trigger event ，但其實原本的實作就已經有，因此不用更動
故意 throw 一個 error 可以看到打 rollbar API
> feat: send error to rollbar when submit work experience form failed

- src/graphql/jobTitle.js
Close #1431  
1. add averageSectionRating queryQL query to make jobtitle card showing OverallRating。職稱總覽頁面、職稱評價頁面同時顯示新舊版卡片。
起 local 可看到職稱總覽頁面、職稱評價頁面同時顯示新舊版卡片。
> feat: add averageSectionRating queryQL query 

- src/components/CompanyAndJobTitle/Searchbar.js
原本用 debounce 秒數搜尋
由於現在改用 API 搜尋，搜尋成本變高，切換頁面也影響使用者體驗
於是改用 onBlur 這類更明確的使用者 intention 來觸發搜尋
https://github.com/user-attachments/assets/f8e81391-3db7-4149-8e2b-243f327ab560
> [公司職稱頁面] Onblur搜尋

- src/client.js
Close #1439
原本，location有任何變化時，就會重設捲軸位置。
但搜尋經驗時產生的 `?q` 變化，並不適合重設捲軸位置。
本 PR 將 `?q` 作為例外。
https://github.com/user-attachments/assets/c2168c09-a81e-45b7-970f-293abe0c68d2
> search query變動時不改變捲軸位置

- src/actions/company.js
- src/apis/company.js
- src/components/CompanyAndJobTitle/CompanyAndJobTitleWrapper.js
- src/components/CompanyAndJobTitle/CompanyAndJobTitleWrapper.module.css
- src/graphql/company.js
- src/pages/Company/CompanyInterviewExperiencesProvider.js
- src/pages/Company/CompanyOverviewProvider.js
- src/pages/Company/CompanyTimeAndSalaryProvider.js
- src/pages/Company/CompanyWorkExperiencesProvider.js
- src/reducers/companyIndex.js
- src/selectors/companyAndJobTitle.js
Close #1390 #1399  
在公司名稱旁邊加上平均分數+評分數量
- Back-end PR： goodjoblife/WorkTimeSurvey-backend#1046
|phone|laptop|
|-|-|
|![畫面擷取於 2024-09-24 01 20 39](https://github.com/user-attachments/assets/a93eb8ab-1521-45a7-b7e5-68b92e555418)|![Screenshot 2024-09-24 at 01-21-17 台灣大學 總覽 GoodJob 職場透明化運動](https://github.com/user-attachments/assets/7f67c9d6-c77c-4e9e-b93f-761a406ed05c)|
- `companyStatistics` 感覺要改名叫做 `ratingStatistics`？
- ~~目前 API return 是 null，但明明有經驗和評分？ http://www-dev.goodjob.life/companies/%E5%8F%B0%E7%81%A3%E5%A4%A7%E5%AD%B8~~
~~Tested on api-dev: https://api-dev.goodjob.life/graphql~~
```
{
company(name:"台灣大學") {
companyStatistics {
averageRating
ratingCount
}
}
}
```
```
{
"data": {
"company": {
"companyStatistics": null
}
}
}
```
[UPDATE] 後端 null 的問題已經修好了
> [公司頁面] 加上平均分

- src/components/CompanyAndJobTitle/CompanyAndJobTitleWrapper.module.css
Close #  
- 對齊一下 company rating 的垂直位置
before:
after:
> Fix: company rating position

- src/components/common/FormBuilder/AnimatedPager.js
- src/components/common/FormBuilder/index.js
Close #1414  
因為表單將所有頁面都選染出來，以達到簡易動畫效果。
然而卻暴露了能夠透過 tab 非預期跳頁的風險。
沒有全部渲染的動畫不好做，這個PR暫時關掉動畫。
https://github.com/user-attachments/assets/74dc698d-006c-4fb5-bf6b-4cd9a92c91c4
> 關閉表單動畫以避免同時渲染多頁

- src/components/CompanyAndJobTitle/InterviewExperiences/ExperienceEntry.js
- src/components/CompanyAndJobTitle/WorkExperiences/ExperienceEntry.js
- src/components/ExperienceDetail/MoreExperiencesBlock/index.js
- src/constants/gaConstants.js
- 追蹤單篇文章頁面，點擊看更多 experience 區塊的數據
> feat: 追蹤看更多 experience 的數據

- src/components/ExperienceDetail/Article/ArticleInfo.js
- src/components/ExperienceDetail/experienceSelector.js
- src/components/ShareExperience/common/ExperienceInYear.js
現在單篇顯示 experience in year 的名稱是 "相關職務評價"，somehow 有點怪，修正之
> fix: wording of experience in years

- src/components/ShareExperience/InterviewForm/TypeForm/index.js
- src/components/ShareExperience/constants.js
- src/components/ShareExperience/questionCreators.js
- src/components/common/FormBuilder/QuestionBuilder/TextArea.js
Close #1457
移除「為這次面試打個分數」
也一併修理 TextArea 的 prop validation
> feat: 移除面試整體評分

- src/apis/experiencesApi.js
- src/apis/timeAndSalaryApi.js
- src/components/ExperienceDetail/MessageBoard/CommentBlock.js
- src/components/ExperienceDetail/MessageBoard/index.js
- src/components/ExperienceDetail/hooks/useQueryReplies.js
- src/components/Me/useQuery.js
- src/graphql/experience.js
- src/graphql/timeAndSalary.js
Close #  
將 restful api 換掉
管理我的資料 > 面試 Toggle 正常運作
任何一篇 Experience 留言，可以取得資料
> chore: replace restful api to graphql

- src/graphql/experience.js
Close #1458  
單篇的區塊評分，沿用工作經驗的元件，只要補上面試經驗API取得區塊評分就行
|Before|After|
|-|-|
|![localhost_3000_companies_A](https://github.com/user-attachments/assets/9a2d812d-2e9c-4a3d-9abb-bea57e039b14)|![localhost_3000_experiences_678dab4e3f763016fdfca35a](https://github.com/user-attachments/assets/abf6bbe9-a19f-40be-b63b-bbb19bcbd946)|
- 我發現被 paywall 擋住的工作經驗，不會顯示 section ratings，這是預期的嗎？ @YongChenSu @barry800414
> [經驗單篇] 加上區塊評分

- src/components/LaborRightsSingle/Body.js
- src/components/LaborRightsSingle/index.js
Close #  
小修正一些 propTypes, 但發現一些問題（都是小問題）
1. 做 Helmet 的 seoTitle 在這個 [PR](https://github.com/goodjoblife/GoodJobShare/pull/58/files#diff-4572b688704fd378d2832c7e1ec6fd71cfd98b4d1314b666d07ed554e449d57cR31) 是拿 title 欄位，沒用到 seoTitle 欄位 <--- 要請 @barry800414 幫忙確認，理論上應該要用 seoTitle
所以調整成拿 seoTitle 欄位優先當 helmet title, 若無，則拿 title 欄位
3. seoDescription 有可能是 null，沒有的話，拿 description 欄位 （雖然實際上 seoDescription 都有資料，但避免困混就修正）
打開小教室的原始碼，Helmet 依然有資料
> chore: fix LaborRightsSingle propTypes

- src/components/ShareExperience/questionCreators.js
- src/components/common/FormBuilder/QuestionBuilder/CheckboxRatingTextAreaList/ActiveItem.js
Close #1501 
- 修復評價表單最後一題 crash 的問題
- Root cause 是，hasRating default value 不是 func，會導致 ActiveItem crash
> hotfix: work experience form crash

- src/components/CompanyAndJobTitle/TimeAndSalary/EsgBlock/EsgBlock.js
- src/components/CompanyAndJobTitle/TimeAndSalary/EsgBlock/EsgBlock.module.css
- src/utils/stringUtil.js
- src/utils/stringUtil.test.js
Close #  
1. 修復同產業平均比較都是 -100% 的問題（傳入的數字沒有同除同樣的數）
2. 如果是正數，加上 `+` 前綴
3. 如果是正數，顯示為黑色，如果是負數，顯示為紅色 (by figma)
> [ESG] Fix: same industry compare

- .github/docker-compose-dev.yml
- .github/docker-compose-production.yml
- .github/docker-compose-stage.yml
- src/components/CompanyAndJobTitle/CompanyAndJobTitleWrapper.js
- src/components/CompanyAndJobTitle/Overview/EmployerAggregateRating.js
- src/components/CompanyAndJobTitle/Overview/EmployerAggregateRatingSeo.js
- src/components/CompanyAndJobTitle/Overview/Helmet.js
- src/config/index.js
Close #  
1. 只有 overview 頁面才 render 這個 google structural data，避免 google 有很多頁面選擇，反而不知道要顯示哪一個
2. 加上更多欄位（name, description, worstRating, bestRating 等），基本上是參照 interview dot tw 的下去做，不過沒有放麵包屑結構（interview dot tw 做的 structural data 可參考[這裡](https://search.google.com/test/rich-results/result/r%2Femployer-ratings?id=q_rtY80xOtAXs8jHL-W0TA) )
> feat: 調整 EmployerAggregateRating 

- src/components/App/Footer/LinkItem.js
- src/components/App/Footer/index.js
- src/components/CompanyAndJobTitle/CompanyAndJobTitleWrapper.js
- src/components/CompanyAndJobTitle/CompanyAndJobTitleWrapper.module.css
- src/components/CompanyAndJobTitle/InterviewExperiences/ExperienceEntry.js
- src/components/CompanyAndJobTitle/Overview/SnippetBlock.js
- src/components/CompanyAndJobTitle/TimeAndSalary/InfoModal.js
- src/components/CompanyAndJobTitle/WorkExperiences/ExperienceEntry.js
- src/components/ExperienceDetail/Article/SectionBlock.js
- src/components/ExperienceDetail/Heading/index.js
- src/components/ExperienceDetail/MoreExperiencesBlock/index.js
- src/components/ExperienceDetail/ReactionZone/ReportInspectModal.js
- src/components/TimeAndSalary/common/OvertimeBlock.js
- src/components/common/LoginModal/index.js
- src/components/common/PermissionBlock/LoginToUnlock.js
- src/components/common/PermissionBlock/PermissionBlock.module.css
- src/components/common/base/Heading.js
- src/components/common/base/Heading.module.css
- src/components/common/base/P.js
- src/components/common/base/P.module.css
1. 讓網站的 h1, h2, h3 結構更符合 SEO 優化的需求
2. 更動的頁面與元件至少包含：
a. 公司的總覽/薪資/面試/評價列表頁面
b. 職稱的總覽/薪資/面試/評價列表頁面
c. 職場經驗單篇
d. footer
使用 [Detail SEO chrome extension](https://detailed.com/extension/) 協助檢測
> feat: tweak website h1,h2,h3 structure

- src/actions/company.js
- src/actions/experience.js
- src/actions/jobTitle.js
- src/graphql/company.js
- src/graphql/experience.js
- src/graphql/jobTitle.js
- src/pages/Company/CompanyInterviewExperiencesProvider.js
- src/pages/Company/CompanyWorkExperiencesProvider.js
- src/pages/JobTitle/JobTitleInterviewExperiencesProvider.js
- src/pages/JobTitle/JobTitleWorkExperiencesProvider.js
Close #1530 
修復巢狀經驗的問題，統一經驗資料在 Redux store 中的位置。
- 將所有 GraphQL 的經驗資料存副本到 Redux store 中，避免資料重複獲取與不一致性。
- 使用 `setExperience` action 處理並統一存儲經驗資料。
- 修復公司頁面與職稱頁面之間不一致的 GraphQL query，統一資料結構。
https://github.com/user-attachments/assets/6cbe70a9-289d-45e3-95e9-438e3f036d8f
- 訪問公司頁面
- 訪問職位頁面
- 單篇經驗
> [面試/經驗/單篇] 統一資料位置

- src/components/ExperienceDetail/hooks/useLoginFlow.js
Close #  
這裡提到的
https://github.com/goodjoblife/GoodJobShare/pull/1542#issuecomment-2851343908
當按下 `SubscribeNotificationButton` 時，會有 callback (處理登入流程 與 call mutation api) 執行，
--> 當 callback 正在執行時，如果切換 tab (i.e. routing component change)，就會造成 `SubscribeNotificationButton` unmount
--> 當 unmount 時，callback 結束時，會嘗試 setState 來重設 LoginFlow 的流程
--> 但此時 LoginFlow 的 setState 已經失效，所以執行的話，會發生 memory leak
https://github.com/user-attachments/assets/436b14b6-0f9e-41be-aec8-9afd3a907184
修改一下 callback, 將 isMounted() 印出
(1) 按下 SubscribeNotificationButton，印出 true
(2) 按下 SubscribeNotificationButton，快速切換 tab，印出 false
(2) 就是 unmount 發生
> fix: prevent setState if unmounted

- src/components/CompanyAndJobTitle/InterviewExperiences/Helmet.js
- src/components/CompanyAndJobTitle/TimeAndSalary/Helmet.js
- src/components/CompanyAndJobTitle/WorkExperiences/Helmet.js
Close #1519
將公司職稱頁面的 canonical url 無視 page
|Before|
|-|
|![截圖 2025-05-13 晚上11 52 28](https://github.com/user-attachments/assets/2fb603f3-a0dd-49fc-a62c-aba9bee98e83)|
|After|
|![截圖 2025-05-13 晚上11 52 07](https://github.com/user-attachments/assets/db676b53-b871-4f4a-85b2-db438421d2fd)|
> [公司職稱頁面] 移除 Canonical url 的 page

- src/components/CompanyAndJobTitle/SubscribeNotificationButton/SubscribeNotificationButton.module.css
Close #  
修正 chrome 瀏覽器上，手機版 hover style
- 修正前 Chrome 手機版，取消訂閱後維持 hover 狀態時的 style
- 修正後
用 chrome 手機版點選訂閱公司按鈕
> fix: 新資料通知，手機版 style

- src/components/CompanyAndJobTitle/CompanyAndJobTitleWrapper.js
- src/components/CompanyAndJobTitle/Experience.js
- src/components/CompanyAndJobTitle/InterviewExperiences/InterviewExperiences.js
- src/components/CompanyAndJobTitle/Overview/Overview.js
- src/components/CompanyAndJobTitle/TimeAndSalary/Helmet.js
- src/components/CompanyAndJobTitle/WorkExperiences/WorkExperiences.js
- src/components/ExperienceDetail/Article/SectionBlock.js
- src/components/ExperienceDetail/Article/index.js
- src/constants/companyJobTitle.js
Close #1553  #1554 
基於 SEO 、使用者體驗考量，修改：
| 頁面 | 類別 | 原本 | 修改後  |
|------|---|---|---|
| 公司 面試經驗列表  |  h1  | OOO公司 | OOO公司 面試經驗  |
| 公司 面試經驗列表  |  h2  | OOO公司XXX職稱  | XXX職稱 面試經驗 | 
| 公司 面試經驗列表  |  h3  | 原本的面向是h2  | 改成 h3  | 
| 公司 評價列表  |  h1  | OOO公司 | OOO公司 評價  |
| 公司 評價列表  |  h2  | OOO公司XXX職稱  | XXX職稱 評價 | 
| 公司 評價列表  |  h3  | 原本的面向是h2  | 改成 h3  | 
| 職稱 面試經驗列表  |  h1  | XXX職稱 | XXX職稱 面試經驗  |
| 職稱 面試經驗列表  |  h2  | OOO公司XXX職稱 | OOO公司 面試經驗  | 
| 職稱 面試經驗列表  |  h3  | 原本的面向是h2  | 改成 h3  | 
| 職稱 評價列表  |  h1  | XXX職稱 | XXX職稱 評價  |
| 職稱 評價列表  |  h2  | OOO公司XXX職稱 | OOO公司 評價  | 
| 職稱 評價列表  |  h3  | 原本的面向是h2  | 改成 h3  | 
面向指的是單篇的不同 subtitle (e.g. 薪資福利、工作內容）
| 原本 |  修改後  |
|------|-------|
| ![Screenshot 2025-05-24 at 10 07 51 PM](https://github.com/user-attachments/assets/e6e29ef8-699a-4cc7-89ef-3d179 …
> feat: 公司/職稱的 面試/評價列表頁面 h1, h2, h3 調整
