goodjoblife/GoodJobShare

.dockerignore
circle.yml
docker/Dockerfile
docker/package.json
docker/server.js

可上線的 docker image 將會在：https://hub.docker.com/r/goodjoblife/goodjobshare/tags/
ci 的流程如下
```
branch commit   --> + Test                  --> + Deployment (to docker hub)
(trigger circleci)  |                           | 
+-> npm install             +-> 是 master branch
+-> npm test                +-> docker push
| (post-test，當測試通過後) 
+-> npm run build
+-> docker build
```
建立好的 image 是可以執行的
```
docker run -d goodjoblife/goodjobshare:VERSION
```

使用 ci 自動化 build image 流程

---

webpack.config.base.js
webpack.config.dev.js
webpack.config.prod.js
webpack.config.stylelint.js

因為 CI 忘了打開要跑 PR 的，所以沒顯示出 lint 需要修正的地方(see #17)，送上一個 PR 修正

eslint, fix cs

---

package.json
src/actions/counter.js
src/components/Counter.js
src/reducers/counter.js
src/reducers/index.js
webpack.config.base.js
webpack.config.dev.js
webpack.config.prod.js
webpack.config.stylelint.js
yarn.lock

#7 
加上兩個lib:
facebook/immutable-js
HurricaneJames/react-immutable-proptypes
另外把使用示範更改進counter 的reducer,   component中。
為了更有使用到immutable ，把原本的counter state 由number 轉為immutable.Map，所以多了一層。
（很無謂，但為了示範方便）

導入immutable 系統

---

src/components/LandingPage/Classrooms.js
src/components/LandingPage/HomeBanner.js
src/components/LandingPage/HomeBanner.module.css
src/components/LandingPage/ShareExperienceWrapper/ShareExperienceItem.js
src/components/LandingPage/ShareExperienceWrapper/index.js
src/components/Layout/App.module.css
src/components/Layout/Footer.js
src/components/Layout/Header.js
src/components/Layout/Header.module.css
src/components/common/variables.module.css

home page style fixed

---

src/components/common/global.module.css
src/containers/AnotherPage.js

1. 依 https://projects.invisionapp.com/d/main#/console/10208710/225568941/preview 增加 font 相關的 class
2. 有在 AnotherPage.js 放上效果 demo，切到 http://localhost:3001/another 可以看結果
3. 有兩個 commit，第一個 commit 是照設計稿的 class name 命名，第二個 commit 是把 class name 換成 camel case (但是有些換成 camel case 看起來有點不直覺，要不要考慮 js 用 camel case，css 還是使用 - 來分隔呢 ?)

Font class

---

src/components/Layout/App.module.css
src/components/common/reset.module.css
src/index.html

由於之後 SSR 會由 server 端產生 html 模板，所以把 reset css 搬移成 module

搬移 Reset Css

---

src/server.js

這裡我改寫 CounterPage 當作範例
**重點**
1. Action Creator 是一個 Function，讓它回傳 (1) Action (2) `Function: dispatch => Promise`
2. componentDidMount 與 fetchData 都要呼叫到 Action Creator
Action Creator 裡面可以做任何事，發 Action，打 API 都可
**細節**
第1步：一般情況
`Counter` Component 當中的 `componentDidMount` 會透過 Action Creator 觸發一個 Action
```
componentDidMount() {
this.props.setCounterFromParams(this.props.params);
}
```
> 這裡的 `this.props.setCounterFromParams` 跟 `setCounterFromParams` 有些差別，在 connect 的過程中，前者被包過而不必使用 `store.dispatch`
第2步：讓 Action Creator 回傳一個 Promise
因為 redux-thunk 的幫忙，所以 Action Creator 可以回傳一個 Function 或是 Action Object
改寫這個 Function，讓它既回傳 Promise，也 dispatch action
```
const setCounterFromParams = () =>
dispatch => 
Promise.resolve().then(() => dispatch(setValue(100)));
```
第3步：fetchData 引入
由於 Server 端不會執行 …

讓 Server 端透過 fetchData 與 componentDidMount 結合

---

src/components/LaborRightsMenu/LectureEntry.module.css

fix小教室目錄的圖片style

---

src/utils/contentfulUtils.js

避免沒有 token, space 造成錯誤
如果想要指定自己的空間，設定下面兩個環境變數
* CONTENTFUL_TOKEN
* CONTENTFUL_LABOR_RIGHTS_SPACE

Contentful: 加上開發用的 token, space

---

src/components/LaborRightsSingle/Pagers.js

修正小教室單篇的上一篇/下一篇連結

---

package.json

縮排package.json裡的pre-commit: ["lint"]

---

src/actions/laborRightsSingle.js

影響：SSR 會在 fetchData 結束後，立刻 render，導致 state 處在抓取資料的狀態

小教室單篇 fetchData 沒有回傳 Promise

---

src/components/ExperienceDetail/CommentBlock.js
src/components/ExperienceDetail/CommentBlock.module.css
src/components/ExperienceDetail/MessageBoard.js
src/components/ExperienceDetail/MessageBoard.module.css
src/components/ExperienceDetail/index.js

先放一版經驗單篇頁目前的進度，目前僅完成https://projects.invisionapp.com/d/main#/console/10208710/221006008/preview 中的留言板初版 layout

added MessageBoard

---

src/components/LaborRightsSingle/MarkdownParser.module.css

如果 li 裡面還有塞 tag，reset 他的 font-size，避免文字一直變大。

如果 li 裡面還有塞 tag，reset 他的 font-size

---

src/components/common/form/Checkbox.js
src/components/common/form/Checkbox.module.css
src/components/common/form/Radio.js
src/components/common/form/Radio.module.css

開放 Radio 及 Checkbox 的 margin 屬性，讓開發者可視排版進行覆寫

added "margin" property for Radio and Checkbox

---

src/components/ExperienceDetail/CommentBlock.module.css
src/components/ExperienceDetail/MessageBoard.js
src/components/ExperienceDetail/MessageBoard.module.css
src/components/ExperienceDetail/RecommendationBlock.js
src/components/ExperienceDetail/RecommendationBlock.module.css
src/components/ExperienceDetail/RecommendationZone.js
src/components/ExperienceDetail/RecommendationZone.module.css
src/components/ExperienceDetail/index.js
src/components/ExperienceSearch/ExperienceBlock.js
src/components/common/Block.module.css

added recommendation zone in experience details (#16)

---

src/components/Layout/Header/SiteMenu.js

fixed header svg

---

src/components/LaborRightsMenu/index.js
src/components/Layout/Header/SiteMenu.js

「勞動小教室」改名為「勞動知識小教室」

---

src/components/Layout/Footer/index.js

Fix Footer facebook link

---

src/components/LaborRightsMenu/index.js
src/helpers/Html.js

Ref #99 
未來打算把 helmet 進行整理，目前少頁面不確定怎麼整理比較好

Add description, og property, favicon

---

src/components/LaborRightsSingle/Footer.js
src/components/Layout/Header/index.js
src/config/config.dev.js
src/config/config.prod.js
src/config/index.js
src/utils/contentfulUtils.js
src/utils/fetchUtil.js
webpack.config.base.js
webpack.config.dev.js
webpack.config.prod.js

把一些有 process.env 的集中放到 config 中
分成 dev 與 production 常用的設定
如果需要不同的參數，可以透過環境變數帶入

Add a config, centralize the env and settings

---

src/actions/experienceSearch.js
src/components/ExperienceSearch/ExperienceBlock.js
src/components/ExperienceSearch/index.js
src/reducers/experienceSearch.js

* 讓經驗列表的每筆經驗可以被點選進入單篇
* 在下載資料時顯示 loading mask

added loading mask

---

src/actions/experienceDetail.js
src/components/ExperienceDetail/Article.module.css
src/components/ExperienceDetail/CommentBlock.js
src/components/ExperienceDetail/MessageBoard.js
src/components/ExperienceDetail/ReactionZone.js
src/components/ExperienceDetail/ReactionZone.module.css
src/components/ExperienceDetail/index.js
src/components/common/button/Button.js
src/components/common/global.module.css
src/components/common/reaction/Report.js
src/components/images/explanation.svg
src/reducers/experienceDetail.js

針對單篇經驗，增加以下 API 介接：
* 讀取留言列表
* 新增留言
* 增加/取消留言的讚

experience-detail apis

---

src/actions/experienceDetail.js
src/components/ExperienceDetail/Article.js
src/components/ExperienceDetail/Article.module.css
src/components/ExperienceDetail/InfoBlock.js
src/components/ExperienceDetail/InfoBlock.module.css
src/components/ExperienceDetail/QABlock.js
src/components/ExperienceDetail/SectionBlock.js
src/components/ExperienceDetail/index.js
src/reducers/experienceDetail.js

* 介接單篇經驗 API
* 將單篇經驗左方資訊獨立出成元件

added experience fetching api

---

src/actions/experienceDetail.js
src/components/ExperienceDetail/Article.js
src/components/ExperienceDetail/index.js
src/reducers/experienceDetail.js

1. 主要是把 Article 那個 component 補上與 API 對應的資料
2. 修正 route 轉換時（由 /experiences/A --> /experiences/B）不會觸發 componentDidMount，需另外處理資料更新
3. SSR

面試/工作經驗單篇頁 顯示邏輯修正

---

src/actions/experienceDetail.js
src/components/ExperienceDetail/MessageBoard.module.css
src/components/ExperienceDetail/ReactionZone.js
src/components/ExperienceDetail/RecommendationZone.module.css
src/components/ExperienceDetail/index.js
src/components/ExperienceSearch/ExperienceBlock.module.css
src/components/common/reaction/Base.js
src/components/common/reaction/Base.module.css
src/components/common/reaction/ThumbsUp.js
yarn.lock

* 補上按讚的功能
* 移除「你可能還想看」區塊
* 留言的功能補強（這部份之前已有實作，只是沒資料測試，所以之前 commit 的程式是用 mock ... 這次 commit 已把實際 api 的註解移掉 ... 雖然我還是找不到哪筆資料有留言可以測試 XD）

experience details enhancement (#134) (#143)

---

src/components/common/Modal.js
src/components/common/Modal.module.css

* 增加一個Modal Component
* style 應該需要校調
* 原本把 **新增資料** ，以及串表單entry 都寫進header，不過rebase 發現跟master 差超多。果斷只送新增Modal 的PR，我再送另一個串起來的PR。

新增Modal Component

---

src/components/ShareExperience/InterviewForm/formCheck.js
src/components/ShareExperience/common/optionMap.js
src/components/ShareExperience/utils.js
src/components/common/form/Select.js

* 若為選取 **相關職務工作經驗問題** 欄位，則送出時移除該項。
* 若年數為0，選項中字樣為「小於一年」
#146

解決相關職務工作經驗問題

---

src/components/ShareExperience/WorkExperiencesForm/WorkInfo/RecommendToOthers.js
src/components/ShareExperience/WorkExperiencesForm/index.js
src/components/common/button/ButtonGroupImage.js

推薦此工作 的按鈕能夠取消

---

src/components/LaborRightsMenu/index.js

另外要麻煩 @mark86092 部署這個 commit 上去，謝謝！

update og:image for labor-rights

---

src/components/ShareExperience/InterviewForm/InterviewInfo/index.js
src/components/ShareExperience/InterviewForm/formCheck.test.js
src/components/ShareExperience/InterviewForm/index.js
src/components/ShareExperience/WorkExperiencesForm/WorkExperience/index.js
src/components/ShareExperience/WorkExperiencesForm/WorkInfo/index.js
src/components/ShareExperience/WorkExperiencesForm/formCheck.test.js
src/components/ShareExperience/WorkExperiencesForm/index.js

#131 
在CompanyQuery 的onChange 除了更換companyQuery 值外，也一併更換title 這欄位的值

自動產生面試經驗/工作經驗 標題

---

src/components/ShareExperience/WorkExperiencesForm/formCheck.js

修正工作經驗填寫頁沒有更新的formCheck

---

src/components/ShareExperience/InterviewForm/formCheck.js
src/components/ShareExperience/InterviewForm/index.js
src/components/ShareExperience/WorkExperiencesForm/index.js
src/components/ShareExperience/utils.js

在要post api 時，檢查salaryAmount 是否有值。
#139

修復填寫表單頁面，薪資格式問題

---

package.json
src/actions/experienceSearch.js
src/components/ExperienceSearch/WorkingHourTable.js
src/components/ExperienceSearch/index.js
src/reducers/experienceSearch.js
yarn.lock

apply infinite scroll to fetch more experiences

---

LICENSE

我選了 MIT license，可以更換，不過至少要選擇一個 open source 授權

增加 MIT LICENSE

---

src/actions/experienceSearch.js
src/components/ExperienceSearch/index.js

`src/actions/experienceSearch.js` 引用 status 沒刪乾淨的 bug

清理註解的 code 與修正 bug

---

src/actions/experienceSearch.js
src/components/LandingPage/index.js

enhancement for fetching popular experiences (#177)

---

src/components/ExperienceDetail/CommentBlock.js

make the count of floor 1-based

---

src/components/ExperienceDetail/CommentBlock.js
src/components/ExperienceDetail/ReactionZone.js

removed the functionality of report

---

package.json
src/components/ShareExperience/InterviewForm/InterviewExperience/index.js
src/components/ShareExperience/InterviewForm/InterviewForm.module.css
src/components/ShareExperience/InterviewForm/InterviewInfo/InterviewResult.js
src/components/ShareExperience/InterviewForm/InterviewInfo/InterviewResult.module.css
src/components/ShareExperience/InterviewForm/InterviewInfo/InterviewTime.js
src/components/ShareExperience/InterviewForm/InterviewInfo/InterviewTime.module.css
src/components/ShareExperience/InterviewForm/InterviewInfo/OverallRating.js
src/components/ShareExperience/InterviewForm/InterviewInfo/OverallRating.module.css
src/components/ShareExperience/InterviewForm/InterviewInfo/index.js
src/components/ShareExperience/InterviewForm/formCheck.js
src/components/ShareExperience/InterviewForm/formCheck.test.js
src/components/ShareExperience/InterviewForm/index.js
src/components/ShareExperience/WorkExperiencesForm/WorkExperience/index.js
src/components/ShareExperience/WorkExperiencesForm/WorkExperiencesForm.module.css
src/components/ShareExperience/WorkExperiencesForm/WorkInfo/index.js
src/components/ShareExperience/WorkExperiencesForm/formCheck.js
src/components/ShareExperience/WorkExperiencesForm/formCheck.test.js
src/components/ShareExperience/WorkExperiencesForm/index.js
src/components/ShareExperience/common/CompanyQuery.js
src/components/ShareExperience/common/JobTitle.js
src/components/ShareExperience/common/Region.js
src/components/ShareExperience/common/Region.module.css
src/components/ShareExperience/common/Sections.js
src/components/ShareExperience/common/Sections.module.css
src/components/ShareExperience/common/SubmitArea.js
src/components/ShareExperience/common/Title.js
src/components/common/form/Select.js
yarn.lock

* 在需要檢查的欄位加上紅框與提示字樣
* 在點選 `submit` 後會先作validation ，若沒通過則捲動至最上方，並且出現提示副標題
* 延上，若通過則直接送出表單，與之前的流程相同
* 盡可能照著 #176 @wutingy 給的wording 風格、格式，但有些沒有，我就先腦補了，可能需要改正。
* 只能跳到最上方，無法到特定未通過檢查的欄位。
#176

面試 / 工作兩頁的表單合格檢查

---

src/components/ExperienceDetail/Article.js

hide QA when there is no data to display

---

src/components/ExperienceSearch/WorkingHourTable.js
src/constants/employmentType.js

added the missing fields of WorkingHourTable

---

src/components/ExperienceDetail/Article.js
src/components/ExperienceDetail/Article.module.css

adjust the field of sensitive questions (#199)

---

src/components/ShareExperience/InterviewForm/formCheck.js
src/components/ShareExperience/InterviewForm/index.js

修正創建QA block 函數的bug

---

src/components/ShareExperience/InterviewForm/formCheck.js

因為收了兩個個別沒問題的PR ，但卻發生了漏引用的情況，補上它。

Undefined Variable Issue

---

src/components/ShareExperience/InterviewForm/InterviewInfo/InterviewTime.js
src/components/ShareExperience/InterviewForm/formCheck.js

* 正確檢驗年份及月份
* 警告文字會依據是年份、月份不合格動態更換
#210

修正面試時間的檢驗以及警告文字

---

package.json
src/components/ShareExperience/InterviewForm/formCheck.js
yarn.lock

目前專案有pre-commit lint test，不過因為會針對所有的檔案都做過一遍，讓commit 變得有點慢。
所以只針對該次commit 所作用的檔案即可。

Pre-commit action 只針對staged file

---

src/components/ShareExperience/InterviewForm/formCheck.js
src/components/common/form/AutoCompleteTextInput.js

* 因為輸入法問題（例如注音輸入法，通常打完字後需要再一次enter 來確認選字），會有menu 不出現的問題。事實上在打完字後是會出現的，但按下enter 後則又消失了。故依據`onFocus`、`onBlur` 自行handle open 的狀態。
* 當接收到的候選名單是空陣列時，隱藏menu。
#215 #195

處理AutoCompleteTextInput bug

---

src/components/common/reaction/Base.js
src/components/common/reaction/Base.module.css
src/components/common/reaction/Comment.js
src/components/common/reaction/Report.js
src/components/common/reaction/ThumbsUp.js

增加Reaction 元件的可觸及範圍至整個方框

---

src/components/ExperienceDetail/Article.js
src/components/ExperienceDetail/Article.module.css
src/components/ExperienceDetail/ReactionZone.js

visualize interview rating (#198)

---

src/components/ShareExperience/InterviewForm/InterviewInfo/index.js
src/components/ShareExperience/WorkExperiencesForm/WorkInfo/index.js
src/components/ShareExperience/common/Region.js

Add inputTitle to Region component

---

src/actions/auth.js
src/components/ExperienceDetail/index.js
src/components/Layout/Header/index.js
src/components/ShareExperience/common/SubmitArea.js
src/components/common/button/ButtonSubmit.js
src/constants/authStatus.js
src/reducers/auth.js

我是全域搜尋`connected`、`not_authorized`、`unknown` 來選定要改的範圍，有再確認改過的檔案所涉及到的畫面是否正常。
不曉得還有沒有漏抽的地方？

將FB 登入狀態抽成常數

---

src/components/ShareExperience/InterviewForm/InterviewExperience/index.js
src/components/ShareExperience/InterviewForm/InterviewForm.module.css
src/components/ShareExperience/InterviewForm/InterviewInfo/InterviewInfo.module.css
src/components/ShareExperience/InterviewForm/InterviewInfo/InterviewTime.js
src/components/ShareExperience/InterviewForm/InterviewInfo/OverallRating.js
src/components/ShareExperience/InterviewForm/InterviewInfo/OverallRating.module.css
src/components/ShareExperience/InterviewForm/index.js
src/components/ShareExperience/ShareExperience.module.css
src/components/ShareExperience/WorkExperiencesForm/WorkExperience/index.js
src/components/ShareExperience/WorkExperiencesForm/WorkExperiencesForm.module.css
src/components/ShareExperience/WorkExperiencesForm/WorkInfo/WeekWorkTime.js
src/components/ShareExperience/WorkExperiencesForm/WorkInfo/index.js
src/components/ShareExperience/WorkExperiencesForm/index.js
src/components/ShareExperience/common/Education.js
src/components/ShareExperience/common/ExperienceInYear.js
src/components/ShareExperience/common/Region.js
src/components/ShareExperience/common/Salary.js
src/components/ShareExperience/common/Salary.module.css
src/components/ShareExperience/common/share.module.css
src/components/ShareExperience/index.js
src/components/common/button/ButtonAdd.js
src/components/common/button/ButtonGroupElement.module.css
src/components/common/button/ButtonGroupImage.js
src/components/common/button/ButtonGroupMultiElement.module.css
src/components/common/button/RateButton.js
src/routes.js

* 至少達到不會重疊，並且元件間有至少5px 空間
* 只有針對550 寬度以下，所以desktop 至mobile 間不是最好效果（但大多應該有達成第一點）
* 增加「面試過程」等欄位的按鈕，沒想到比較好跟下方「QA」不重疊的方式

兩個填寫頁面的RWD

---

src/components/ShareExperience/InterviewForm/InterviewExperience/index.js
src/components/ShareExperience/InterviewForm/index.js
src/components/ShareExperience/WorkExperiencesForm/WorkExperience/index.js
src/components/ShareExperience/WorkExperiencesForm/index.js
src/components/ShareExperience/common/SectionEle.js
src/components/ShareExperience/common/Sections.js
src/components/ShareExperience/common/SubmitArea.js
src/components/ShareExperience/common/optionMap.js
src/components/ShareExperience/common/share.module.css
src/components/common/button/ButtonAdd.js
src/components/common/button/ButtonAddElement.module.css

closes #110 
* 修改原本的補完標題
* 接受placeholder
* 程式介面也能接受titlePlaceholder

面試/工作經驗填寫頁 section title, placeholder

---

src/components/Guidelines/index.js
src/components/Layout/Footer/index.js

done guidelines page

---

src/components/LaborRightsSingle/index.js

LaborRightsSingle 的 helmet 忘記修改到，送 fix

fix title and og:title of LaborRightsSingle

---

src/components/ShareExperience/common/SubmitArea.js

把每個可能的 feedback 都設定上 hasClose 參數

Enable control hasClose over different feedbacks

---

src/constants/helmetData.js

- change landingPage og:image
- add facebook app_id

小修改 helmet

---

.circleci/config.yml
.circleci/prepare-docker-login.sh

How complicated the aws registry authetication

---

src/components/ExperienceDetail/Article.js
src/components/ShareExperience/InterviewForm/InterviewInfo/OverallRating.js
src/components/ShareExperience/common/ExperienceInYear.js

Close #267 
`相關職務工作經驗` -> `自身相關職務工作經驗`
`面試整體滿意度` -> `對公司面試整體滿意度`
工作經驗單篇： `應徵職稱` ->   `職稱`

fix wordings

---

src/components/common/button/RateButtonElement.js

因應 #275 改變了Glike 的export 方式，RateButtonElement import Glike 的方式也需要調整。

調整RateButtonElement 取用Glike icon 的方式

---

src/components/common/PopoverToggle/Popover.module.css
src/components/common/PopoverToggle/index.js

修正Popover點選外部可關閉

---

src/components/Me/ShareBlockElement/index.js
src/components/Me/index.js
src/components/common/PopoverToggle/Popover.module.css

- use href not react-router
- 讓他連到搜尋公司名稱 url（我不確定這樣對嗎？需要 @mark86092 review

調整 /me 薪時連結

---

src/helpers/Html.js

我們公司有用 [Hotjar](https://www.hotjar.com/) 這個服務，發現我們很需要它！
有主要幾個功能：
1. HeatMap：搜集大量使用者點擊的紀錄，畫成熱力圖，可以知道使用者哪邊點最多
2. Recording：這個有點變態..，就是把整段使用流程錄起來
3. Funnel：看使用者是從哪個頁面流走的，跟GA使用者流程很像
4. Form：還可以有個 fixed 表單，搜集使用者回饋或 email 
免費版是 2000 page views/day ，我們網站現在平均一天 700 ~ 800 page view ，還很夠用
@mark86092 @wutingy

使用 Hotjar 追蹤使用者點擊與使用網站的流程

---

src/components/LaborRightsMenu/LaborRightsEntry.js
src/components/LaborRightsMenu/index.js

實作置入型小教室篇目，如圖片的 "募資中"
本 PR 從 #320 中抽出

小教室目錄頁 - 置入"募資中" 文案

---

bin/server.js
src/components/Layout/Footer/index.js
src/components/Layout/Header/SiteMenu.js
src/components/Me/ShareBlockElement/index.js
src/routes.js
src/server.js
webpack.config.base.js

修正連往 /time-and-salary 的連結

---

src/apis/timeAndSalaryApi.js
src/components/TimeAndSalary/SearchBar.js

#316 
close #327 
本PR做了以下事情：
1. 修復`SearchBar`的`onSubmit`跳轉行為
2. Auto complete完成

薪時查詢頁面的SearchBar修復&Auto complete

---

.github/PULL_REQUEST_TEMPLATE.md

新增 PR template 

---

src/actions/experienceSearch.js
src/apis/experiencesApi.js
src/components/ExperienceSearch/ExperienceSearch.module.css
src/components/ExperienceSearch/Pagination/Pagination.js
src/components/ExperienceSearch/Pagination/Pagination.module.css
src/components/ExperienceSearch/Pagination/helpers.js
src/components/ExperienceSearch/Pagination/index.js
src/components/ExperienceSearch/helper.js
src/components/ExperienceSearch/index.js
src/components/LandingPage/index.js
src/containers/ExperienceSearchPage.js
src/reducers/experienceSearch.js
src/selectors/experienceSearchSelector.js

Close #313 
* 本來的增加更多資料機制改為分頁式
* 分頁資訊綁定routing
* search type 綁定routing
* 讓path 中 `p=` 與 完全沒有`p` 這個項目有相同的結果 （@mark86092 不知道怎麼敘述更好 ＸＤ）
* 資料抓取中時會有Loading
建議是從Component 看起，往回action --> reducer 看起。

New: 完成面試、工作查詢頁面分頁綁定與loading 狀態

---

src/apis/experiencesApi.js

add default valut to searchType
修 getExperiences 不相容產生的錯誤

Fix getExperiences breaks

---

bin/server.js
src/routes.js
src/server.js
webpack.config.base.js

1. 從 #326 pick 一些 commit 過來，主要是改寫 `renderProps` 裡面如何取出 SSR 要用的 component
2. 修正 `query` 不在 `renderProps` 中，而是在 `renderProps.location`
commit 96fd565 請參考 #326 
commit d2d5cf7 是解 Bug

修正 SSR 取值的 Bug

---

src/components/TimeAndSalary/TimeAndSalaryBoard/index.js
src/components/TimeAndSalary/TimeAndSalaryCompany/index.js
src/components/TimeAndSalary/TimeAndSalaryJobTitle/index.js

幫 TimeAndSalary 三大頁面加上 SSR
1. `npm run start` 後，query 頁面應該會看到 prerender 好的 html

TimeAndSalary 部分加上 SSR

---

src/reducers/laborRightsSingle.js

Close #381
error 是一個 object，當 reducer 塞入 store 的時候，應該要轉成 immutable 物件
PR 後會看到

Resolve #381

---

src/components/TimeAndSalary/TimeAndSalaryCompany/index.js
src/components/TimeAndSalary/TimeAndSalaryJobTitle/index.js
src/components/TimeAndSalary/views/view.module.css

TimeAndSalary loading 狀態處理

---

src/components/ShareExperience/common/CompanyQuery.js
src/components/ShareExperience/common/JobTitle.js

我 checkout 到 master，yarn install 後，可能因為 react-dom 更新，表單填寫區的公司＆職稱填寫時會跳錯誤訊息：
應該是新版的 react-dom 不允許這種寫法了，但不知道為什麼 production 沒有問題。
總之先換個可行，local 端也不會錯的方法。

fix props undefined problem

---

src/components/Layout/Header/SiteMenu.js

Close #405
增加部落格連結，刪除 user link，韋銘有建議要加箭頭但是我認為不用，因為已經很清楚了。

add blog link remove user link

---

src/components/ExperienceSearch/ExperienceSearch.module.css
src/components/ExperienceSearch/Pagination/Pagination.js
src/components/ExperienceSearch/Pagination/Pagination.module.css

Close #409  
修正 safari style bug
run start 看 `/experiences/search` 畫面是否正確

fixed #409

---

src/components/Layout/Footer/index.js
src/components/Layout/Header/SiteMenu.js

Close #414
原本是要新增一個，經討論決定改文字即可。

Update: Add link to header

---

src/components/ExperienceDetail/BackToList.js
src/components/ShareExperience/Entry.js
src/components/common/PopoverToggle/index.js

將 `history` 透過 HOC `withRouter` 傳入

Replace createHistory with withRouter

---

src/components/ExperienceSearch/ExperienceBlock/helper.js
src/components/ExperienceSearch/Filter/index.js
src/components/ExperienceSearch/helper.js
src/components/ExperienceSearch/index.js

ExperienceSearch 擴充實習經驗

---

src/components/ExperienceDetail/Article/Article.module.css
src/components/ExperienceDetail/Article/Aside.js
src/components/ExperienceDetail/Article/RateButtons.js
src/components/ExperienceDetail/Article/RateButtons.module.css
src/components/ExperienceDetail/Heading/index.js
src/components/ExperienceDetail/index.js
src/components/ExperienceSearch/ExperienceBlock/helper.js
src/components/ExperienceSearch/Filter/index.js
src/components/ExperienceSearch/helper.js
src/components/ExperienceSearch/index.js
src/components/Layout/Footer/index.js
src/components/Layout/Header/SiteMenu.js

New: 整合實習透視鏡、實習資料整合 (dev)

---

src/components/LandingPage/Banner.js
src/components/LandingPage/Banner.module.css

將 banner 換成新的文案
#430 其中之ㄧ的 task

#430 首頁主 banner

---

src/components/TimeAndSalary/TimeAndSalaryBoard/index.js

TimeAndSalaryBoard補上重置極端值資料

---

src/components/ExperienceSearch/Pagination/Pagination.js

Pagination 「第一頁」改成「最前頁」

---

src/components/ExperienceSearch/Banners/Banner1.js
src/components/ExperienceSearch/Banners/Banner2.js
src/components/Layout/Footer/index.js
src/components/Layout/Header/Top/index.js
src/components/Layout/Header/index.js
src/components/common/CallToAction/CallToActionFolder.js
src/constants/helmetData.js

Close #430 
Footer
Header 募資條
募資塊
helmet

[網站名稱更改] change website name, slogan and wording

---

src/components/common/ProgressBar/ProgressBar.js
src/components/common/ProgressBar/ProgressBarWithDataCount.js
src/containers/ProgressBar.js

1. 讓 goalNum 變成 progressbar component 的 props
2. 把 dataCount 改名為 dataNum，跟 goalNum 一致
測試同 #446

refactor: ProgressBar

---

src/components/Layout/index.js
src/containers/Root.js

Close #449 
之前升級React Router v4 時漏補這段，這裡補上。
* 將logPageView 抽成pure function
* 在Root 的componentDidMount 與componentDidUpdate 埋logPageView

Fix page view issue

---

README.md

Update readme to 職場透明化運動，and add new wording

---

src/components/CampaignTimeAndSalary/CampaignTimeAndSalaryBoard/index.js
src/components/TimeAndSalary/TimeAndSalaryBoard/index.js
src/components/TimeAndSalary/common/AboutThisJobModal.js
src/components/TimeAndSalary/common/formatter.js

Close #454
1. Campaign查詢頁面補上AboutThisJobModal
2. 加上`title = companyName + jobTitle` // Tin的指示
3. if (aboutThisJob) 不顯示放大鏡按鈕 // Tin的指示

AboutThisJobModal更新+bugfix

---

src/apis/campaignInfoApi.js

Close #471 
調整預設搜尋的職稱列表，挑了資料最多的幾個。

Update: campaign queryJobTitles

---

package.json
yarn.lock

AutoComplete升級

---

src/components/CampaignTimeAndSalary/Banner.module.css
src/components/TimeAndSalary/SearchBar.js
src/components/TimeAndSalary/SearchBar.module.css

修正 #473 第三點
1. Campaign的Banner style補上media query的`margin-top`
2. Campaign的InfoModal toggle `margin-top`

修正Campaign style

---

src/components/TimeAndSalary/common/AboutThisJobModal.js

AboutThisJobModal style

---

src/components/ShareExperience/CampaignTimeAndSalaryForm/index.js
src/components/ShareExperience/utils.js

aboutThisJob若與defaultContent相同就改送出空字串

---

src/components/ShareExperience/CampaignTimeAndSalaryForm/index.js
src/components/ShareExperience/common/SubmitArea.js

Close #501 
Campaign 表單頁填完後，要導到 Campaign 查詢頁

Campaign 表單頁填完後，導到 Campaign 查詢頁

---

src/components/ExperienceDetail/index.js
src/utils/fetchUtil.js

解決 https://www.goodjob.life/experiences/WRONG_ID 頁面沒有正確顯示 NotFound 的問題

Pass fetch HTTP status code to downstream

---

src/actions/campaignTimeAndSalaryBoard.js
src/actions/timeAndSalaryBoard.js
src/components/CampaignTimeAndSalary/CampaignTimeAndSalaryBoard/index.js
src/components/TimeAndSalary/TimeAndSalaryBoard/index.js
src/containers/CampaignTimeAndSalary/CampaignTimeAndSalaryBoard.js
src/containers/TimeAndSalary/TimeAndSalaryBoard.js
src/reducers/campaignTimeAndSalaryBoard.js
src/reducers/timeAndSalaryBoard.js

Close #487 
薪資工時頁面（包含Campaign 頁），讀取到底部的話，就不再打 api 了。

Fix/stop sending API when reach bottom

---

src/components/CampaignTimeAndSalary/CampaignTimeAndSalaryBoard/index.js
src/components/common/PermissionBlock/BasicPermissionBlock.js

Close #502  
讓 campaign 頁的查詢頁權限區塊，導到 campaign 的表單頁

update: goto campaign form if in campaign table

---

src/components/ShareExperience/TimeSalaryForm/BasicInfo.js

fix: fix wording of time and salary form

---

src/components/Faq/index.js

修正 FAQ 頁面的 wording，避免使用者再填寫表單請我們刪除、修改資訊。

Update: wording in FAQ page

---

src/utils/facebook.js

Upgrade facebook sdk to v3.0

---

src/helpers/Html.js

Move css to <head>

---

package.json
src/actions/campaignTimeAndSalaryBoard.js
src/components/CampaignTimeAndSalary/CampaignTimeAndSalaryBoard/index.js
src/containers/CampaignTimeAndSalary/CampaignTimeAndSalaryBoard.js
src/reducers/campaignTimeAndSalaryBoard.js
yarn.lock

Close #541 
Campaign 薪資工時查詢頁，改成分頁。
參考 #534

feat: Campaign 薪資工時查詢頁 改分頁

---

src/components/ShareExperience/CampaignTimeAndSalaryForm/index.js
src/components/ShareExperience/InterviewForm/index.js
src/components/ShareExperience/TimeSalaryForm/index.js
src/components/ShareExperience/WorkExperiencesForm/index.js
src/components/ShareExperience/common/SubmitArea.js

Disable submit button during submitting

---

src/store/middlewares.js

這個 bug 導致 https://www-stage.goodjob.life/time-and-salary/latest 產生 500

Bugfix: Fix window is not defined, bug from #556

---

src/components/CampaignTimeAndSalary/CampaignTimeAndSalaryBoard/helmet.js
src/components/CampaignTimeAndSalary/CampaignTimeAndSalaryBoard/index.js
src/components/CampaignTimeAndSalary/index.js
src/reducers/campaignInfo.js

close #546
整理 Campaign 頁面的 helmet，修正文字，並且加上頁碼

Campaign 頁 Helmet

---

src/components/CampaignTimeAndSalary/CampaignTimeAndSalaryBoard/index.js
src/components/CampaignTimeAndSalary/index.js
src/components/TimeAndSalary/TimeAndSalaryBoard/index.js
src/components/TimeAndSalary/common/withModal.js
src/components/TimeAndSalary/index.js

Extract Modal to HOC

---

src/actions/laborRights.js
src/components/LaborRightsSingle/index.js
src/store/middlewares.js
src/utils/errors/httpError.js
src/utils/errors/index.js
src/utils/fetchUtil.js

這個 PR 整理了 Redux 方面的錯誤處理流程
```
catch error --> 可處理 --> update store
--> 不可處理 --> Sentry 紀錄 --> 拋出錯誤
```

Redux 錯誤處理

---

src/utils/fetchUtil.js

這個 bug 沒有影響到任何重要的 API，除了`取得搜尋關鍵字的API` 會在未登入下沒有資料

Bugfix: should send in json type

---

src/components/common/PermissionBlock/CallToLoginShareButton.js

remove useless code
see https://sentry.io/goodjob/goodjob-frontend-production/issues/702596345/events/

Bugfix: fix handleIsOpen is not a function

---

src/actions/laborRights.js

Bugfix: labor right entry pass entryId to action

---

.eslintrc.js
src/components/ExperienceDetail/ReactionZone/ReportInspectModal.js
src/components/ShareExperience/CampaignTimeAndSalaryForm/index.js
src/components/TimeAndSalary/SearchBar.js

Remove old method

---

src/components/ExperienceDetail/Article/Article.module.css
src/components/ExperienceDetail/Article/index.js
src/components/ExperienceDetail/BackToList.js
src/components/ExperienceDetail/BackToList.module.css
src/components/ExperienceDetail/ExperienceDetail.module.css
src/components/ExperienceDetail/Heading/Heading.module.css
src/components/ExperienceDetail/Heading/index.js
src/components/ExperienceDetail/LikeZone/LikeZone.js
src/components/ExperienceDetail/LikeZone/LikeZone.module.css
src/components/ExperienceDetail/ReactionZone/ReactionZone.module.css
src/components/ExperienceDetail/index.js

Close #594
手機版
（明明只是想加個手機版 style 結果重寫了好多東西，工程師真的很不會寫 css 誒）
不知道為什麼 `LikeZone.js` 不要用已經有的 `ThumbUp.js` 要自己在裡面寫一個 component?
@peteranny

Mobile Style Experience Detail

---

src/actions/experienceDetail.js
src/actions/experiences.js
src/actions/me.js
src/actions/reports.js
src/actions/timeAndSalary.js
src/apis/experiencesApi.js
src/apis/interviewExperiencesApi.js
src/apis/reportsExperiencesApi.js
src/apis/timeAndSalaryApi.js
src/apis/workExperiencesApi.js
src/components/ExperienceDetail/ReportForm/ReportForm.js
src/components/ShareExperience/CampaignTimeAndSalaryForm/index.js
src/components/ShareExperience/InterviewForm/index.js
src/components/ShareExperience/TimeSalaryForm/index.js
src/components/ShareExperience/WorkExperiencesForm/index.js
src/containers/ExperienceDetail/ReportFormContainer.js
src/containers/ShareExperience/CampaignTimeAndSalaryFormContainer.js
src/containers/ShareExperience/InterviewFormContainer.js
src/containers/ShareExperience/TimeSalaryFormContainer.js
src/containers/ShareExperience/WorkExperiencesFormContainer.js

Close #607
確保每個需要 Token 的 API 有帶出 token

Migrate api

---

src/server.js

React redux 會直接將 static expose 出來，修正，避免 fetchData 有問題

---

src/components/TimeAndSalary/TimeAndSalarySearch/index.js

解決 #617 所說的跳轉網址的問題
是修改成新API後我漏改掉一個與API相關的取值，故修正之

fix name extraction on redirect

---

package.json

為了方便開發自動fix stylelint，在lint-staged加上`stylelint --fix`和`git add`

add stylelint in lint-staged

---

src/client.js
src/server.js

修正了之前把 react-router-redux 移除時，忘記把 routing key 拔掉

Refactor store

---

src/actions/timeAndSalarySearch.js
src/components/TimeAndSalary/SearchScreen/SearchScreen.js

調整薪資工時搜尋行為

---

src/components/TimeAndSalary/common/injectHideContentBlock.js
src/components/TimeAndSalary/common/injectHideContentBlock.module.css

Close #645   
修正表格RWD
未登入狀況下進入薪資工時，搜尋公司或是職稱，點入單篇頁面，可以看到表格
調整螢幕大小觀察變化

修正薪資工時表格RWD

---

src/components/Company/SalaryWorkTimeScreen.js
src/components/JobTitle/SalaryWorkTimeScreen.js
src/components/TimeAndSalary/SearchScreen/SearchScreen.js

Close #654 #638
補上忘記做`encode/decodeURIComponent`的部分

fix when slash in keyword

---

src/apis/experiencesApi.js
src/components/ExperienceDetail/Article/Aside.js
src/graphql/experience.js

職場經驗單篇 API 換 GraphQL

---

src/actions/timeAndSalary.js
src/actions/timeAndSalaryBoard.js
src/apis/timeAndSalaryApi.js
src/components/TimeAndSalary/common/formatter.js
src/graphql/timeAndSalary.js
src/reducers/timeAndSalaryBoard.js

#660   
最新工時 更換成graghql api
並且修正一些相關的東西
目前 salary_work_time_count 有問題，所以數量顯示不了
要先等 goodjoblife/WorkTimeSurvey-backend#566 解掉才能正常顯示

薪資工時預設列表頁 API 換 GraphQL

---

src/components/App/Header/Top/EmailVerificationTop.js
src/components/EmailVerification/VerifyEmailForm.js
src/selectors/authSelector.js

Close #693 
email dialog 自動填入 email

feat: auto fill user email from me API

---

src/components/App/Header/Top/EmailVerificationTop.js
src/components/EmailVerification/VerifyEmailForm.js
src/components/EmailVerification/VerifyEmailForm.module.css
src/selectors/authSelector.js
src/utils/dataCheckUtil.js

base on #694 ，多加功能：
驗證信箱的部分，加上 validation ，檢查是否有明顯的格式錯誤
- Front-end PR：#694
email validate regex: https://stackoverflow.com/questions/46155/how-to-validate-an-email-address-in-javascript

Feature: email validate

---

src/components/App/Header/Top/EmailVerificationTop.js
src/components/EmailVerification/VerifyEmailForm.js

改寫驗證信的 wording ，變成「訂閱」
- 覺得不用測試，真的就是改字而已

refactor: change wording of email collecting

---

src/components/ExperienceDetail/Article/Article.module.css
src/components/ShareExperience/InterviewForm/InterviewExperience/InterviewSensitiveQuestions.js
src/components/ShareExperience/InterviewStepsForm/InterviewForm.module.css
src/components/ShareExperience/InterviewStepsForm/QAs/InterviewSensitiveQuestions.js
src/components/ShareExperience/InterviewStepsForm/Section/Section.module.css
src/components/ShareExperience/InterviewStepsForm/index.js
src/components/ShareExperience/common/SectionEleContent.module.css
src/components/common/Block/Block.module.css

Close #711 
- 修正現在 production 面試經驗分享頁面的手機版
- 檢查單篇職場經驗分享 rwd
希望過了之後可以儘速上到正式站。
拉下來看看手機版還有沒有其他問題

interview share rwd style

---

src/components/Guidelines/Guidelines.test.js
src/components/Guidelines/index.js

hotfix: fix guideline page

---

src/routes.js

Close #706 
1. 訂出routing rule
2. 除了salary-and-time ，都先給一個最小的component 代表
`/companies/:companyName` --> 總覽
`/companies/:companyName/salary-work-times` --> 薪資&加班
`/companies/:companyName/interview-experiences` --> 面試經驗
`/companies/:companyName/work-experiences` --> 工作經驗
`/job-titles/:jobTitle` --> 總覽
`/job-titles/:jobTitle/salary-work-times` --> 薪資&加班
`/job-titles/:jobTitle/interview-experiences` --> 面試經驗
`/job-titles/:jobTitle/work-experiences` --> 工作經驗

create routing rule

---

src/actions/popularExperiences.js
src/apis/experiencesApi.js
src/components/LandingPage/index.js
src/graphql/popularExperience.js

Close https://github.com/goodjoblife/GoodJobShare/issues/692

Replace legacy popular experiences with graphql

---

src/components/EmailVerification/VerificationPage.js
src/components/ExperienceDetail/Article/ArticleInfo.js
src/components/ExperienceDetail/index.js
src/components/ExperienceSearch/index.js
src/components/LaborRightsMenu/index.js
src/components/LaborRightsSingle/Footer.js
src/components/LaborRightsSingle/index.js
src/components/Me/ShareBlockElement/index.js
src/components/ShareExperience/InterviewStepsForm/index.js
src/components/ShareExperience/TimeSalaryForm/SalaryInfo.js
src/components/ShareExperience/common/CompanyQuery.js
src/components/ShareExperience/common/JobTitle.js
src/components/TimeAndSalary/SearchScreen/SearchScreen.js
yarn.lock

1. upgrade packages
2. fix prettier

Upgrade package

---

src/actions/viewLog.js
src/apis/index.js
src/apis/viewLogApi.js
src/components/Company/SalaryWorkTimeScreen.js
src/components/Company/ViewLog.js
src/components/Company/withRouteParameter.js
src/containers/Company/ViewLog.js
src/graphql/timeAndSalary.js
src/graphql/viewLog.js

Close #  
瀏覽公司頁的時候，紀錄 View Log，可以用來計算瀏覽量

View log on company

---

src/components/ShareExperience/InterviewStepsForm/Step1.js
src/components/ShareExperience/InterviewStepsForm/Step2.js
src/components/ShareExperience/InterviewStepsForm/Step3.js
src/components/common/button/ButtonRect.js

@peteranny  這個是把 ButtonRect 變成可以傳 Tag type 進去的 PR
沒問題的話就合進去吧！

refactor: make ButtonRect as Link or Button according to props

---

src/components/ShareExperience/InterviewStepsForm/InterviewForm.module.css
src/components/ShareExperience/InterviewStepsForm/QAs/InterviewQa.js
src/components/ShareExperience/InterviewStepsForm/QAs/InterviewQas.js
src/components/ShareExperience/InterviewStepsForm/Section/index.js
src/components/ShareExperience/InterviewStepsForm/Step1.js
src/components/ShareExperience/InterviewStepsForm/Step2.js
src/components/ShareExperience/InterviewStepsForm/Step3.js
src/components/ShareExperience/InterviewStepsForm/StepControl.js
src/components/ShareExperience/InterviewStepsForm/StepControl.module.css
src/components/ShareExperience/InterviewStepsForm/formCheck.js
src/components/ShareExperience/InterviewStepsForm/index.js
src/components/ShareExperience/common/SectionEleContent.js
src/components/ShareExperience/common/SectionEleContent.module.css
src/components/ShareExperience/common/SubmitArea.js
src/components/common/Feedback.js
src/components/common/button/ButtonRect.js
src/constants/formElements.js
src/containers/ShareExperience/SubmitAreaContainer.js

這個 feature 想早點上線，因為這個改好後，我要把權限機制導到面試經驗表單做測試

Release 經驗分享頁面更新 (#721) 

---

src/components/CompanyAndJobTitle/InterviewExperiences/InterviewExperiences.js
src/components/CompanyAndJobTitle/InterviewExperiences/index.js
src/components/CompanyAndJobTitle/StatusRenderer.js
src/components/CompanyAndJobTitle/TimeAndSalary/TimeAndSalary.js
src/components/CompanyAndJobTitle/TimeAndSalary/index.js
src/components/CompanyAndJobTitle/WorkExperiences/index.js
src/components/JobTitle/JobTitlePageProvider.js

將StatusRenderer的children改為function，可傳入自訂的render function
並讓工時薪資、面試經驗、工作經驗都使用相同元件渲染
此為code重構，不應該改變原本UI行為

[公司職稱頁面] 共用StatusRenderer

---

src/components/CompanyAndJobTitle/Overview/Overview.js
src/components/CompanyAndJobTitle/Overview/Overview.module.css
src/components/CompanyAndJobTitle/Overview/SnippetBlock.js
src/components/CompanyAndJobTitle/Overview/index.js
src/selectors/companyAndJobTitle.js

Close #745
把目前的工時薪資、工作經驗、面試經驗拼起來
在沒有資料的時候(`isEmpty`)會不顯示資料，並且修改title

[公司職稱頁面] 總覽

---

src/components/CompanyAndJobTitle/Overview/Overview.js
src/components/CompanyAndJobTitle/Overview/SnippetBlock.js

#759 
修改總覽的empty state
Zeplin: https://app.zeplin.io/project/5c316d528cc2d146a73dfc59/screen/5d51460b333aeb9b061f81b9

[公司職稱頁面] 總覽Empty state

---

src/components/TimeAndSalary/AutoCompleteTextInput.js
src/components/TimeAndSalary/AutoCompleteTextInput.module.css
src/components/TimeAndSalary/SearchBar.js
src/components/TimeAndSalary/SearchBar.module.css
src/components/TimeAndSalary/SearchScreen/SearchScreen.js
src/components/TimeAndSalary/SearchScreen/WorkingHourBlock.js
src/components/TimeAndSalary/SearchScreen/WorkingHourBlock.module.css
src/components/TimeAndSalary/common/validators.js
src/components/TimeAndSalary/index.js
src/components/TimeAndSalary/styles.module.css

#771 
依照UI修改，autocomplete打api的部分先用搜尋公司的api暫代
http://localhost:3000/salary-work-times/latest

[公司/職稱頁面] 修改搜尋結果頁面

---

src/components/ExperienceDetail/Article/Article.module.css
src/components/ExperienceDetail/Article/ArticleInfo.js

Close #780
依照UI加上日期Label (右上角灰色日期)
http://localhost:3000/experiences/5d9855a19a935d0012f29c75

經驗分享頁面加上日期

---

src/components/ExperienceSearch/ExperienceBlock/ExperienceBlock.module.css
src/components/ExperienceSearch/ExperienceBlock/helper.js
src/components/ExperienceSearch/ExperienceBlock/index.js
src/components/LandingPage/index.js

Close #776  
依照UI修改wording & block。
http://localhost:3000

[首頁改版] 最新心得分享區塊

---

.circleci/docker-compose-dev.yml
.circleci/docker-compose-production.yml
.circleci/docker-compose-stage.yml
src/actions/auth.js
src/apis/auth.js
src/components/App/Header/index.js
src/components/common/LoginModal/LoginModal.module.css
src/components/common/LoginModal/index.js
src/components/common/PermissionBlock/BasicPermissionBlock.js
src/components/common/PermissionBlock/CallToLoginShareButton.js
src/components/common/PermissionBlock/LaborRightsPermissionBlock.js
src/components/common/PermissionBlock/PermissionBlock.module.css
src/components/common/google/index.js
src/config/index.js
src/containers/PermissionBlock/CallToLoginShareButtonContainer.js

Close #687   
串接Google Login
- Back-end PR：[PR595](https://github.com/goodjoblife/WorkTimeSurvey-backend/pull/595)
- 有哪些文件需要被更新嗎？ No 
按登入 檢查 mongo db user collections

Google login

---

src/components/Company/CompanyPageProvider.js
src/components/JobTitle/JobTitlePageProvider.js

從route path解析出來的params有問題，應該要用decodeURIComponent來解析
結果發現這些元件的檔案本身就已經有一個selector寫好了，用在SSR
所以就直接拿來用
Before
After

[公司/職稱頁面] 修正pageName

---

src/actions/timeAndSalarySearch.js
src/components/App/Header/Searchbar.js
src/components/TimeAndSalary/SearchBar.js
src/components/TimeAndSalary/SearchScreen/SearchScreen.js
src/reducers/timeAndSalarySearch.js

原本是用pathname決定公司或職稱
因為現在改成合併查詢了，所以現在要用查詢結果來決定
搜尋公司名 `Yahoo` 
搜尋職稱 `隨車服務員`

[公司職稱頁面] Bugfix: 用資料決定公司或職稱

---

src/components/CompanyAndJobTitle/InterviewExperiences/ExperienceEntry.js
src/components/CompanyAndJobTitle/InterviewExperiences/InterviewExperiences.module.css
src/components/CompanyAndJobTitle/Overview/SummaryBlock.module.css
src/components/CompanyAndJobTitle/TabLinkGroup.module.css
src/components/CompanyAndJobTitle/WorkExperiences/ExperienceEntry.js
src/components/CompanyAndJobTitle/WorkExperiences/WorkExperiences.module.css
src/components/ExperienceSearch/ExperienceBlock/ExperienceBlock.module.css
src/components/LaborRightsMenu/LaborRightsEntry.js
src/components/LandingPage/CallToActionBlock.js
src/components/LandingPage/SummarySection.js
src/components/LandingPage/SummarySection.module.css
src/components/LandingPage/index.js
src/components/TimeAndSalary/SearchBar.module.css
src/components/TimeAndSalary/index.js
src/components/TimeAndSalary/styles.module.css
src/components/common/Charts/CompanyDistributionChart.js

#759
1. 首頁RWD
2. 公司/職稱頁面 RWD
3. 首頁區塊順序調整
然後本來的方式我通常沒動，但我自己會寫mobile first css，告知reviewer 一下。 
TBD
我的電腦Gifox 一直無法取得螢幕錄製授權，有時間再弄個GIF
這個PR 主要都是view，在desktop 與mobile 看起來沒問題，大致就可以了。

[公司/職稱頁面][首頁改版] 首頁與公司/職稱頁面 RWD 與細節調整

---

LICENSE
src/components/About/index.js
src/components/App/Footer/LinkItem.js
src/components/App/Footer/index.js
src/components/App/Header/SiteMenu.js
src/components/App/Header/index.js
src/components/LandingPage/index.js
src/components/TimeAndSalary/SearchBar.js
src/constants/dataProgress.js

昨天跟 @yudilai 討論 UI 的優化，有一些比較簡單，我就直接改。
想請 @wutingy 直接看Ｏ不ＯＫ
1. search bar wording 小修，讓使用者知道是公司“或”職稱
2. header 的項目希望放主要功能，我把小教室＆百工寫真移動到 footer。然後 slogan 有小改。
3. 關於我們頁面，上面的 call to action 區塊移除掉（沒什麼效果），下方徵才文字更新

Feat: 改一些 wording

---

src/config/index.js
src/helpers/Html.js

- 加上 google adsense SDK
Note：目前只有一個帳號，不太確定需不需要分 production / dev / local 
所有功能都要 production 站上認證過後才能用，所以想先合進去

feat: add google adsense sdk

---

public/ads.txt

讓 goodjob.life/ads.txt 可以讀到檔案，for google adsense 用

chore: add ads.txt

---

src/components/GoogleAdsenseTestPage/GoogleAdsenseTestPage.module.css
src/components/GoogleAdsenseTestPage/index.js
src/components/common/GoogleAdsense/index.js
src/routes.js

測試 google adsense 廣告。
上網 google 了好久，我實在是找不到 local 端可以測試的方法，用 google tag manager 去塞也不行。
只好做個測試頁面 `/google-adsense-test` 上 production 測試看看了，這些廣告如果出的來，至少我可以依樣畫葫蘆放到其他頁面去。
不會影響現有功能，無需測試

Feat: 測試 google adsense 廣告

---

src/components/ExperienceDetail/ExperienceDetail.module.css
src/components/ExperienceDetail/index.js

職場經驗單篇，加上 160x600 廣告
Note: /google-adsense-test 頁面我在下個 PR 再刪

Feat: 職場經驗單篇，加上 160x600 廣告

---

src/apis/interviewExperiencesApi.js
src/components/ShareExperience/InterviewForm/formCheck.js
src/components/ShareExperience/InterviewStepsForm/formCheck.js
src/components/ShareExperience/InterviewStepsForm/index.js
src/components/ShareExperience/utils.js
src/graphql/experience.js

新增面試經驗的 API ，換成 graphql API
- Back-end PR：https://github.com/goodjoblife/WorkTimeSurvey-backend/pull/663

refactor: change to use graphql api for POST interview experience

---

src/apis/workExperiencesApi.js
src/components/ShareExperience/InterviewForm/formCheck.js
src/components/ShareExperience/InterviewStepsForm/formCheck.js
src/components/ShareExperience/WorkExperiencesForm/formCheck.js
src/components/ShareExperience/WorkExperiencesForm/index.js
src/components/ShareExperience/utils.js
src/graphql/experience.js

[Refactor] Change to use graphql api for POST work experience

---

src/components/ShareExperience/CampaignTimeAndSalaryForm/index.js
src/components/ShareExperience/TimeSalaryForm/index.js

Merge dev into master

---

src/actions/experienceDetail.js
src/apis/auth.js
src/apis/experiencesApi.js
src/apis/jobTitleSearchApi.js
src/apis/timeAndSalaryApi.js
src/components/ShareExperience/common/JobTitle.js
src/graphql/auth.js
src/graphql/jobTitle.js
src/graphql/reply.js
src/graphql/timeAndSalary.js

換 Graphql API

---

src/components/ShareExperience/FormBuilderDemoForm/index.js
src/components/common/FormBuilder/QuestionBuilder/Checkbox.js
src/components/common/FormBuilder/QuestionBuilder/File.js
src/components/common/FormBuilder/QuestionBuilder/Radio.js
src/components/common/FormBuilder/QuestionBuilder/Rating.js
src/components/common/FormBuilder/QuestionBuilder/Text.js
src/components/common/FormBuilder/QuestionBuilder/TextArea.js
src/components/common/FormBuilder/QuestionBuilder/index.js
src/components/common/FormBuilder/index.js
src/components/common/FormBuilder/usePagination.js
src/routes.js

#845 #846
簡單的Demo頁面以及框架，方便之後推各自元件的PR和review。
完成功能之後會移除Demo頁面。
可幫忙確認元件Demo用法是否有誤，若有誤則提早調整，避免之後做錯。

[新版UI] Stage 1: Form builder template

---

src/components/ShareExperience/FormBuilderDemoForm/FormBuilderDemoForm.module.css
src/components/ShareExperience/FormBuilderDemoForm/index.js
src/components/common/FormBuilder/FormBuilder.module.css
src/components/common/FormBuilder/NavigatorBlock.js
src/components/common/FormBuilder/NavigatorBlock.module.css
src/components/common/FormBuilder/ProgressBlock.js
src/components/common/FormBuilder/ProgressBlock.module.css
src/components/common/FormBuilder/index.js

[新版表單UI] Stage 1: Navigator & Header & Footer

---

src/components/ExperienceDetail/BackToList.js
src/components/ExperienceDetail/index.js

Close #849  
首頁的單篇中的「返回列表」按鈕點進去會是舊的工作列表頁面
現在改為導回「職業」列表頁面

change index Return url

---

src/components/ExperienceDetail/index.js

`defaultBackToURL` 應該在 loaded status 才可以決定 (否則Error status會無法取出defaultBackToURL)

[Bugfix] 修正經驗defaultBackURL

---

public/ads.txt

feat: update ads.txt

---

src/components/common/FormBuilder/QuestionBuilder/Text.js
src/components/common/FormBuilder/QuestionBuilder/Text.module.css

#846
表單一：文字 css 修改
題號那邊不知道要怎麼模組化比較好 
必填紅色星號那個不知道這樣寫可以嗎

Form text css

---

src/components/ShareExperience/FormBuilderDemoForm/index.js
src/components/common/FormBuilder/FormBuilder.module.css
src/components/common/FormBuilder/index.js
src/components/common/FormBuilder/usePagination.js

#846 
把FormBuilder做成Modal，支援關閉的功能。
在close時會做reset (之後可以在reset之前呼叫callback)

[新版表單] Modal

---

src/components/common/FormBuilder/QuestionBuilder/File.js
src/components/common/FormBuilder/QuestionBuilder/File.module.css

#846  
edit form file css
before 
1.  description 內文模組化，不知道如何像設計師設計的一樣拆成 2 行分別修改 css 
2. 中間檔案的圖片不知道要去哪裡找

Form file css

---

src/components/common/FormBuilder/QuestionBuilder/Radio.js
src/components/common/FormBuilder/QuestionBuilder/Rating.js
src/components/common/FormBuilder/QuestionBuilder/Text.js
src/components/common/FormBuilder/QuestionBuilder/index.js
src/components/common/FormBuilder/index.js

[新版表單] 自動換頁

---

src/components/common/FormBuilder/AnimatedPager.js
src/components/common/FormBuilder/AnimatedPager.module.css
src/components/common/FormBuilder/FormBuilder.module.css
src/components/common/FormBuilder/ProgressBlock.module.css
src/components/common/FormBuilder/index.js

[新版UI] 換頁動畫

---

src/components/ShareExperience/FormBuilderDemoForm/FormBuilderDemoForm.module.css
src/components/ShareExperience/FormBuilderDemoForm/index.js
src/components/common/FormBuilder/FormBuilder.module.css
src/components/common/FormBuilder/QuestionBuilder/TextArea.js
src/components/common/FormBuilder/QuestionBuilder/index.js
src/components/common/FormBuilder/SubmissionBlock.js
src/components/common/FormBuilder/SubmissionBlock.module.css
src/components/common/FormBuilder/index.js
src/components/common/FormBuilder/useDraft.js

#846 
- 送出表單按鈕和onSubmit
- onChange時也會呼叫callback
- 關掉之後會resetDraft

[新版表單] 送出表單

---

src/components/common/FormBuilder/QuestionBuilder/Radio.js
src/components/common/FormBuilder/QuestionBuilder/Radio.module.css

#846  
Edit Form Radio CSS
before

Form radio css

---

src/components/common/FormBuilder/AnimatedPager.js
src/components/common/FormBuilder/QuestionBuilder/Text.js

#846 
1. TextInput Enter的時候要blur，否則可以一直按Enter到下一頁
1. handleRef only when node !== null
Before：在TextInput按Enter到下一頁後，可以繼續按Enter到下一頁
After：在TextInput按Enter到下一頁後，繼續按Enter無法到下一頁

[新版表單] Bugfix: Text input blurs on Enter

---

src/components/common/FormBuilder/QuestionBuilder/Rating.js
src/components/common/FormBuilder/QuestionBuilder/Rating.module.css

#846  
Form Rating CSS
before 
1.  按下去沒有變成黃色的不知道為什麼  QAQ 
2.  原設計稿，點擊做評分下面那個黃色的圖形，不知道要怎麼生產出來 QAQ

Form rating css

---

src/components/common/FormBuilder/NavigatorBlock.js
src/components/common/FormBuilder/NavigatorBlock.module.css
src/components/common/FormBuilder/QuestionBuilder/Checkbox.js
src/components/common/FormBuilder/QuestionBuilder/Checkbox.module.css
src/components/common/FormBuilder/QuestionBuilder/File.js
src/components/common/FormBuilder/QuestionBuilder/File.module.css
src/components/common/FormBuilder/QuestionBuilder/Radio.js
src/components/common/FormBuilder/QuestionBuilder/Radio.module.css
src/components/common/FormBuilder/QuestionBuilder/Rating.js
src/components/common/FormBuilder/QuestionBuilder/Rating.module.css
src/components/common/FormBuilder/QuestionBuilder/Text.js
src/components/common/FormBuilder/QuestionBuilder/Text.module.css
src/components/common/FormBuilder/QuestionBuilder/TextArea.js
src/components/common/FormBuilder/QuestionBuilder/TextArea.module.css
src/components/common/FormBuilder/QuestionBuilder/index.js
src/components/common/FormBuilder/SubmissionBlock.module.css
src/components/common/FormBuilder/TitleBlock.js
src/components/common/FormBuilder/TitleBlock.module.css
src/components/common/FormBuilder/index.js

#846 
1. Checkbox 樣式
1. 共用 `TitleBlock`
1. Radio & Rating 延遲換頁
1. 重構`button:disabled`
*一般優化*
*個別元件優化*

[新版表單] Checkbox + Other optimizations

---

src/components/common/FormBuilder/QuestionBuilder/Text.js

Close #871 
用onComposition避免中文輸入選字時按的Enter

[新版表單] Fix: Composition

---

src/components/common/FormBuilder/FormBuilder.module.css
src/components/common/FormBuilder/Scrollable.js
src/components/common/FormBuilder/Scrollable.module.css
src/components/common/FormBuilder/index.js

#846 
可捲動頁面增加白色漸層 (https://app.zeplin.io/project/5c316d528cc2d146a73dfc59/screen/5e5c481acd5a3567b367a898)
https://recordit.co/RXpSvEph4I

[新版表單] 可捲動頁面增加白色漸層

---

src/components/common/FormBuilder/QuestionBuilder/Rating.js
src/components/common/FormBuilder/QuestionBuilder/Rating.module.css

#846 
Rating的文字和hover效果
https://app.zeplin.io/project/5c316d528cc2d146a73dfc59/screen/5e5c4f6c8d27f0666e7f2049
http://localhost:3000/form-builder/demo?p=5

[新版表單] Rating文字和hover效果

---

src/components/common/PermissionBlock/BasicPermissionBlock.js
src/components/common/PermissionBlock/PermissionBlock.module.css
src/components/common/withExperimentParameters.js

製作一個 High Order Component ，目的是監聽 google optimize 給的參數，方便做 A/B testing。
詳細說明：
- google optimize 是一個非常方便的 A/B testing 工具，可以指定編輯某個頁面的 html, 插入 js & css
- 對於簡單的 UI 調整，可以直接用它給的工具，完全不需要改 code
- 而對於像權限區塊這種會根據狀況動態改變內容的 UI ，則可以用 js 把參數傳下去，讓 react render 出不同版本
- 我自己是習慣把參數傳到 `<div id="root">` 的 attributes 上面，然後再用 mutation observer 去監聽 attributes 的變化，當作 props 傳給 WrappedCompoment，如此就會觸發 re-render
文字簡化版，想看轉換率會不會提升
原始版：
A/B testing 簡單來說就是把使用者亂數分流，進到 B 組的使用者會看到不同的 UI ，進而測試指定目標（例如：轉換率），是否有因此提升，是改善 UX 最有效的方法之一

Feat: add withExperimentParameter HOC (for A/B testing)

---

src/components/ShareExperience/FormBuilderDemoForm/FormBuilderDemoForm.module.css
src/components/ShareExperience/FormBuilderDemoForm/index.js
src/components/common/FormBuilder/FormBuilder.module.css
src/components/common/FormBuilder/QuestionBuilder/Checkbox.js
src/components/common/FormBuilder/QuestionBuilder/File.js
src/components/common/FormBuilder/QuestionBuilder/Radio.js
src/components/common/FormBuilder/QuestionBuilder/Rating.js
src/components/common/FormBuilder/QuestionBuilder/Text.js
src/components/common/FormBuilder/QuestionBuilder/TextArea.js
src/components/common/FormBuilder/QuestionBuilder/index.js
src/components/common/FormBuilder/index.js

[新版表單] 整理prop types

---

src/components/ShareExperience/FormBuilderDemoForm/index.js
src/components/common/FormBuilder/FormBuilder.module.css
src/components/common/FormBuilder/NavigatorBlock.module.css
src/components/common/FormBuilder/QuestionBuilder/index.js
src/components/common/FormBuilder/SubmissionBlock.js
src/components/common/FormBuilder/SubmissionBlock.module.css
src/components/common/FormBuilder/TitleBlock.js
src/components/common/FormBuilder/index.js

#846 
1. Required 都答完了就 enable Submit
1. 最後一題必定 enable Submit (用Submit觸發檢查)
1. 最後一題的下一題按鈕消失，第一題的上一題按鈕也消失
1. `required`, `validator`, `warning` 因為是必定一起設定的項目，所以改成
```js
assert = [condition, message] // 參考 assert(condition, message)
```
1. 全部題目必填
1. 部分題目必填（圖為第三題之後都是選填）
http://localhost:3000/form-builder/demo

[新版表單] 調整觸發檢查流程

---

src/components/common/PermissionBlock/BasicPermissionBlock.js
src/containers/PermissionBlock/BasicPermissionBlockContainer.js

A/B testing 跑了快兩週，結果非常不錯，新的版本轉換率提升大約 50％ （3.32％ -> 4.86％
因此把文案換成新的版本

refactor: 權限區塊文案換新的版本

---

src/client.js
src/components/App/index.js
src/components/LandingPage/CallToActionBlock.js
src/components/ShareExperience/Entry.js
src/components/ShareExperience/InterviewForm/TypeForm.js
src/components/common/FormBuilder/index.js
src/components/common/FormBuilder/useDraft.js
src/components/common/PermissionBlock/BasicPermissionBlock.js
src/components/common/PermissionBlock/CallToLoginShareButton.js
src/components/common/ShareExpSection/index.js
src/constants/dataProgress.js

#892
- 把Modal放在App上，會由query.share來決定是否打開modal

[新版面試表單] 代換原本的表單成新版表單

---

src/components/ShareExperience/InterviewForm/TypeForm/index.js
src/components/common/FormBuilder/Modals/ConfirmModal.js
src/components/common/FormBuilder/Modals/styles.module.css
src/components/common/Modal.js

[新版表單] 確認關閉的取消

---

src/components/ExperienceDetail/Article/index.js

修復私訊原作者被擋住還是 render 的問題
Before：
After：

Hotfix: 修復私訊原作者按鈕

---

src/components/LaborUnionDetail/index.js
src/routes.js

Close #  
render  一個 hello world

add LaborUnionDetail/index.js

---

src/components/ShareExperience/common/TypeFormFooter.module.css
src/components/common/FormBuilder/AnimatedPager.module.css
src/components/common/FormBuilder/FormBuilder.module.css
src/components/common/FormBuilder/ProgressBlock.module.css
src/components/common/FormBuilder/QuestionBuilder/Checkbox/private.js
src/components/common/FormBuilder/QuestionBuilder/Checkbox/private.module.css
src/components/common/FormBuilder/QuestionBuilder/Date.js
src/components/common/FormBuilder/QuestionBuilder/Date.module.css
src/components/common/FormBuilder/QuestionBuilder/Rating.js
src/components/common/FormBuilder/QuestionBuilder/Rating.module.css
src/components/common/FormBuilder/QuestionBuilder/SelectText.js
src/components/common/FormBuilder/QuestionBuilder/SelectText.module.css
src/components/common/FormBuilder/QuestionBuilder/Text.js
src/components/common/FormBuilder/QuestionBuilder/Text.module.css
src/components/common/FormBuilder/QuestionBuilder/TextArea.js
src/components/common/FormBuilder/QuestionBuilder/TextArea.module.css
src/components/common/FormBuilder/QuestionBuilder/TextList.js
src/components/common/FormBuilder/QuestionBuilder/TextList.module.css
src/components/common/FormBuilder/QuestionBuilder/index.js
src/components/common/FormBuilder/QuestionBuilder/styles.module.css
src/components/common/FormBuilder/index.js

#894
新版表單 RWD
有兩個 bug 
1. 頁面 1-3、10 如果按照設計稿需往下移置中，但其他多選題也會跟著全部往下，所以暫時沒有調整 
2. 縮放頁面會跳出動畫的 bug ，但是不知道為什麼

新版表單 RWD verson1

---

src/components/ExperienceDetail/Article/Article.module.css
src/components/ExperienceDetail/Article/index.js
src/components/common/GradientMask/GradientMask.module.css
src/components/common/GradientMask/index.js
src/components/common/withExperimentParameters.js
src/constants/hideContent.js
src/hooks/useExperimentParameters.js
src/utils/stringUtil.js

職場經驗單篇的部分，加上總字數。
並且做 A/B testing ，看對轉換率是否有影響。
by commit

Feat: 文章總字數測試

---

src/components/App/Header/index.js
src/components/common/LoginModal/index.js
src/components/common/permission-context/withPermission.js
src/constants/dataProgress.js
src/hooks/usePermission.js

Close #925 
修正AB連結使用useShareLink
為了使用hooks所以順帶重構App/Header

[新版表單] 修正AB連結

---

package.json
src/components/CompanyAndJobTitle/CompanyAndJobTitleWrapper.js
src/components/CompanyAndJobTitle/CompanyAndJobTitleWrapper.module.css
src/components/CompanyAndJobTitle/Overview/Overview.js
src/components/CompanyAndJobTitle/Overview/Overview.module.css
src/components/CompanyAndJobTitle/index.js
src/components/ExperienceDetail/index.js
src/components/common/GoogleAdUnit/index.js
src/config/index.js
yarn.lock

廣告版位 v2
[公司頁手機版](https://user-images.githubusercontent.com/3805975/86534861-86c92d00-bf0e-11ea-9533-0b4659de2b5c.png)
[公司頁電腦版](https://user-images.githubusercontent.com/3805975/86534855-7dd85b80-bf0e-11ea-982b-76eebdfe1532.png)
[職場經驗單篇右邊的廣告](https://user-images.githubusercontent.com/3805975/86535146-b711cb00-bf10-11ea-831b-3e217664fa4a.png)
DFP 是 google ad manager 的前稱，react-dfp 就是協助在 react 上面設置 google ad manager 的套件
現在大部分 google adsense 廣告改用 google ad manager 管理 
Note: 職業頁，桌機版，最下方有廣告（這個暫時出不來，先不理他）

Feat: 用 google ad manager 管理廣告

---

src/components/ShareExperience/InterviewForm/TypeForm/index.js

一頁一題式的面試表單，忘記埋事件，難怪 A/B testing 結果都是 0 ，此 PR 埋之

Feat: 一頁一題式表單埋事件

---

src/components/ShareExperience/InterviewForm/TypeForm/constants.js

[新版表單] 修正年資選項

---

src/components/ShareExperience/InterviewForm/TypeForm/index.js
src/components/ShareExperience/InterviewForm/TypeForm/utils.js
src/components/common/FormBuilder/QuestionBuilder/Text.js
src/components/common/FormBuilder/Scrollable.js
src/components/common/FormBuilder/index.js

Close #924 
1. 新增薪資、面試結果文字、敏感問題的限制&警告文字
2. onPageChange(page)：發生頁數變化、表單初始化時被觸發。
3. 修正一些bug

[新版經驗表單] 優化&修正

---

src/components/common/PermissionBlock/CallToLoginShareButton.js
src/reducers/laborRights.js
src/reducers/popularCompanyAverageSalary.js
src/reducers/popularExperiences.js
src/reducers/popularJobTitleSalaryDistribution.js
src/utils/createReducer.js
src/utils/eventBasedTracking/user.js

Close #946 
目前logout會重置所有state，但是部分state不需要在logout重置（比如：小教室、最新心得）
順帶修掉一些warning & error

登出不重置部分state

---

src/components/App/Header/Top/index.js
src/components/App/Header/index.js
src/components/common/PermissionBlock/BasicPermissionBlock.js
src/components/common/PermissionBlock/CallToLoginShareButton.js

Fix PropTypes

---

src/components/ExperienceDetail/MessageBoard/index.js

目前的留言區，成功留言後並不會清掉文字方塊的內容
這個PR自動清除文字方塊，並且滾動至最新的留言 -- 也就是剛成功留的言

[經驗單篇] 留言區加強

---

src/components/CompanyAndJobTitle/WorkExperiences/ExperienceEntry.js
src/components/CompanyAndJobTitle/WorkExperiences/WorkExperiences.module.css

[公司職稱頁面] 修正工作經驗區塊樣式

---

.circleci/config.yml
.github/workflows/main.yml
docker/Dockerfile

將 nodejs 調整至 LTS 12，Current 14 作為測試版本

Change minimal nodejs version to 12

---

src/components/App/index.js
src/components/ExperienceDetail/Article/ReactionZone.js
src/components/Root.js
src/components/common/LoginModalContextProvider/index.js
src/contexts/LoginModalContext.js
src/hooks/login/useLogin.js

將登入表單放在App
由Context決定是否開啟
這樣一來useLogin就不需要回傳loginModal

由Context決定是否開啟登入Modal

---

src/components/App/Header/index.js
src/components/Me/index.js

Close #964  
#960 漏掉使用useLogin的use cases
這個PR修復之

修復Header login

---

src/components/common/FormBuilder/SubmissionBlock.js

1. 面試經驗表單的登入，改成用新的 useLogin
2. submit 按鈕下方條款多加一個發文留言規則

Refactor: 面試經驗表單 login 方式更新＋加上發文留言規則

---

package.json
src/components/ShareExperience/InterviewForm/TypeForm/TypeForm.test.js
src/utils/testUtils.js
yarn.lock

- 嘗試用 React-Testing-Library 做 react component 的 unit testing
- [React-Testing-Library](https://testing-library.com/docs/react-testing-library/intro)  是一個可以協助開發者測試 react component 的套件，可搭配 jest runner 跑
此外，也有 [React-Hook-Testing-Library](https://github.com/testing-library/react-hooks-testing-library) 可以搭配使用，用來測試 react hook 
- 為什麼沒有選擇 [enzyme](https://github.com/enzymejs/enzyme) ？  因為目前 enzyme 的 shallow rendering 尚未支援 react hook 
- 先簡單看 React-Testing-Library 的介紹
- 看 2361567 ，這個 commit 的目的在於把一些 global 的 providers 引進來，讓 component 可以正常運作
- 看 8a074cc ，做了第一個最簡單的 component unit test

Feat: 加入 React-Testing-Library 做 component unit testing

---

src/actions/permission.js
src/pages/MyUnlockedContentsPage/MyUnlockedContentsPage.container.js
src/pages/MyUnlockedContentsPage/MyUnlockedContentsPage.js
src/pages/MyUnlockedContentsPage/index.js
src/reducers/index.js
src/reducers/permission.js
src/selectors/permissionSelector.js

- 把 points & 解鎖資料放到 redux ，因為之後 header & 很多頁面都會用到

feat: add redux 'permission' for unlocked content and points

---

src/actions/permission.js
src/components/App/Header/Header.module.css
src/components/App/Header/index.js
src/components/Company/CompanyPageProvider.js
src/components/CompanyAndJobTitle/InterviewExperiences/InterviewExperiences.js
src/components/CompanyAndJobTitle/InterviewExperiences/index.js
src/components/CompanyAndJobTitle/Overview/Overview.js
src/components/CompanyAndJobTitle/Overview/index.js
src/components/CompanyAndJobTitle/WorkExperiences/WorkExperiences.js
src/components/CompanyAndJobTitle/WorkExperiences/index.js
src/components/ExperienceDetail/MoreExperiencesBlock/index.js
src/components/ExperienceDetail/index.js
src/components/JobTitle/JobTitlePageProvider.js
src/components/common/permission-context/PermissionContext.js
src/components/common/permission-context/PermissionContextProvider.js
src/hooks/usePermission.js
src/pages/MyUnlockedContentsPage/MyUnlockedContentsPage.js
src/selectors/permissionSelector.js
src/utils/permissionUtil.js

1. 改寫 usePermission hook 
- 其中，firstTimeView 這個變數是放在 PermissionContext 裡面，原因是如果放 redux 裡面，browser 端的 store 會被 server side 的 store 覆蓋掉，但我想要在 local 端再重新檢查一次 localStorage，確認用戶是不是第一次上站
- 其他與權限機制相關的變數，都放在 store 裡面
2. 我解鎖的資料頁、職場經驗單篇、公司/職業的工作心得與面試心得區塊、header ，都已經改用新的 usePermission，會一筆一筆檢查是否有權限。但是，薪資工時區塊還沒做，之後的 PR 會改。

Refactor: 權限機制的檢查方式

---

src/constants/dataProgress.js

feat: update goal number to 50000

---

src/components/common/facebook/Facebook.js

feat: upgrade fb sdk to v10.0

---

src/components/TimeAndSalary/common/injectHideContentBlock.js
src/components/common/PermissionBlock/CallToLoginShareButton.js

Close #991 
修正Time-and-salary分享按鈕無作用的bug
- 有哪些文件需要被更新嗎？ No 
找到這種鎖住的資訊，點擊後跳出的分享畫面

修正分享按鈕無作用的錯誤(#991)

---

src/components/ExperienceDetail/Article/ArticleInfo.js

[Hotfix] 修復 經驗頁 顯示月份 問題

---

src/components/Buy/SubscriptionsSection/SubscriptionsSection.module.css
src/components/PlanPage/CardSection.js
src/components/PlanPage/CardSection.module.css
src/components/PlanPage/PlanCard.js
src/components/PlanPage/PlanCard.module.css
src/components/PlanPage/PlanPage.module.css
src/components/PlanPage/helpers.js
src/components/PlanPage/index.js
src/components/common/RoundCard/RoundCard.module.css

Close #  
修改至設計稿
**dWeb**
**mWeb**
https://user-images.githubusercontent.com/8898129/204091797-78578145-65f5-408e-a4b8-05701a38fc2a.mp4

Plan page styling

---

src/components/PlanPage/CardSection.js
src/components/PlanPage/index.js

Close #  
- Back-end PR：
https://user-images.githubusercontent.com/8898129/207589740-4a87bfa3-bd1e-4644-a799-78dcca6f3f46.mp4

feat: Plans Page to Buy Page

---

src/components/Buy/SubscriptionsSection/index.js

#1009
讀取 `?sku_id=` 決定初始方案
http://localhost:3000/plans 選擇不同方案，連結到付款頁面時會選取對應的方案
https://user-images.githubusercontent.com/7566586/207902339-c3409d6c-3a5c-4e94-9a04-1d7511b90c72.mov

[付款頁面] 透過 location.search?sku_id= 決定初始方案

---

src/actions/payment.js
src/apis/payment.js
src/components/BuyResultPage/PaymentResult/index.js
src/components/PlanPage/PlanCard.js
src/graphql/payment.js

Close #1012 
串接Buy Result Page 的APIs
https://user-images.githubusercontent.com/8898129/217863417-0ded1478-8d76-47a6-8842-644eb6d645eb.mp4

feat: Buy Result Page API Integration

---

.eslintrc.js
jsconfig.json
package.json
src/components/Buy/PaymentSection/index.js
src/components/Buy/SubscriptionsSection/SubscriptionPlan.js
src/components/Buy/SubscriptionsSection/SubscriptionPlanCollection.js
src/components/Buy/SubscriptionsSection/index.js
src/components/Buy/index.js
src/graphql/payment.js
src/razzle-plugins/alias.js

1. 讀取 #1057 的subscription plans
2. 加上 actions 的 path alias 方便以後拿
http://localhost:3000/buy?skuId=plan_30_days

[購買頁面] 讀取Store的SubscriptionPlans

---

src/components/App/Header/Header.module.css
src/components/Buy/LoginSection/LoginSection.module.css
src/components/Buy/LoginSection/index.js
src/components/Buy/PaymentSection/index.js
src/components/common/Login/FacebookLoginButton.js
src/components/common/Login/GoogleLoginButton.js
src/components/common/Login/LoginButton.module.css
src/components/common/PermissionBlock/LoginModal.js
src/components/common/PermissionBlock/PermissionBlock.module.css

Close #1081   
Close #1082 
* 增加底部Margin
* 以是否登入判斷秀出表單或是Login Action Section
* 新增Login Action Section
* 修Header 中「解鎖方案」非預期排版的問題
**Bottom Margin**
https://user-images.githubusercontent.com/8898129/230638831-f719717c-30be-4dce-adb2-99b91340efd1.mp4
**Login Logic**
https://user-images.githubusercontent.com/8898129/230638844-5e53b9b8-a4ec-4f73-b072-50af44787732.mp4
**Responsive**
https://user-images.githubusercontent.com/8898129/230638852-4f90d216-a604-4506-8642-2a4215972474.mp4
**解鎖方案**
https://user-images.githubusercontent.com/8898129/230705206-5a6a6d07-319d-4f8c-9082-5d7906049159.mp4

Fix: buy page issues

---

src/components/CompanyAndJobTitle/TimeAndSalary/WorkingHourTable.js

#1007
WorkingHourTable 是舊版寫法，順便改寫成 functional
建議用 Hide Whitespace 看

改寫 WorkingHourTable 成 functional component

---

src/components/common/PermissionBlock/LoginToUnlock.js
src/components/common/PermissionBlock/PermissionBlock.module.css

#1016  
Ref: https://github.com/goodjoblife/GoodJobShare/issues/1016#issuecomment-1510518058
修正 Login Modal style
尚未登入狀況下，在以下網址按鎖頭
http://localhost:3000/companies/%E7%9F%BD%E5%93%81%E7%B2%BE%E5%AF%86%E5%B7%A5%E6%A5%AD%E8%82%A1%E4%BB%BD%E6%9C%89%E9%99%90%E5%85%AC%E5%8F%B8/overview

[登入並解鎖視窗] 樣式調整

---

src/components/CompanyAndJobTitle/TimeAndSalary/WorkingHourTable.js
src/components/TimeAndSalary/common/injectHideContentBlock.js
src/components/TimeAndSalary/common/injectHideContentBlock.module.css
src/components/common/PermissionBlock/PermissionBlock.module.css

Close #1007
更新樣式
尚未登入狀態下，盡到下列頁面，檢查鎖頭
http://localhost:3000/companies/%E7%9F%BD%E5%93%81%E7%B2%BE%E5%AF%86%E5%B7%A5%E6%A5%AD%E8%82%A1%E4%BB%BD%E6%9C%89%E9%99%90%E5%85%AC%E5%8F%B8/overview

[薪資解鎖] 樣式更新

---

.github/docker-compose-production.yml
src/utils/sentryUtil.js

Close #
- disable sentry to send error event by default 
- now we already run out of quota
可參考 https://github.com/goodjoblife/GoodJobShare/tree/test/disable-sentry 這個 branch 做測試

Feat: disable sentry by default

---

.github/docker-compose-stage.yml
src/config/index.js

feat: fix #1112

---

src/components/Buy/PaymentSection/useForm.js

Close #1097
修改空 "paymentUrl" 的跳轉網址
https://github.com/goodjoblife/GoodJobShare/assets/7566586/283cd5be-54e4-4bd2-af11-7b7cb1c8f93d
輸入卡號：
5451 4178 2523 0575

修正非3D驗證的跳轉網址

---

.github/docker-compose-dev2.yml
.github/workflows/main.yml

feat: dev site with tappay prod key

---

src/components/Buy/PaymentSection/index.js
src/components/Buy/PaymentSection/useForm.js

Close #1096 
1. 以formState 來表達表單狀態
2. 移除沒用到的state
3. 隱藏「設為主要付款」checkbox
https://github.com/goodjoblife/GoodJobShare/assets/8898129/fd4456d1-a1bf-4154-ac91-9dd8a883b92d

feat: 處理付款頁面「正處理」的表單狀態

---

package.json
src/components/Buy/SubscriptionsSection/Captain.js
src/components/Buy/SubscriptionsSection/index.js
src/utils/dateUtil.js
yarn.lock

Close #1131 
修復 /buy 頁面的資訊錯誤：
- 有效時間
- 資料數
- 條款網址

fix: /buy page 解鎖範圍資料數、方案使用時間計算、policy 網址

---

src/components/Buy/SubscriptionsSection/SubscriptionsSection.module.css
src/components/PlanPage/PlanCard.module.css

Close #1122
把PayCard的style修好
||Plans|Buy|
|-|-|-|
|電腦版|<img width="1840" alt="截圖 2023-06-14 下午10 29 43" src="https://github.com/goodjoblife/GoodJobShare/assets/7566586/532e81e9-ca0a-43b4-9528-f0b06793658b">|<img width="1840" alt="截圖 2023-06-14 下午10 29 41" src="https://github.com/goodjoblife/GoodJobShare/assets/7566586/68195055-f4da-42f8-9581-fdd0c5fe6c5b">|
|手機版|<img width="628" alt="截圖 2023-06-14 下午10 29 37" src="https://github.com/goodjoblife/GoodJobShare/assets/7566586/cae75712-8678-498d-8fa4-b48ff7319e4d">|<img width="628" alt="截圖 2023-06-14 下午10 29 39" src="https://github.com/goodjoblife/GoodJobShare/assets/7566586/4b51a8d7-7d60-40f0-8ed3-57b6dcc3ba89">|
http://localhost:3000/plans
http://localhost:3000/buy
切換電腦版/手機版

[方案頁面] 修正 style

---

src/components/common/button/ButtonSubmit.js
src/components/common/button/WhyFacebookAuth.js

Close #1128
Close #1129
舊版表單登入時打API會有問題。
改寫成hook並用現有的登入方法即可。
一併解決舊版只能以facebook登入的問題。
https://github.com/goodjoblife/GoodJobShare/assets/7566586/978135a4-dcfa-4465-86f4-c2b34446b84d
https://github.com/goodjoblife/GoodJobShare/assets/7566586/1126f027-79cf-4563-8578-bfc24f80e509
尚未登入下，填寫以下表單並登入送出
http://localhost:3000/share/work-experiences
http://localhost:3000/share/time-and-salary

[工作/薪資] 修正登入上傳

---

.github/docker-compose-production.yml

This feature pushes to dev,
when dev merge to master, it will effect
related to #1107

feat: Production tappay key

---

src/components/BuyResultPage/PaymentResult/Failure.js

Close #1094
在購買失敗頁面新增「再試一次」按鈕
https://github.com/goodjoblife/GoodJobShare/assets/7566586/ba005ea6-61b6-4c46-a9b5-09f4766b69c9
套用以下 diff 並至 http://localhost:3000/buy/result/123
```diff
diff --git a/src/components/BuyResultPage/PaymentResult/index.js b/src/components/BuyResultPage/PaymentResult/index.js
index 886ca6f..2603a71 100644
--- a/src/components/BuyResultPage/PaymentResult/index.js
+++ b/src/components/BuyResultPage/PaymentResult/index.js
@@ -22,18 +22,8 @@ const PaymentResult = ({ paymentRecordBox, paymentRecordId }) => {
return <Success expiredAt={new Date(expiredAt)} />;
}
-  if (buyStatus === buyStatusMap.inProgress) {
-    return (
-      <InProgress
-        paymentRecordId={paymentRecordId}
-        fetchingStatus={fetchingStatus}
-      />
-    );
-  }
-
-  const { publicId …
```

[購買結果頁面] 新增"再試一次"按鈕

---

src/components/PlanPage/PlanCard.module.css

fix: Plan Card style

---

src/actions/experience.js

refactor: minor fix

---

src/components/ShareExperience/InterviewForm/index.js
src/components/ShareExperience/TimeSalaryForm/index.js
src/components/ShareExperience/WorkExperiencesForm/index.js
src/hooks/experiments/useShareLink.js
src/utils/hotjarUtil.js

feat: random to different forms

---

src/components/ShareExperience/InterviewForm/TypeForm/index.js
src/components/ShareExperience/InterviewForm/index.js
src/components/ShareExperience/TimeSalaryForm/index.js
src/components/ShareExperience/WorkExperiencesForm/index.js

- 修復上個 PR 的 hotjar event 
- 三種 form 多送開始填寫的 GA 事件

feat: fix hotjar tracking, tracking form start

---

src/components/ShareExperience/InterviewForm/TypeForm/index.js

- 修復原本送 enter_interview_form 時間點不對的問題，原本即使表單沒開也送（基本上就是一進網站就送）

fix: enter interview form timing

---

src/components/CompanyAndJobTitle/utils.js
src/utils/dateUtil.js

Related to https://github.com/goodjoblife/GoodJobShare/pull/1184#discussion_r1407900510
修改經驗頁面的麵包屑標題！
http://localhost:3000/experiences/6500039a35ddcb001398dc86

[面試經驗] 更新麵包屑標題

---

src/components/ShareExperience/InterviewForm/TypeForm/index.js
src/components/ShareExperience/InterviewForm/index.js
src/components/ShareExperience/InterviewStepsForm/index.js
src/constants/gaConstants.js
src/hooks/experiments/useShareLink.js
src/routes.js

GoodJob 曾經有三種面試表單（一頁全部題目式、三頁式、一頁一題式），我想測試不同表單的轉換率是否有差別

Feat: interview form ab testing

---

src/components/ShareExperience/InterviewForm/formCheck.js
src/components/ShareExperience/InterviewForm/formCheck.test.js
src/components/ShareExperience/InterviewForm/index.js
src/components/ShareExperience/InterviewStepsForm/Step3.js
src/components/ShareExperience/common/Sections.js

正在做面試經驗的三種表單 AB testing ，為了求公平比較，將提示文案、字數要求拉平

feat: 面試經驗三種表單 A/B testing 拉平要求

---

src/components/ShareExperience/common/Sections.js

feat: better hint

---

src/components/ShareExperience/InterviewForm/TypeForm/index.js
src/components/ShareExperience/InterviewForm/formCheck.js
src/components/ShareExperience/InterviewStepsForm/Step3.js
src/components/ShareExperience/common/SectionEle.js
src/components/ShareExperience/common/SectionEle.module.css
src/components/ShareExperience/common/SectionEleContent.js
src/components/ShareExperience/common/Sections.js

讓三種面試經驗表單的字數提示體驗一致，讓 A/B testing 更公平

Feat: 三種表單字數提示一致

---

src/components/ShareExperience/InterviewForm/TypeForm/index.js
src/components/ShareExperience/InterviewForm/index.js
src/components/ShareExperience/InterviewStepsForm/index.js
src/components/ShareExperience/utils.js
src/hooks/experiments/useShareLink.js
src/utils/GAUtils.js

- 在上傳面試資料時，多上傳一些追蹤資訊
- form_type：表單的種類，共三種
- ga_user_pseudo_id：GA 在 device 上的 user id ，用於算多少使用者
- Back-end PR：https://github.com/goodjoblife/WorkTimeSurvey-backend/pull/911

feat: send extra data while submitting interview form

---

src/components/ShareExperience/InterviewForm/TypeForm/index.js
src/components/ShareExperience/common/SubmittableFormBuilder.js

[面試經驗] 取出可共用的上傳元件

---

src/components/ShareExperience/questionCreators.js
src/components/common/FormBuilder/QuestionBuilder/index.js
src/components/common/FormBuilder/index.js

#1195
原本的question type是自由字串，改成常數

[面試表單] 常數化 QUESTION_TYPE

---

src/components/ShareExperience/common/SubmittableFormBuilder.js
src/components/common/FormBuilder/index.js

#1195
整理 SubmittableFormBuilder 以利後續修改，包括：
1. methods 整理出來
2. prop types 補上

[面試經驗] 整理 SubmittableFormBuilder

---

src/components/App/index.js
src/components/ShareExperience/TimeSalaryForm/TypeForm.js
src/components/ShareExperience/TimeSalaryForm/index.js
src/components/ShareExperience/common/SubmittableFormBuilder.js
src/components/ShareExperience/utils.js
src/components/common/FormBuilder/index.js
src/components/common/ShareExpSection/index.js
src/config/index.js
src/constants/gaConstants.js
src/hooks/experiments/useShareLink.js

薪資表單 A/B testing 
- variant 1: 原本一頁式  (34%)
- variant 2: 一頁一題式 (33%)
- variant 3: 一頁一題式但沒有 progress bar (33%)
- Back-end PR： https://github.com/goodjoblife/WorkTimeSurvey-backend/pull/926
variant 1
variant 2
variant 3

Feat: salary form A/B test

---

src/components/Company/CompanyPageProvider.js
src/components/CompanyAndJobTitle/Overview/Helmet.js
src/components/CompanyAndJobTitle/Overview/Overview.js
src/components/CompanyAndJobTitle/utils.js
src/components/JobTitle/JobTitlePageProvider.js
src/components/TimeAndSalary/SearchScreen/urlBuilder.js
src/components/TimeAndSalary/common/formatter.js
src/constants/companyJobTitle.js

refactor: use overview page and company, job landing page

---

src/apis/experiencesApi.js
src/components/ExperienceDetail/hooks/useToggleLike.js
src/graphql/experience.js

發現放了1年的 commit ... rebase 後開個 PR XD

refactor: Experience like change to graphql api

---

src/components/App/index.js
src/components/common/ShareExpSection/index.js
src/components/common/ShareExpSection/shareLinkTo.js
src/components/common/StaticHelmet/index.js
src/hooks/experiments/useShareLink.js

收攏所有表單的 link，減少 typo && 方便 A/B testing

refactor: share link use generateTo

---

.github/workflows/update.yml

Allow click of Run workflow to sync dev to newest master commit

feature: github action to sync dev with fast forward merge

---

src/hooks/experiments/useShareLink.js

feat: 50% salary & 50% interview

---

README.md

update npm run build

---

src/apis/timeAndSalaryApi.js
src/components/common/form/TextInput/SearchTextInput.js

Close #1241 #1242 #1243
移除舊版 /workings/companies/search
改用 Query.search_companies
|header|![截圖 2024-04-09 晚上10 11 14](https://github.com/goodjoblife/GoodJobShare/assets/7566586/411362a6-ab35-4214-9b35-d7e54ba958e3)|
|-|-|
|CTA|![截圖 2024-04-09 晚上10 04 53](https://github.com/goodjoblife/GoodJobShare/assets/7566586/730ced53-9e11-4462-bad2-16cfb6614bc1)|
|底部CTA|![截圖 2024-04-09 晚上10 11 22](https://github.com/goodjoblife/GoodJobShare/assets/7566586/35946f84-200b-4340-9b74-48d0160fb599)|

[API] 移除 /workings/companies/search

---

src/components/common/facebook/Facebook.js

feat: upgrade facebook SDK to v19.0

---

src/components/App/Footer/index.js

Close #  
- 解決 FB 商家驗證問題
- Back-end PR：

hotfix: add name in footer for FB business verification

---

src/components/Annoucement/index.jsx
src/components/App/index.js

hotfix: website announcement for fb login issue

---

src/components/Me/SubscriptionsPage.js
src/components/Me/subscriptionUtils.js
src/constants/payment.js
src/constants/subscription.js
src/graphql/payment.js

fix: subscriptions wording fix

---

src/components/CompanyAndJobTitle/utils.js
src/components/ExperienceDetail/Article/ArticleInfo.js
src/components/ExperienceDetail/Heading/index.js
src/components/ExperienceDetail/experienceSelector.js
src/graphql/experience.js

Close #1245
Close #1275
1. 標題使用 original company name
2. 移除 breadcrumb 第五層

[經驗頁面] 使用 original company name

---

src/components/ShareExperience/questionCreators.js

Close #1218  
將一頁一題式的最後一題資料數量改為動態更新

[一頁一題表單] 動態更新資料數量

---

src/components/ShareExperience/CompanyAutoCompleteItem.js
src/components/ShareExperience/CompanyAutoCompleteItem.module.css
src/components/ShareExperience/questionCreators.js
src/components/common/FormBuilder/QuestionBuilder/Text.js
src/graphql/timeAndSalary.js

[表單] 公司搜尋加上統一編號

---

src/actions/company.js
src/actions/jobTitle.js
src/components/CompanyAndJobTitle/CompanyAndJobTitleWrapper.js
src/graphql/company.js
src/graphql/jobTitle.js
src/selectors/companyAndJobTitle.js

Close #1244
在 CompanyAndJobTitleWrapper 統一比對 pageName 和 companyName / jobTitle，發現不同的時候，使用 Redirect 進行轉址。
https://github.com/goodjoblife/GoodJobShare/assets/7566586/0dc5ca1d-c6da-48ee-a37e-e723f127e6d5
- http://localhost:3000/companies/台積電
- 應轉址為 http://localhost:3000/companies/台灣積體電路製造股份有限公司
- http://localhost:3000/companies/台積電/salary-work-times
- 應轉址為 http://localhost:3000/companies/台灣積體電路製造股份有限公司/salary-work-times
- http://localhost:3000/companies/台積電/work-experiences
- 應轉址為 http://localhost:3000/companies/台灣積體電路製造股份有限公司/work-experiences
- http://localhost:3000/companies/台積電/interview-experiences
- 應轉址為 http://localhost:3000/companies/台灣積體電路製造股份有限公司/interview-experiences

[公司頁面] 301轉址至 canonical URL

---

src/actions/timeAndSalarySearch.js
src/components/CompanyAndJobTitle/IndexPage/index.js
src/components/TimeAndSalary/SearchScreen/SearchScreen.js
src/components/TimeAndSalary/SearchScreen/WorkingHourBlock.js
src/components/TimeAndSalary/SearchScreen/WorkingHourBlock.module.css
src/graphql/company.js
src/graphql/timeAndSalary.js

Close #1247 
Close #1273
Close #1274 
在公司列表新增統一編號，以及更新資料數量

[公司列表] 新增統一編號與數量

---

src/components/LaborRightsSingle/MarkdownParser.module.css

Close #585
小教室的內文有連結，因為沒有換行而撐大了 container 也撐大了圖片
這個 PR 補上了 break-word
|Before|After|
|-|-|
|![截圖 2024-06-09 晚上9 02 10](https://github.com/goodjoblife/GoodJobShare/assets/7566586/d589ce9f-a54f-4634-9b05-0116732dc601)|![截圖 2024-06-09 晚上9 00 31](https://github.com/goodjoblife/GoodJobShare/assets/7566586/70780315-c5c6-4a82-b4fa-414788b183c9)|

[小教室] 修正跑版

---

src/apis/timeAndSalaryApi.js
src/graphql/timeAndSalary.js

follow #1308, found some api doesn't used

chore: remove unused api/action

---

src/components/CompanyAndJobTitle/WorkExperiences/ExperienceEntry.js
src/graphql/jobTitle.js

Close #1330 
補上缺漏的 originalCompanyName

[職稱頁面] 卡片補上 originalCompanyName

---

src/graphql/experience.js

Close #1338  
As title
|Before|After|
|-|-|
|![截圖 2024-06-18 晚上10 22 52](https://github.com/goodjoblife/GoodJobShare/assets/7566586/ed2a32e8-0b19-460d-bcf3-12e1c55f7244)|![截圖 2024-06-18 晚上10 21 10](https://github.com/goodjoblife/GoodJobShare/assets/7566586/ddb1226a-4b10-45eb-af9d-4c182f6adb86)|

[經驗單篇] 在更多經驗區塊加上 originalCompanyName

---

src/graphql/timeAndSalary.js

Close #1334 
仿照公司列表，秀 dataCount
https://github.com/goodjoblife/WorkTimeSurvey-backend/issues/1026

[職稱搜尋] 補 dataCount

---

src/components/ExperienceDetail/MoreExperiencesBlock/index.js

Close #1344  
將更多經驗的標題改為 originalCompanyName
|Before|After|
|-|-|
|![畫面擷取於 2024-06-19 21 48 04](https://github.com/goodjoblife/GoodJobShare/assets/7566586/045201c1-597f-4b66-ad68-14b86fa92297)|![畫面擷取於 2024-06-19 21 47 43](https://github.com/goodjoblife/GoodJobShare/assets/7566586/75fd1140-f6bf-45f7-ae62-2c3a8e16936c)|

[經驗單篇] 更多經驗區塊改為 originalCompanyName

---

src/actions/timeAndSalarySearch.js
src/apis/timeAndSalaryApi.js
src/components/ShareExperience/questionCreators.js
src/graphql/timeAndSalary.js

Close #1341
代換表單的公司自動完成 API
帶入 `hasData:false` 取得包含沒資料的公司名稱
- Back-end PR：

[表單] 自動完成抓取包含沒資料的公司名稱

---

src/components/ShareExperience/common/CompanyQuery.js
src/components/common/form/TextInput/SearchTextInput.js

Close #1341 
還有首頁的搜尋和舊版工作心得表單需要加上 `hasData`
|首頁搜尋|工作心得表單|
|-|-|
|![Screenshot 2024-06-20 at 3 41 44 PM](https://github.com/goodjoblife/GoodJobShare/assets/7566586/83855e3a-9ac1-40f3-a910-de63ea45b870)|![Screenshot 2024-06-20 at 3 41 53 PM](https://github.com/goodjoblife/GoodJobShare/assets/7566586/943965a7-5f96-438e-88d5-ffd58aed372a)|

[首頁搜尋][工作心得表單] 修復 hasData

---

src/components/ShareExperience/common/CompanyQuery.js
src/components/common/form/TextInput/SearchTextInput.js

Close #1272  
替頂部搜尋和公司心得表單的公司搜尋加上統一編號

[公司自動完成] 補上統一編號

---

src/components/ShareExperience/common/CompanyQuery.js

Close #1360  
舊版的 autocomplete 介面不同，修復使用方法
https://github.com/goodjoblife/GoodJobShare/assets/7566586/a5f9f6a6-d69f-4e1a-b025-24500686c01b

[工作表單] 修復公司名稱自動完成

---

src/apis/experiencesApi.js
src/components/CompanyAndJobTitle/InterviewExperiences/ExperienceEntry.js
src/components/ShareExperience/AutoCompleteItem.js
src/components/ShareExperience/AutoCompleteItem.module.css
src/graphql/experience.js

Close #1331
將統編直接接在公司名稱後面
|Before|After|
|-|-|
|![截圖 2024-06-26 晚上10 23 20](https://github.com/goodjoblife/GoodJobShare/assets/7566586/4474f06b-ac9a-4869-bc5c-1d11a07fff9c)|![截圖 2024-06-26 晚上10 23 05](https://github.com/goodjoblife/GoodJobShare/assets/7566586/90f51dcd-123a-40b5-b293-b4595b94db50)|

[公司自動完成] 修改統編樣式

---

src/apis/experiencesApi.js

#1362 
修正 `data.experiencd` 為 `null` 的情況，不應做解析

[經驗單篇] 修正無經驗的頁面

---

src/graphql/auth.js
src/graphql/company.js
src/graphql/emailVerification.js
src/graphql/experience.js
src/graphql/jobTitle.js
src/graphql/payment.js
src/graphql/popularCompanyAndJobTitle.js
src/graphql/popularExperience.js
src/graphql/reply.js
src/graphql/timeAndSalary.js
src/graphql/userFeedback.js

Close #  
將 graphql 加上 `/* GraphQL */` 的註解，讓 eslint 可以自己排版 graphql syntax
無

chore: format graphql

---

src/components/CompanyAndJobTitle/useSearchbar.js
src/constants/gaConstants.js

feat: track search usage by GA4

---

public/robots.txt

Close #1387
將 robots.txt 放到 pubic 資料夾，會當作一般的 static file serve
```
ls -al build/public/
total 56
drwxr-xr-x 3 ycchen ycchen  4096 Aug  2 14:11 .
drwxr-xr-x 3 ycchen ycchen 24576 Aug  2 14:11 ..
-rw-r--r-- 1 ycchen ycchen 16958 Aug  2 14:11 favicon.ico
-rw-r--r-- 1 ycchen ycchen    76 Aug  2 14:11 robots.txt
drwxr-xr-x 5 ycchen ycchen  4096 Aug  2 14:11 static
```

feat: Add robots.txt to let google know our sitemap

---

src/components/ShareExperience/WorkExperiencesForm/TypeForm.js

Close #1409 
- dev 因為有評價表單，會跟 master branch 的 change 有衝突（會少一個 function parameter）。這個 PR 修復之

Fix: dev site is down

---

src/components/CompanyAndJobTitle/WorkExperiences/ExperienceEntry.js
src/components/ExperienceDetail/Article/RatingInfo.js
src/components/ExperienceDetail/Article/SectionBlock.js
src/components/ExperienceDetail/Article/SectionBlock.module.css
src/components/ExperienceDetail/Article/index.js
src/components/common/OverallRating/index.js
src/graphql/experience.js

Close #1374 
評價單篇頁面，
1. 顯示每一個面向的評分 rating。
2. 顯示每一個面向的 subtitle。
1. 分享工作心得(評價) > 留下多個不同面向 (包含自訂面向) 的分數、評論

feat: add OverallRating for different aspects

---

src/components/CompanyAndJobTitle/CompanyAndJobTitleWrapper.js
src/components/CompanyAndJobTitle/InterviewExperiences/InterviewExperiences.js
src/components/CompanyAndJobTitle/InterviewExperiences/index.js
src/components/CompanyAndJobTitle/Overview/index.js
src/components/CompanyAndJobTitle/StatusRenderer.js
src/components/CompanyAndJobTitle/TimeAndSalary/TimeAndSalary.js
src/components/CompanyAndJobTitle/TimeAndSalary/index.js
src/components/CompanyAndJobTitle/WorkExperiences/WorkExperiences.js
src/components/CompanyAndJobTitle/WorkExperiences/index.js

Close #1418
建立一個 Wrapper，統一用來處理 box 的狀態
轉址正常運作
```
curl -i http://localhost:3000/companies/%E5%8F%B0%E7%A9%8D%E9%9B%BB
HTTP/1.1 301 Moved Permanently
Location: /companies/%E5%8F%B0%E7%81%A3%E7%A9%8D%E9%AB%94%E9%9B%BB%E8%B7%AF%E8%A3%BD%E9%80%A0%E8%82%A1%E4%BB%BD%E6%9C%89%E9%99%90%E5%85%AC%E5%8F%B8
curl -i http://localhost:3000/companies/%E5%8F%B0%E7%A9%8D%E9%9B%BB/salary-work-times
curl -i http://localhost:3000/companies/%E5%8F%B0%E7%A9%8D%E9%9B%BB/work-experiences
curl -i http://localhost:3000/companies/%E5%8F%B0%E7%A9%8D%E9%9B%BB/interview-experiences
```
不存在的公司
```
curl -i http://localhost:3000/companies/not-exists
HTTP/1.1 404 Not Found
curl -i http://localhost:3000/companies/not-exists/salary-work-times
curl -i http://localhost:3000/companies/not-exists/work-experiences
curl -i …
```

refactor: [公司職稱頁面] handling 404 cases

---

src/components/CompanyAndJobTitle/InterviewExperiences/Helmet.js
src/components/CompanyAndJobTitle/InterviewExperiences/index.js
src/components/CompanyAndJobTitle/TimeAndSalary/Helmet.js
src/components/CompanyAndJobTitle/TimeAndSalary/index.js
src/components/CompanyAndJobTitle/WorkExperiences/Helmet.js
src/components/CompanyAndJobTitle/WorkExperiences/index.js

修正 helmet, 原本從 array length 拿，由於分頁，所以數量會錯誤
http://localhost:3000/companies/%E5%8F%B0%E7%81%A3%E7%A9%8D%E9%AB%94%E9%9B%BB%E8%B7%AF%E8%A3%BD%E9%80%A0%E8%82%A1%E4%BB%BD%E6%9C%89%E9%99%90%E5%85%AC%E5%8F%B8/work-experiences
可以看到 64 筆，數量正確

fix: [公司職稱頁面] helmet

---

src/actions/company.js
src/apis/company.js
src/components/CompanyAndJobTitle/CompanyAndJobTitleWrapper.js
src/components/CompanyAndJobTitle/CompanyAndJobTitleWrapper.module.css
src/graphql/company.js
src/pages/Company/CompanyInterviewExperiencesProvider.js
src/pages/Company/CompanyOverviewProvider.js
src/pages/Company/CompanyTimeAndSalaryProvider.js
src/pages/Company/CompanyWorkExperiencesProvider.js
src/reducers/companyIndex.js
src/selectors/companyAndJobTitle.js

For 工作心得改版 M1.5  https://github.com/goodjoblife/GoodJobShare/pull/1443

Merge dev into master 

---

src/hooks/experiments/useShareLink.js

- Base SEO traffic analysis ，評價這個字可能值得我們多累積一些資訊
- 評價表單調整至 45% 、面試經驗表單降至 10%

feat: increase work form to 45%

---

src/utils/GAUtils.js

Close #1465 
- fix the issue that user cannot submit form on Brave browser

fix: form submit issue on Brave browser

---

src/apis/interviewExperiencesApi.js
src/components/ShareExperience/InterviewForm/TypeForm/index.js
src/components/ShareExperience/constants.js
src/components/ShareExperience/questionCreators.js
src/components/common/FormBuilder/QuestionBuilder/CheckboxRatingTextAreaList/ActiveItem.js
src/components/common/FormBuilder/QuestionBuilder/CheckboxRatingTextAreaList/index.js
src/components/common/FormBuilder/QuestionBuilder/Rating.js
src/components/common/FormBuilder/QuestionBuilder/index.js
src/components/common/FormBuilder/index.js
src/graphql/experience.js

Close #1460  
更新面試過程、建議、問題，以 aspects 填寫
其中幾個問題的 rating 為 optional
另外串接 API
https://github.com/user-attachments/assets/6f60e684-d250-49ab-bbe2-5001450d8873

[面試表單] 更新面試過程、建議、問題

---

src/components/ExperienceDetail/Article/ArticleInfo.js
src/graphql/experience.js

Close #1458
新增評分數值在單篇。
- Back-end PR： https://github.com/goodjoblife/WorkTimeSurvey-backend/pull/1109
後端還沒好，所以要先本地 mock
```diff
diff --git a/src/components/ExperienceDetail/Article/ArticleInfo.js b/src/components/ExperienceDetail/Article/ArticleInfo.js
index e9d7481e..7f6fcb67 100644
--- a/src/components/ExperienceDetail/Article/ArticleInfo.js
+++ b/src/components/ExperienceDetail/Article/ArticleInfo.js
@@ -79,10 +79,10 @@ const InterviewInfoBlocks = ({ experience, hideContent }) => {
)}
</InfoBlock>
) : null}
-      {typeof experience.averageSectionRating !== 'undefined' ? (
+      {typeof experience.averageSectionRating === 'undefined' ? (
<InfoBlock label="評分">
<OverallRating
-            rating={experience.averageSectionRating}
+            rating={1.5}
hasRatingLabel
hasRatingNumber …
```

[面試經驗] 新增評分數值在單篇

---

src/apis/interviewExperiencesApi.js
src/components/CompanyAndJobTitle/InterviewExperiences/ExperienceEntry.js
src/components/CompanyAndJobTitle/InterviewExperiences/InterviewExperiences.module.css
src/components/ExperienceDetail/Article/ArticleInfo.js
src/components/ShareExperience/InterviewForm/TypeForm/index.js
src/graphql/company.js
src/graphql/experience.js
src/graphql/jobTitle.js
src/utils/uploadSuccessValueCalc.js

Close #1459
將評價的面向評分，套用至面試經驗。
https://hopk8t.axshare.com/#id=uaa5dh&p=%E9%9D%A2%E8%A9%A6%E5%8D%A1%E7%89%87&c=1
由於後端還沒完成，可以先本地 mock data
```diff
diff --git a/src/components/CompanyAndJobTitle/InterviewExperiences/ExperienceEntry.js b/src/components/CompanyAndJobTitle/InterviewExperiences/ExperienceEntry.js
index 50af3058..96079846 100644
--- a/src/components/CompanyAndJobTitle/InterviewExperiences/ExperienceEntry.js
+++ b/src/components/CompanyAndJobTitle/InterviewExperiences/ExperienceEntry.js
@@ -28,7 +28,7 @@ const ExperienceEntry = ({
created_at: createdAt,
salary,
overall_rating: overallRating,
-    averageSectionRating,
+    averageSectionRating = 1.5,
sections: [section],
},
size,
```

[面試經驗] 新增面向評分在卡片

---

src/actions/company.js
src/apis/company.js
src/components/CompanyAndJobTitle/InterviewExperiences/Helmet.js
src/components/CompanyAndJobTitle/InterviewExperiences/index.js
src/components/CompanyAndJobTitle/Overview/Helmet.js
src/components/CompanyAndJobTitle/Overview/index.js
src/components/CompanyAndJobTitle/TimeAndSalary/Helmet.js
src/components/CompanyAndJobTitle/TimeAndSalary/index.js
src/components/CompanyAndJobTitle/WorkExperiences/Helmet.js
src/graphql/company.js
src/pages/Company/CompanyInterviewExperiencesProvider.js
src/pages/Company/CompanyOverviewProvider.js
src/pages/Company/CompanyTimeAndSalaryProvider.js
src/pages/Company/useTopNJobTitles.js
src/reducers/companyIndex.js
src/selectors/companyAndJobTitle.js

Close #1407 
- 更新公司「總覽」、「面試列表」、「評價列表」、「薪水＆工時列表」頁面的 title & description
- PRD: https://goodjoblife.atlassian.net/wiki/spaces/GJ/pages/115867659/SEO+PRD

feat: update company page title & description (adding top n job title)

---

src/actions/company.js
src/apis/company.js

refactor: rename function name

---

src/actions/company.js
src/pages/Company/CompanyInterviewExperiencesProvider.js
src/pages/Company/CompanyOverviewProvider.js
src/pages/Company/CompanyTimeAndSalaryProvider.js
src/pages/Company/CompanyWorkExperiencesProvider.js
src/pages/Company/useCompanyName.js
src/pages/JobTitle/JobTitleInterviewExperiencesProvider.js
src/pages/JobTitle/JobTitleOverviewProvider.js
src/pages/JobTitle/JobTitleTimeAndSalaryProvider.js
src/pages/JobTitle/JobTitleWorkExperiencesProvider.js
src/pages/JobTitle/useJobTitle.js
src/routes.js

我們有 `company/usePageName` 和 `jobTitle/usePageName`，很容易搞混
這個 PR 改名為 `company/useCompanyName` 和 `jobTitle/useJobTitle`

chore: 重新命名 usePageName

---

src/actions/laborRights.js
src/apis/laborRightsApi.js
src/components/LaborRightsMenu/index.js
src/components/LaborRightsSingle/index.js
src/components/LaborRightsSingle/useEntry.js
src/components/LandingPage/index.js
src/graphql/laborRight.js
src/reducers/laborRights.js
src/selectors/laborRightsSelector.js

Close #  
改寫 勞動小教室的 redux 結構，改用 box 的方式實作（目前網站主要的 redux 格式）
頁面正常
SSR 正常

refactor: laborRights entry box

---

src/actions/company.js
src/actions/jobTitle.js
src/components/CompanyAndJobTitle/TimeAndSalary/TimeAndSalary.js
src/components/CompanyAndJobTitle/TimeAndSalary/index.js

沒有資料的時候不需要顯示統計區塊
Unblocking #1484
|Before|After|
|-|-|
|![畫面擷取於 2025-02-14 00 13 23](https://github.com/user-attachments/assets/e35c9ea1-b2f6-4453-aa20-23e678b92c6b)|![畫面擷取於 2025-02-14 00 13 16](https://github.com/user-attachments/assets/7f6fb3c9-5904-44ae-ae9a-10558268dcf4)|

[薪資工時頁面] 渲染空資料

---

src/components/CompanyAndJobTitle/TimeAndSalary/index.js

Close #1476  
當後端查無公司， `data` 會是 `null`，因此要特別檢查。

[公司頁面] 修復後端查無的公司

---

src/components/CompanyAndJobTitle/TimeAndSalary/EsgBlock/EsgBlock.js

Close #1508  
限制小數點
|Before|After|
|-|-|
|![畫面擷取於 2025-03-07 09 38 08](https://github.com/user-attachments/assets/90d92cf2-536c-44e9-ab4d-20d254d7fcdf)|![畫面擷取於 2025-03-07 09 38 00](https://github.com/user-attachments/assets/0406402d-927a-407b-822a-bce4c3006e49)|

[ESG] 修復小數點

---

src/components/CompanyAndJobTitle/Experience.js
src/components/CompanyAndJobTitle/InterviewExperiences/InterviewExperiences.js
src/components/CompanyAndJobTitle/InterviewExperiences/index.js
src/components/CompanyAndJobTitle/Sorter.js
src/components/CompanyAndJobTitle/WorkExperiences/WorkExperiences.js
src/components/CompanyAndJobTitle/WorkExperiences/WorkExperiences.module.css
src/components/CompanyAndJobTitle/WorkExperiences/index.js
src/components/CompanyAndJobTitle/styles.module.css
src/components/ExperienceDetail/Article/Article.module.css
src/components/ExperienceDetail/Article/ArticleInfo.js
src/components/ExperienceDetail/Article/index.js
src/components/ExperienceDetail/Article/visibility.js
src/components/ExperienceDetail/index.js
src/components/common/button/Button.js
src/components/common/global.module.css

Close #1505  
照 mockup 先做 UI，後續設計出來再另開 PR 補
https://a1c2km.axshare.com/?id=d577nl&g=1&p=%E9%9D%A2%E8%A9%A6%E8%A9%95%E5%83%B9%E5%88%97%E8%A1%A8%E9%A0%81%E9%9D%A2%E9%A1%AF%E7%A4%BA%E5%85%A8%E6%96%87_-_%E9%9B%BB%E8%85%A6%E7%89%88
https://github.com/user-attachments/assets/61232c54-6727-4e3e-8c1b-a26a090aedfb

[公司職稱頁面] 展開經驗

---

src/components/CompanyAndJobTitle/CompanyAndJobTitleWrapper.module.css
src/components/CompanyAndJobTitle/StatisticsCard/StatisticsCard.module.css
src/components/CompanyAndJobTitle/SubscribeNotificationButton/SubscribeNotificationButton.module.css

Close #1528 
1. 更新 `SubscribeNotificationButton`, `StatisticsCard` 字體大小、版面。
2. 修正手機版「訂閱通知按鈕」與標題的距離 [reference comment](https://github.com/goodjoblife/GoodJobShare/pull/1527#issuecomment-2781326265)。
1. 不同尺寸下的 `SubscribeNotificationButton`, `StatisticsCard` and responsive layout
2. 桌機版
3. 手機版 (小螢幕)
4. hover 狀態變化
5. 已訂閱樣式 
[confluence link](https://goodjoblife.atlassian.net/wiki/spaces/GJ/pages/130908165/PRD)
[Figma UI Link](https://www.figma.com/design/okGUQmeosjVn2hMRBNrx75/Goodjob?node-id=1795-3134&p=f&t=tj9LZTIlIo85IXVZ-0)
起 local 檢查 Responsive layout

feat: subscribe notification UI

---

package.json
src/components/App/index.js
src/components/CompanyAndJobTitle/StatisticsCard/StatisticsCard.module.css
src/components/CompanyAndJobTitle/StatisticsCard/index.js
yarn.lock

Close #  
Same as #1534 (no notification button), but add some fix
1. Add dependencies via yarn add 
2. remove all `// eslint-disable-next-line import/no-extraneous-dependencies`, it should not be used to skip warning

feat: statistics card skeleton

---

src/components/CompanyAndJobTitle/InterviewExperiences/InterviewExperiences.js
src/components/CompanyAndJobTitle/WorkExperiences/WorkExperiences.js
src/components/common/icons/Sort.js

hotfix: 消除warnings

---

src/components/CompanyAndJobTitle/Experience.js

Close #  
- refactor 確認值是否存在的方法，改用 `?.` optional chain operator，以簡化邏輯

refactor: use optional chain operator (?.)

---

src/hooks/viewLog/index.js

修復 track apis 使錯誤有被處理。
修復以前，錯誤的文章路徑會使頁面凍結，無法點選其他連結
修復後，即使錯誤的文章路徑導致 tracking error 也仍可以點選連結
<table>
<tr>
<th>Before</th>
<th>After</th>
</tr>
<tr>
<td>
https://github.com/user-attachments/assets/be4d8caf-ab20-4dd8-9397-75bb7e568f45
</td>
<td>
https://github.com/user-attachments/assets/8000ffdf-2e38-46c4-8279-0b72ad6a7434
</tr>
</tr>
</table>

[Track] 修復API錯誤

---

package.json
src/actions/auth.js
src/actions/company.js
src/actions/experience.js
src/actions/me.js
src/constants/companyJobTitle.js

chore: change code order

---

src/actions/company.js
src/apis/company.js
src/apis/queryCompanyEsgSalaryData.ts
src/apis/queryCompanyIsSubscribed.ts
src/apis/subscribeCompany.ts
src/apis/unsubscribeCompany.ts
src/graphql/company.ts

refactor: 逐步改寫 Company API

---

src/components/ShareExperience/InterviewForm/TypeForm/index.js
src/components/ShareExperience/TimeSalaryForm/TypeForm.js
src/components/ShareExperience/WorkExperiencesForm/TypeForm.js

- 追蹤有填寫性別為女性、有填寫性別友善度的使用者 for hotjar tracking ，用於使用者行為研究
- 需要部署到 prod 上面測試，因為會認 domain ，付費的功能只能用在一個 domain ，我會上線後測試

feat: hotjar track more fine grained session for research purpose
